export interface SeoLandingPage {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  subheading: string;
  heroDescription: string;
  painPoints: { title: string; description: string }[];
  features: { title: string; description: string; icon: string }[];
  howItWorks: { step: number; title: string; description: string }[];
  faqItems: { question: string; answer: string }[];
  ctaHeadline: string;
  ctaSubtext: string;
  industry: string;
}

export const seoLandingPages: SeoLandingPage[] = [
  {
    slug: "pool-rental-waivers",
    title: "Pool Rental Waivers",
    metaTitle: "Digital Pool Rental Waivers | Send & Sign in Minutes",
    metaDescription: "Protect your pool rental business with legally-binding digital waivers. Send, sign, and store liability waivers automatically. Start free.",
    h1: "Digital Waivers for Pool Rentals",
    subheading: "Protect your pool rental business from liability — without the paperwork",
    heroDescription: "Swimply hosts, private pool rental operators, and aquatic venues trust Rental Waivers to automate their liability protection. Send waivers before guests arrive, collect signatures on any device, and store everything securely for years.",
    painPoints: [
      { title: "Soggy paper waivers", description: "Paper forms get lost, damaged by water, and are impossible to organize. Go digital and never lose a signed waiver again." },
      { title: "Guests arrive without signing", description: "Automatically send waivers via email or text before the booking date. Guests sign before they even show up." },
      { title: "No proof in a dispute", description: "Every signature is timestamped, IP-logged, and stored with a tamper-proof PDF. You'll have evidence that holds up." },
    ],
    features: [
      { title: "Auto-send on booking", description: "Integrate with your booking platform to send waivers automatically when a reservation is made.", icon: "zap" },
      { title: "Mobile-friendly signing", description: "Guests sign on their phone in under 60 seconds. No app download required.", icon: "smartphone" },
      { title: "7-year secure storage", description: "All signed waivers are stored as tamper-proof PDFs with SHA-256 verification.", icon: "shield" },
    ],
    howItWorks: [
      { step: 1, title: "Create your waiver template", description: "Use our editor or paste your existing liability waiver. Add custom fields for guest info." },
      { step: 2, title: "Send to guests automatically", description: "Connect your booking platform or send manually via email. Guests get a secure signing link." },
      { step: 3, title: "Guests sign on any device", description: "Full legal name, initials, and drawn signature — all captured with timestamps and IP logging." },
      { step: 4, title: "Access signed waivers anytime", description: "Download PDFs, check audit trails, and prove compliance whenever you need to." },
    ],
    faqItems: [
      { question: "Are digital pool waivers legally binding?", answer: "Yes. Electronic signatures are legally binding under the ESIGN Act and UETA in all 50 US states. Our waivers capture full name, drawn signature, timestamp, and IP address for maximum enforceability." },
      { question: "Can guests sign before they arrive?", answer: "Absolutely. That's the whole point. Send waivers via email when they book, and they sign from their phone before showing up." },
      { question: "How long are signed waivers stored?", answer: "By default, 7 years. You can configure retention periods up to 99 years in your organization settings." },
      { question: "Do I need a subscription?", answer: "No. Rental Waivers uses a pay-per-waiver model starting at just 6¢ per waiver. No monthly fees." },
    ],
    ctaHeadline: "Protect your pool rental business today",
    ctaSubtext: "Start sending digital waivers in under 5 minutes. No subscription required.",
    industry: "pool-rental",
  },
  {
    slug: "boat-rental-waivers",
    title: "Boat Rental Waivers",
    metaTitle: "Digital Boat Rental Waivers | Liability Protection for Boat Owners",
    metaDescription: "Protect your boat rental business with digital liability waivers. Automatically send, collect signatures, and store securely. Starting at 6¢/waiver.",
    h1: "Digital Waivers for Boat Rentals",
    subheading: "Liability protection for boat rental operators — fully automated",
    heroDescription: "Whether you rent pontoons, speedboats, or sailboats, Rental Waivers automates your liability protection. Send waivers before renters hit the water, capture legally-binding signatures, and keep tamper-proof records for years.",
    painPoints: [
      { title: "Renters skip the paperwork", description: "When excitement takes over, waivers get forgotten. Send them digitally before arrival so they're done before the dock." },
      { title: "Water destroys paper", description: "Marina environments are hostile to paper. Digital waivers are stored securely in the cloud, never at risk." },
      { title: "Insurance requires proof", description: "When claims happen, you need signed waivers fast. Access any waiver instantly from your dashboard." },
    ],
    features: [
      { title: "Pre-arrival signing", description: "Renters receive and sign waivers on their phone before they show up at the marina.", icon: "zap" },
      { title: "Custom fields", description: "Capture boat number, experience level, number of passengers — whatever your operation needs.", icon: "clipboard" },
      { title: "Audit trail", description: "Every action is logged: when the waiver was sent, opened, and signed, with IP and device info.", icon: "shield" },
    ],
    howItWorks: [
      { step: 1, title: "Build your waiver", description: "Create a waiver template with your liability language and custom fields for boat-specific info." },
      { step: 2, title: "Send automatically", description: "Connect to your booking system or send via email/QR code at the dock." },
      { step: 3, title: "Collect signatures", description: "Renters sign on their phone — full name, initials, and drawn signature." },
      { step: 4, title: "Stay protected", description: "Access signed waivers anytime. Download PDFs for insurance claims." },
    ],
    faqItems: [
      { question: "Are digital boat rental waivers legally enforceable?", answer: "Yes. Under the ESIGN Act, electronic signatures are as legally binding as ink signatures. Our system captures comprehensive evidence including timestamps, IP addresses, and device information." },
      { question: "Can renters sign at the dock?", answer: "Yes! Use our kiosk mode with a QR code. Renters scan and sign on their own phone in under a minute." },
      { question: "Do you integrate with marina booking software?", answer: "We integrate via API and webhooks with any booking platform. Contact us for specific integration help." },
      { question: "What does it cost?", answer: "Pay-per-waiver starting at 6¢. No monthly fees, no contracts. Buy credits in bulk for better rates." },
    ],
    ctaHeadline: "Keep your boat rental operation protected",
    ctaSubtext: "Digital waivers that work as hard as you do. Set up in minutes.",
    industry: "boat-rental",
  },
  {
    slug: "jet-ski-rental-waivers",
    title: "Jet Ski Rental Waivers",
    metaTitle: "Jet Ski Rental Waivers | Digital Liability Protection",
    metaDescription: "Digital liability waivers for jet ski rental operators. Auto-send before rides, collect e-signatures, and store securely. No monthly fees.",
    h1: "Digital Waivers for Jet Ski Rentals",
    subheading: "High-speed fun needs airtight liability protection",
    heroDescription: "Jet ski rentals carry inherent risk. Protect your business with digital waivers that get signed before riders hit the water. Capture signatures, log consent, and store everything securely.",
    painPoints: [
      { title: "High-risk activity", description: "Jet skiing is one of the highest-liability water activities. Digital waivers ensure every rider has acknowledged the risks." },
      { title: "Rushed check-ins", description: "Riders want to go fast — not fill out paperwork. Let them sign digitally before they arrive." },
      { title: "Multiple riders per booking", description: "Group waivers let every rider in a party sign individually with one shared link." },
    ],
    features: [
      { title: "Group signing links", description: "One link for the whole group. Each rider signs individually with their own name and signature.", icon: "users" },
      { title: "Safety acknowledgment fields", description: "Add checkboxes for safety briefing confirmation, experience level, and age verification.", icon: "check-square" },
      { title: "Instant PDF generation", description: "Signed waivers are immediately available as downloadable PDFs with full audit trails.", icon: "file-text" },
    ],
    howItWorks: [
      { step: 1, title: "Create your jet ski waiver", description: "Include liability language, safety rules, and custom fields for rider info." },
      { step: 2, title: "Send or display", description: "Email the waiver link or display a QR code at your rental counter." },
      { step: 3, title: "All riders sign", description: "Each person in the group signs individually on their own device." },
      { step: 4, title: "Ride with confidence", description: "Every rider is covered. Access records anytime from your dashboard." },
    ],
    faqItems: [
      { question: "Can each rider in a group sign separately?", answer: "Yes! Our group signing feature creates one shared link where each rider signs individually with their own name and signature." },
      { question: "Can I add a safety briefing checklist?", answer: "Absolutely. Add custom checkbox fields for safety rules, age verification, swimming ability, and more." },
      { question: "What if a rider is a minor?", answer: "Include a guardian signature field in your template. The guardian signs on behalf of the minor." },
      { question: "Is there a monthly fee?", answer: "No. Pay only for what you use — starting at 6¢ per waiver. No subscriptions." },
    ],
    ctaHeadline: "Protect every ride with digital waivers",
    ctaSubtext: "Set up in minutes. No monthly fees. Just peace of mind.",
    industry: "jet-ski-rental",
  },
  {
    slug: "kayak-rental-waivers",
    title: "Kayak Rental Waivers",
    metaTitle: "Kayak Rental Waivers | Digital Liability Forms for Kayak Operators",
    metaDescription: "Streamline your kayak rental operation with digital waivers. Guests sign before they paddle. Secure storage, audit trails, no monthly fees.",
    h1: "Digital Waivers for Kayak Rentals",
    subheading: "Simple, secure liability protection for kayak rental operators",
    heroDescription: "From guided tours to hourly rentals, kayak operators need reliable waiver collection. Rental Waivers lets paddlers sign before they arrive, so you can focus on the experience — not the paperwork.",
    painPoints: [
      { title: "Outdoor environments", description: "Clipboards and paper don't survive wind, water, and sun. Digital waivers are always accessible." },
      { title: "Seasonal staff confusion", description: "New staff forget to collect waivers. Automation ensures every renter is covered." },
      { title: "Tour groups", description: "Collecting waivers from a group of 20 is chaos on paper. One link handles them all." },
    ],
    features: [
      { title: "QR code at launch point", description: "Display a QR code at your rental counter or launch point. Renters scan and sign in seconds.", icon: "qr-code" },
      { title: "Bulk send for tours", description: "Send one waiver link to your entire tour group. Everyone signs individually.", icon: "send" },
      { title: "Weather-proof records", description: "Cloud storage means your records survive any conditions. Access from anywhere.", icon: "cloud" },
    ],
    howItWorks: [
      { step: 1, title: "Set up your template", description: "Create a waiver with your liability terms, safety rules, and rental policies." },
      { step: 2, title: "Distribute the link", description: "Email it with bookings, post a QR code, or share via text message." },
      { step: 3, title: "Paddlers sign digitally", description: "Guests sign on their phone in under a minute — no app needed." },
      { step: 4, title: "Records stored securely", description: "Every signed waiver is stored with timestamps and audit trails for years." },
    ],
    faqItems: [
      { question: "Can I use a QR code at my rental shop?", answer: "Yes! Generate a QR code for any waiver template and display it at your counter, on signage, or at the launch point." },
      { question: "What about guided tour groups?", answer: "Use group signing — one link for the whole group where each participant signs individually." },
      { question: "Do I need wifi for guests to sign?", answer: "Guests need a mobile data or wifi connection on their phone. The signing page is lightweight and works on any connection." },
      { question: "How much does it cost?", answer: "Pay-per-waiver starting at 6¢. No monthly fees. Perfect for seasonal operations." },
    ],
    ctaHeadline: "Paddle without paperwork",
    ctaSubtext: "Digital waivers for kayak rentals. Set up in 5 minutes, pay per waiver.",
    industry: "kayak-rental",
  },
  {
    slug: "airbnb-host-waivers",
    title: "Airbnb Host Waivers",
    metaTitle: "Airbnb Host Waivers | Protect Your Short-Term Rental Property",
    metaDescription: "Send digital liability waivers to Airbnb guests automatically. Protect your property with legally-binding e-signatures. Starting at 6¢/waiver.",
    h1: "Digital Waivers for Airbnb Hosts",
    subheading: "Protect your property and yourself — before guests check in",
    heroDescription: "As an Airbnb host, you're responsible for guest safety. Rental Waivers lets you send liability waivers automatically when guests book, so they sign before they arrive. Pool rules, house rules, damage policies — all acknowledged in writing.",
    painPoints: [
      { title: "Verbal agreements don't hold up", description: "A spoken 'I understand the pool rules' means nothing in court. Get it in writing, digitally." },
      { title: "Guests ignore house rules", description: "When guests sign a waiver acknowledging rules, they take them seriously. It changes behavior." },
      { title: "No time for manual follow-up", description: "Automate waiver delivery on every booking. Set it and forget it." },
    ],
    features: [
      { title: "Booking integration", description: "Connect with Hospitable, Guesty, and other PMS tools to auto-send waivers on booking.", icon: "link" },
      { title: "Custom property rules", description: "Template variables let you customize waivers per listing — pool rules, pet policies, quiet hours.", icon: "home" },
      { title: "Guest compliance tracking", description: "See at a glance which guests have signed and which need a reminder.", icon: "check-circle" },
    ],
    howItWorks: [
      { step: 1, title: "Create your property waiver", description: "Include liability terms, house rules, pool/hot tub policies, and damage agreements." },
      { step: 2, title: "Connect your booking platform", description: "Integrate via API to auto-send waivers when guests book." },
      { step: 3, title: "Guests sign before check-in", description: "Guests receive the waiver via email and sign on their phone." },
      { step: 4, title: "Full protection on file", description: "Access signed waivers from your dashboard. Download PDFs for insurance." },
    ],
    faqItems: [
      { question: "Does this integrate with Airbnb directly?", answer: "We integrate with property management tools like Hospitable, Guesty, and Lodgify that connect to Airbnb. Direct Airbnb API integration is on our roadmap." },
      { question: "Can I have different waivers for different properties?", answer: "Yes! Create a separate template for each listing with property-specific rules and policies." },
      { question: "Will guests actually sign?", answer: "Yes — hosts report 90%+ completion rates because waivers are sent immediately after booking while engagement is high." },
      { question: "What if a guest doesn't sign?", answer: "Set up automatic reminders. You can also require waiver completion before sharing check-in instructions." },
    ],
    ctaHeadline: "Protect your Airbnb listings",
    ctaSubtext: "Auto-send waivers on every booking. Starting at 6¢ per guest.",
    industry: "airbnb",
  },
  {
    slug: "vacation-rental-waivers",
    title: "Vacation Rental Waivers",
    metaTitle: "Vacation Rental Waivers | Digital Liability Protection for VRBO & STR",
    metaDescription: "Send digital liability waivers to vacation rental guests automatically. Protect your property and reduce liability. No monthly fees.",
    h1: "Digital Waivers for Vacation Rentals",
    subheading: "Liability protection for VRBO, Booking.com, and direct booking hosts",
    heroDescription: "Vacation rental properties with pools, hot tubs, docks, or outdoor amenities need liability waivers. Automate the entire process — from sending to signing to secure storage.",
    painPoints: [
      { title: "Multiple amenity risks", description: "Pools, hot tubs, fire pits, docks — each amenity is a liability. One waiver covers them all." },
      { title: "Remote management", description: "You can't hand guests a clipboard when you manage remotely. Digital waivers work from anywhere." },
      { title: "Insurance requirements", description: "Many insurers require signed waivers. Digital records make compliance effortless." },
    ],
    features: [
      { title: "Multi-platform integration", description: "Works with VRBO, Booking.com, and direct booking systems via API.", icon: "globe" },
      { title: "Template variables", description: "Personalize waivers with guest name, property address, and check-in dates automatically.", icon: "file-text" },
      { title: "Automated reminders", description: "Guests who haven't signed get gentle reminders. No manual follow-up needed.", icon: "bell" },
    ],
    howItWorks: [
      { step: 1, title: "Build your waiver template", description: "Include all amenity-specific liability language and house rules." },
      { step: 2, title: "Automate delivery", description: "Connect your PMS or send via our API when bookings are confirmed." },
      { step: 3, title: "Guests sign remotely", description: "Guests sign on their phone or computer before check-in." },
      { step: 4, title: "Secure storage", description: "All signed waivers stored as tamper-proof PDFs for 7+ years." },
    ],
    faqItems: [
      { question: "Does this work with VRBO and Booking.com?", answer: "Yes — via property management system integrations. We support Hospitable, Guesty, Lodgify, and custom API connections." },
      { question: "Can I include damage deposit agreements?", answer: "Yes. Your waiver template can include any legal language — liability, damage policies, house rules, and more." },
      { question: "How do I know if guests signed?", answer: "Your dashboard shows real-time status for every waiver: sent, viewed, and signed. Set up webhook notifications too." },
      { question: "What's the pricing?", answer: "Pay-per-waiver starting at 6¢. No monthly subscriptions. Perfect for seasonal or multi-property operations." },
    ],
    ctaHeadline: "Protect every vacation rental booking",
    ctaSubtext: "Digital waivers that work while you sleep. Set up in minutes.",
    industry: "vacation-rental",
  },
  {
    slug: "short-term-rental-waivers",
    title: "Short-Term Rental Waivers",
    metaTitle: "Short-Term Rental Waivers | Digital Liability Forms for STR Hosts",
    metaDescription: "Automate liability waiver collection for your short-term rental. Guests sign digitally before check-in. Secure, legal, affordable.",
    h1: "Digital Waivers for Short-Term Rentals",
    subheading: "Automated liability protection for every STR booking",
    heroDescription: "Short-term rental hosts face unique liability challenges. Rental Waivers automates the entire waiver process — send on booking, sign before check-in, store for years. Protect your STR business effortlessly.",
    painPoints: [
      { title: "High guest turnover", description: "With new guests every few days, manual waiver collection is unsustainable. Automation is essential." },
      { title: "Varied amenity risks", description: "Each property has different risk factors. Customize templates per listing." },
      { title: "Multi-property management", description: "Managing waivers across 5, 10, or 50 properties? One dashboard handles them all." },
    ],
    features: [
      { title: "Per-listing templates", description: "Create unique waivers for each property with specific amenity warnings and rules.", icon: "layers" },
      { title: "Dashboard overview", description: "See waiver status across all properties in one place. Filter by property, status, or date.", icon: "layout-dashboard" },
      { title: "API for scale", description: "Use our REST API to integrate with any property management system or custom workflow.", icon: "code" },
    ],
    howItWorks: [
      { step: 1, title: "Create templates per property", description: "Build waiver templates for each listing with relevant liability terms." },
      { step: 2, title: "Connect your PMS", description: "Integrate via API or webhooks to auto-send waivers on new bookings." },
      { step: 3, title: "Guests sign pre-arrival", description: "Waivers are sent immediately and guests sign before they show up." },
      { step: 4, title: "Manage all properties", description: "One dashboard shows every waiver across your entire portfolio." },
    ],
    faqItems: [
      { question: "Can I manage multiple properties?", answer: "Yes! Create separate templates for each property and manage all waivers from one dashboard." },
      { question: "Does it work with my PMS?", answer: "We integrate via API with Hospitable, Guesty, Lodgify, and any system with webhook support." },
      { question: "How many waivers can I send?", answer: "Unlimited. Buy credits in bulk — the more you buy, the cheaper each waiver gets (as low as 6¢)." },
      { question: "Is there a contract?", answer: "No contracts, no subscriptions. Pay per waiver, use as needed." },
    ],
    ctaHeadline: "Scale your STR liability protection",
    ctaSubtext: "One platform for all your short-term rental waivers.",
    industry: "str",
  },
  {
    slug: "property-manager-waivers",
    title: "Property Manager Waivers",
    metaTitle: "Property Manager Waivers | Bulk Digital Waivers for PM Companies",
    metaDescription: "Property management companies use Rental Waivers to automate guest liability forms across their portfolio. API-first, scalable, affordable.",
    h1: "Digital Waivers for Property Managers",
    subheading: "Scale liability protection across your entire portfolio",
    heroDescription: "Property management companies need waiver solutions that scale. Rental Waivers provides API-first automation, multi-property dashboards, team access, and bulk pricing built for operators managing 10 to 1,000+ units.",
    painPoints: [
      { title: "Inconsistent processes", description: "Different properties, different hosts, different waiver practices. Standardize everything." },
      { title: "Team coordination", description: "Your team needs shared access to waiver records. Role-based access keeps everyone aligned." },
      { title: "Owner reporting", description: "Property owners want proof of compliance. Export signed waivers anytime." },
    ],
    features: [
      { title: "Team roles", description: "Admin and host roles with appropriate permissions. Admins manage templates, hosts view waivers.", icon: "users" },
      { title: "Bulk operations", description: "Send waivers to entire booking lists at once. Perfect for seasonal openings.", icon: "send" },
      { title: "API & webhooks", description: "Full REST API and webhook notifications for seamless PMS integration.", icon: "webhook" },
    ],
    howItWorks: [
      { step: 1, title: "Set up your org", description: "Create your organization and invite team members with appropriate roles." },
      { step: 2, title: "Build templates by property", description: "Create tailored waivers for each property type and amenity set." },
      { step: 3, title: "Automate at scale", description: "Use the API to connect with your PMS and auto-send waivers for every booking." },
      { step: 4, title: "Monitor compliance", description: "Dashboard analytics show signing rates, pending waivers, and compliance status." },
    ],
    faqItems: [
      { question: "How many team members can I add?", answer: "Unlimited team members. Assign admin or host roles based on responsibilities." },
      { question: "Can property owners access waivers?", answer: "Yes — export signed waivers as PDFs or give owners limited dashboard access." },
      { question: "What about volume pricing?", answer: "Credit packages offer bulk discounts. 8,000 credits for $500 works out to about 6¢ per waiver." },
      { question: "Is there an API?", answer: "Yes! Full REST API with documentation. Create envelopes, check status, and receive webhook notifications." },
    ],
    ctaHeadline: "Enterprise-grade waiver management",
    ctaSubtext: "Built for property management companies. Scale with confidence.",
    industry: "property-management",
  },
  {
    slug: "atv-rental-waivers",
    title: "ATV Rental Waivers",
    metaTitle: "ATV Rental Waivers | Digital Liability Protection for Off-Road Rentals",
    metaDescription: "Protect your ATV rental business with digital liability waivers. Riders sign before they ride. Legally binding, affordable, no subscription.",
    h1: "Digital Waivers for ATV Rentals",
    subheading: "High-risk activity demands airtight liability protection",
    heroDescription: "ATV rentals carry significant liability. Rental Waivers ensures every rider acknowledges the risks before they ride. Digital signatures, safety acknowledgments, and tamper-proof storage keep your business protected.",
    painPoints: [
      { title: "Extreme liability exposure", description: "ATVs are inherently dangerous. A signed waiver is your first line of defense in any claim." },
      { title: "Riders just want to ride", description: "Nobody wants to fill out forms trailside. Digital waivers get signed before riders arrive." },
      { title: "Group outings", description: "Bachelor parties, corporate events, family trips — collect individual signatures from everyone." },
    ],
    features: [
      { title: "Safety checklist fields", description: "Add required checkboxes for helmet use, experience level, age verification, and safety briefing acknowledgment.", icon: "check-square" },
      { title: "Group waivers", description: "One link for the whole group. Each rider signs individually — perfect for group bookings.", icon: "users" },
      { title: "Photo ID capture", description: "Add file upload fields so riders can submit a photo of their driver's license.", icon: "camera" },
    ],
    howItWorks: [
      { step: 1, title: "Create your ATV waiver", description: "Include comprehensive liability terms, safety rules, and equipment condition acknowledgment." },
      { step: 2, title: "Send before the ride", description: "Email waivers when bookings are confirmed. Riders sign on their phone." },
      { step: 3, title: "Every rider signs", description: "Group links ensure every participant signs individually." },
      { step: 4, title: "Ride with confidence", description: "All signatures are timestamped and stored securely. Access anytime." },
    ],
    faqItems: [
      { question: "Can I require a safety quiz?", answer: "Use custom checkbox fields to create a safety acknowledgment checklist that riders must complete before signing." },
      { question: "What about minors riding ATVs?", answer: "Include a parent/guardian signature field. The guardian signs on behalf of the minor rider." },
      { question: "Do digital waivers hold up for high-risk activities?", answer: "Yes. Courts have consistently upheld properly executed electronic waivers under the ESIGN Act. Our comprehensive evidence capture strengthens enforceability." },
      { question: "How fast can I set this up?", answer: "Under 5 minutes. Create a template, send your first waiver, and you're protected." },
    ],
    ctaHeadline: "Protect every ATV ride",
    ctaSubtext: "Digital waivers for off-road rental operators. No subscription, no hassle.",
    industry: "atv-rental",
  },
  {
    slug: "golf-cart-rental-waivers",
    title: "Golf Cart Rental Waivers",
    metaTitle: "Golf Cart Rental Waivers | Digital Liability Forms for Cart Rentals",
    metaDescription: "Digital liability waivers for golf cart rental businesses. Easy signing, secure storage, no monthly fees. Protect your fleet.",
    h1: "Digital Waivers for Golf Cart Rentals",
    subheading: "Protect your fleet and your business with digital waivers",
    heroDescription: "Golf cart rentals at resorts, beach towns, and retirement communities need liability protection. Rental Waivers automates the process — renters sign before they drive, and you're covered.",
    painPoints: [
      { title: "Damage disputes", description: "Without a signed waiver documenting pre-rental conditions, damage claims become he-said-she-said." },
      { title: "Tourist turnover", description: "New renters every day means hundreds of waivers per season. Automate or drown in paper." },
      { title: "Local regulations", description: "Many jurisdictions require documented safety acknowledgments. Digital records prove compliance." },
    ],
    features: [
      { title: "Pre-rental condition form", description: "Capture existing damage, battery level, and cart number before each rental.", icon: "clipboard" },
      { title: "Kiosk mode", description: "Set up a tablet at your counter with a QR code. Renters scan and sign on their phone.", icon: "monitor" },
      { title: "Bulk credits", description: "High-volume operations save with bulk credit packages — as low as 6¢ per waiver.", icon: "coins" },
    ],
    howItWorks: [
      { step: 1, title: "Set up your template", description: "Include liability terms, driving rules, damage policies, and cart condition fields." },
      { step: 2, title: "Display at your counter", description: "QR code kiosk mode lets walk-in renters sign instantly." },
      { step: 3, title: "Renters sign on the spot", description: "Quick mobile signing takes under 60 seconds." },
      { step: 4, title: "Records for every rental", description: "Every signed waiver is stored with full audit trail." },
    ],
    faqItems: [
      { question: "Can I use this for walk-in rentals?", answer: "Yes! Kiosk mode with QR codes is perfect for walk-in operations. Renters scan and sign on their own phone." },
      { question: "Can I document cart condition before rental?", answer: "Yes. Add custom fields for cart number, condition notes, and damage descriptions." },
      { question: "What about fleet tracking?", answer: "Use custom fields to log cart numbers per waiver for easy cross-referencing." },
      { question: "Is this affordable for seasonal businesses?", answer: "Absolutely. No monthly fees — pay only when you use it. Perfect for seasonal operations." },
    ],
    ctaHeadline: "Digital waivers for every cart rental",
    ctaSubtext: "Kiosk-ready, mobile-friendly, built for high-volume operations.",
    industry: "golf-cart-rental",
  },
  {
    slug: "bounce-house-rental-waivers",
    title: "Bounce House Rental Waivers",
    metaTitle: "Bounce House Rental Waivers | Digital Liability Protection",
    metaDescription: "Protect your bounce house rental business with digital liability waivers. Parents sign before kids bounce. Legally binding, starting at 6¢.",
    h1: "Digital Waivers for Bounce House Rentals",
    subheading: "Keep kids safe and your business protected",
    heroDescription: "Bounce houses are fun — but injuries happen. Protect your rental business with digital waivers that parents sign before the party starts. Capture acknowledgment of risks, safety rules, and supervision requirements.",
    painPoints: [
      { title: "Children's safety liability", description: "When kids get hurt, lawsuits follow. A signed waiver from the parent is essential protection." },
      { title: "Event chaos", description: "Nobody's tracking down parents for signatures at a birthday party. Get it done before delivery." },
      { title: "Multiple families", description: "Group events mean waivers from every family. One link handles them all." },
    ],
    features: [
      { title: "Parent/guardian signing", description: "Waivers are designed for adult signatures on behalf of minor children.", icon: "user-check" },
      { title: "Pre-event delivery", description: "Send waivers to the booking parent who shares with other families before the event.", icon: "send" },
      { title: "Safety rules acknowledgment", description: "Built-in fields for age restrictions, weight limits, and supervision requirements.", icon: "shield" },
    ],
    howItWorks: [
      { step: 1, title: "Create your bounce house waiver", description: "Include liability language, safety rules, age/weight limits, and supervision requirements." },
      { step: 2, title: "Send to the booking party", description: "Email the waiver link when the rental is booked. They share with other parents." },
      { step: 3, title: "All parents sign", description: "Group signing lets each parent/guardian sign individually for their children." },
      { step: 4, title: "Deliver with confidence", description: "Every family is covered before the bounce house is even inflated." },
    ],
    faqItems: [
      { question: "Can parents sign for their children?", answer: "Yes — waivers are specifically designed for parent/guardian signatures acknowledging risks for minor children." },
      { question: "What about events with multiple families?", answer: "Use group signing! Send one link and every parent signs individually. Perfect for birthday parties and community events." },
      { question: "When should I send the waiver?", answer: "Send immediately after booking. Parents complete it days before the event — no last-minute scramble." },
      { question: "How does pricing work?", answer: "One waiver per booking (or per family for group events). Starting at 6¢ each with no monthly fees." },
    ],
    ctaHeadline: "Bounce house rentals, fully protected",
    ctaSubtext: "Parents sign before the party. You focus on the fun.",
    industry: "bounce-house",
  },
  {
    slug: "party-equipment-rental-waivers",
    title: "Party Equipment Rental Waivers",
    metaTitle: "Party Equipment Rental Waivers | Liability Forms for Event Rentals",
    metaDescription: "Digital liability waivers for party and event equipment rentals. Tables, chairs, tents, inflatables — protect your business. No subscription.",
    h1: "Digital Waivers for Party Equipment Rentals",
    subheading: "Protect your equipment and your business at every event",
    heroDescription: "Party equipment rentals — tents, tables, chairs, stages, inflatables — all carry liability. Rental Waivers automates damage agreements and liability waivers so you're protected at every event.",
    painPoints: [
      { title: "Equipment damage", description: "Renters don't treat equipment like their own. Signed damage agreements change behavior." },
      { title: "Setup liability", description: "If a tent collapses or a table breaks, you need proof the renter accepted responsibility." },
      { title: "Volume business", description: "Weekends are packed with events. Manual waiver tracking doesn't scale." },
    ],
    features: [
      { title: "Damage & liability combined", description: "One waiver covers both liability for injuries and responsibility for equipment damage.", icon: "shield" },
      { title: "Equipment checklist", description: "Custom fields for items rented, quantities, and condition at delivery.", icon: "clipboard" },
      { title: "Automatic with bookings", description: "API integration sends waivers when events are booked.", icon: "zap" },
    ],
    howItWorks: [
      { step: 1, title: "Build your rental agreement waiver", description: "Include liability terms, equipment condition, damage policies, and rental terms." },
      { step: 2, title: "Send with confirmations", description: "Attach the waiver to booking confirmations automatically." },
      { step: 3, title: "Renters sign before delivery", description: "Event organizers sign acknowledging terms before equipment arrives." },
      { step: 4, title: "Protected at every event", description: "Access signed agreements from your dashboard anytime." },
    ],
    faqItems: [
      { question: "Can I list specific equipment rented?", answer: "Yes. Use custom fields and template variables to include specific items, quantities, and pricing." },
      { question: "What about damage deposits?", answer: "Include damage deposit terms and conditions in your waiver template." },
      { question: "Can event organizers forward the waiver?", answer: "Yes — the signing link can be shared so additional responsible parties can sign too." },
      { question: "Pricing for high-volume?", answer: "Bulk credits get as low as 6¢ per waiver. No monthly fees — perfect for seasonal peaks." },
    ],
    ctaHeadline: "Protect every rental, every event",
    ctaSubtext: "Digital waivers built for party equipment rental companies.",
    industry: "party-equipment",
  },
  {
    slug: "rv-rental-waivers",
    title: "RV Rental Waivers",
    metaTitle: "RV Rental Waivers | Digital Liability Protection for RV Owners",
    metaDescription: "Protect your RV rental with digital liability waivers. Renters sign before the road trip. Damage agreements, safety acknowledgments, secure storage.",
    h1: "Digital Waivers for RV Rentals",
    subheading: "Protect your investment with comprehensive digital waivers",
    heroDescription: "RVs are expensive assets. Whether you rent through Outdoorsy, RVshare, or direct booking, Rental Waivers protects you with digital liability and damage agreements that renters sign before they drive off.",
    painPoints: [
      { title: "High-value asset risk", description: "RVs cost $50K-$200K+. A signed waiver documenting the renter's responsibilities is non-negotiable." },
      { title: "Remote handoffs", description: "Many RV rentals involve remote pickup. Digital waivers work even when you're not there." },
      { title: "Complex liability", description: "Driving, camping, propane, generators — RVs involve multiple risk categories." },
    ],
    features: [
      { title: "Vehicle condition report", description: "Custom fields for mileage, fuel level, damage photos, and equipment checklist.", icon: "clipboard" },
      { title: "Driver info capture", description: "Collect driver's license number, insurance info, and driving experience.", icon: "id-card" },
      { title: "Pre-trip signing", description: "Renters sign before pickup, giving you time to review and approve.", icon: "clock" },
    ],
    howItWorks: [
      { step: 1, title: "Create your RV waiver", description: "Comprehensive liability, damage, and rental terms for your specific vehicle." },
      { step: 2, title: "Send on booking", description: "Automatically send when a rental is confirmed." },
      { step: 3, title: "Renter signs pre-trip", description: "Full legal signature with all required acknowledgments." },
      { step: 4, title: "Secure documentation", description: "Tamper-proof PDF with audit trail. Access anytime for claims." },
    ],
    faqItems: [
      { question: "Does this work with Outdoorsy and RVshare?", answer: "We integrate via API. Send waivers automatically when bookings are confirmed on any platform." },
      { question: "Can I capture driver's license info?", answer: "Yes. Add custom text and file upload fields for license numbers, insurance details, and photos." },
      { question: "What about security deposits?", answer: "Include deposit terms in your waiver. The signed agreement serves as documentation." },
      { question: "Is this suitable for fleet operators?", answer: "Absolutely. Manage templates per vehicle type and send waivers at scale via API." },
    ],
    ctaHeadline: "Protect your RV before every trip",
    ctaSubtext: "Digital rental agreements that protect your investment.",
    industry: "rv-rental",
  },
  {
    slug: "bike-rental-waivers",
    title: "Bike Rental Waivers",
    metaTitle: "Bike Rental Waivers | Digital Liability Forms for Bicycle Rentals",
    metaDescription: "Digital liability waivers for bike rental shops and tour operators. Riders sign on their phone. No app, no paper, no hassle. Starting at 6¢.",
    h1: "Digital Waivers for Bike Rentals",
    subheading: "Quick, simple liability protection for every ride",
    heroDescription: "Bike rental shops, e-bike operators, and cycling tour companies use Rental Waivers to collect signed liability forms before every ride. Mobile-friendly, fast signing, and secure storage.",
    painPoints: [
      { title: "Quick-turnaround rentals", description: "Hourly bike rentals move fast. You need waivers signed in seconds, not minutes." },
      { title: "Tourist volume", description: "Beach towns and tourist areas process hundreds of rentals daily. Scale without drowning in paper." },
      { title: "E-bike liability", description: "E-bikes carry higher risk and speed. Proper waivers are even more critical." },
    ],
    features: [
      { title: "30-second signing", description: "Optimized mobile flow gets riders signed and riding in under a minute.", icon: "zap" },
      { title: "Kiosk QR code", description: "Walk-in renters scan a QR code and sign on their own phone.", icon: "qr-code" },
      { title: "Helmet acknowledgment", description: "Checkbox fields for helmet use, safety rules, and road law acknowledgment.", icon: "check-square" },
    ],
    howItWorks: [
      { step: 1, title: "Set up your bike waiver", description: "Liability terms, helmet policy, route restrictions, and damage responsibility." },
      { step: 2, title: "Display QR or send link", description: "Counter QR code for walk-ins, email links for reservations." },
      { step: 3, title: "Riders sign instantly", description: "Quick mobile signing — full name, initials, and signature." },
      { step: 4, title: "Every ride documented", description: "Secure records for every rental. Access from anywhere." },
    ],
    faqItems: [
      { question: "How fast can a rider sign?", answer: "Under 60 seconds. Our signing flow is optimized for speed — perfect for high-turnover bike shops." },
      { question: "Does it work for e-bike rentals?", answer: "Yes. Create specific templates for e-bikes with speed acknowledgments and additional liability terms." },
      { question: "Can I use it for guided bike tours?", answer: "Absolutely. Send group waiver links to all tour participants before the ride." },
      { question: "What about walk-in customers?", answer: "Kiosk mode with QR codes handles walk-ins perfectly. No app download needed." },
    ],
    ctaHeadline: "Every ride, every rider, protected",
    ctaSubtext: "Digital waivers for bike rental operations of any size.",
    industry: "bike-rental",
  },
  {
    slug: "paddleboard-rental-waivers",
    title: "Paddleboard Rental Waivers",
    metaTitle: "Paddleboard Rental Waivers | SUP Liability Protection",
    metaDescription: "Digital liability waivers for stand-up paddleboard (SUP) rentals. Guests sign before they paddle. Secure, legal, affordable.",
    h1: "Digital Waivers for Paddleboard Rentals",
    subheading: "Protect your SUP rental business on and off the water",
    heroDescription: "Stand-up paddleboarding is booming — and so is the liability. Rental Waivers helps SUP operators collect signed waivers before every session, whether it's a solo rental or a guided group tour.",
    painPoints: [
      { title: "Water-related liability", description: "Drowning risk, weather conditions, and wildlife encounters. Waivers document risk acknowledgment." },
      { title: "Group lessons & tours", description: "Collecting waivers from 10-15 people at the beach is chaos. Do it digitally, in advance." },
      { title: "Seasonal operations", description: "No monthly software fees eating into your margins during the off-season." },
    ],
    features: [
      { title: "Swimming ability acknowledgment", description: "Custom fields to confirm swimming ability and water comfort level.", icon: "droplets" },
      { title: "Group tour links", description: "One link for the whole group. Each participant signs individually.", icon: "users" },
      { title: "Pay-per-use pricing", description: "No monthly fees. Pay only during your season.", icon: "coins" },
    ],
    howItWorks: [
      { step: 1, title: "Create your SUP waiver", description: "Water safety, liability terms, equipment responsibility, and skill acknowledgment." },
      { step: 2, title: "Send to participants", description: "Email links or share QR codes at your launch point." },
      { step: 3, title: "Everyone signs", description: "Individual signatures from every participant in the group." },
      { step: 4, title: "Records secured", description: "Cloud storage with full audit trails for every signed waiver." },
    ],
    faqItems: [
      { question: "Can I ask about swimming ability?", answer: "Yes! Add custom fields asking about swimming proficiency, comfort level, and experience." },
      { question: "What about guided tours?", answer: "Group signing links let every tour participant sign individually before the tour starts." },
      { question: "Do I pay during the off-season?", answer: "No! Pay-per-waiver means zero costs when you're not renting. Perfect for seasonal businesses." },
      { question: "Can I use this at the beach?", answer: "QR codes work anywhere with cell service. Participants sign on their own phones." },
    ],
    ctaHeadline: "Paddle with peace of mind",
    ctaSubtext: "Digital waivers for SUP rentals and tours. No monthly fees.",
    industry: "paddleboard-rental",
  },
  {
    slug: "scooter-rental-waivers",
    title: "Scooter Rental Waivers",
    metaTitle: "Scooter Rental Waivers | Digital Liability Forms for Scooter Shops",
    metaDescription: "Digital liability waivers for scooter and moped rental businesses. Renters sign before they ride. Legally binding, secure, affordable.",
    h1: "Digital Waivers for Scooter Rentals",
    subheading: "Liability protection for scooter and moped rental operators",
    heroDescription: "Scooter and moped rentals are popular in tourist destinations — but they carry real liability. Rental Waivers ensures every rider signs before they ride, with comprehensive risk acknowledgment and license verification.",
    painPoints: [
      { title: "Tourist inexperience", description: "Many scooter renters have never ridden before. Waivers force them to acknowledge the risks." },
      { title: "Traffic accidents", description: "Road incidents are common. Signed waivers are your first defense against liability claims." },
      { title: "License verification", description: "Document that you checked the rider has a valid license before renting." },
    ],
    features: [
      { title: "License verification field", description: "Capture license numbers and require acknowledgment of valid licensure.", icon: "id-card" },
      { title: "Experience level assessment", description: "Ask riders about their experience level before renting.", icon: "gauge" },
      { title: "Multi-language support", description: "Create templates in English and Spanish for international tourist markets.", icon: "globe" },
    ],
    howItWorks: [
      { step: 1, title: "Build your scooter waiver", description: "Liability, traffic rules, helmet requirements, and damage policies." },
      { step: 2, title: "Sign at the counter", description: "QR code kiosk mode for walk-in renters. Email links for reservations." },
      { step: 3, title: "Riders sign in seconds", description: "Mobile-optimized signing with license acknowledgment." },
      { step: 4, title: "Full documentation", description: "Every rental is documented with timestamps and IP logging." },
    ],
    faqItems: [
      { question: "Can I verify the rider has a license?", answer: "Yes. Add a required text field for license number and a checkbox confirming valid licensure." },
      { question: "What about international tourists?", answer: "Our platform supports English and Spanish. Create templates in both languages for your market." },
      { question: "Can I include a vehicle condition report?", answer: "Yes. Custom fields let you document scooter number, condition, fuel level, and pre-existing damage." },
      { question: "How does walk-in signing work?", answer: "Display a QR code. Renters scan with their phone and sign — no app download needed." },
    ],
    ctaHeadline: "Protect every scooter rental",
    ctaSubtext: "Digital waivers that riders sign in under a minute.",
    industry: "scooter-rental",
  },
  {
    slug: "equipment-rental-waivers",
    title: "Equipment Rental Waivers",
    metaTitle: "Equipment Rental Waivers | Digital Liability Forms for Rental Businesses",
    metaDescription: "Digital liability and damage waivers for equipment rental businesses. Power tools, construction equipment, sporting goods — protect your assets.",
    h1: "Digital Waivers for Equipment Rentals",
    subheading: "Protect your equipment and your business with every rental",
    heroDescription: "From power tools to construction equipment, sporting goods to camera gear — equipment rental businesses need signed agreements for every transaction. Rental Waivers digitizes the entire process.",
    painPoints: [
      { title: "Equipment misuse", description: "Without signed acknowledgment of proper use, damage claims are hard to enforce." },
      { title: "Inventory tracking", description: "Link each waiver to specific equipment for clear rental records." },
      { title: "Late returns", description: "Include late fee policies in your waiver so terms are acknowledged upfront." },
    ],
    features: [
      { title: "Equipment-specific templates", description: "Create different waivers for different equipment categories.", icon: "wrench" },
      { title: "Serial number tracking", description: "Custom fields for equipment ID, serial number, and condition notes.", icon: "hash" },
      { title: "Rental terms included", description: "Combine liability waiver with rental agreement terms in one document.", icon: "file-text" },
    ],
    howItWorks: [
      { step: 1, title: "Create templates by category", description: "Different waivers for power tools, heavy equipment, sporting goods, etc." },
      { step: 2, title: "Sign at checkout", description: "QR code at your counter or email links for reservations." },
      { step: 3, title: "Document everything", description: "Equipment ID, condition, and renter signature — all captured." },
      { step: 4, title: "Access records easily", description: "Search by renter, date, or equipment. Download PDFs for disputes." },
    ],
    faqItems: [
      { question: "Can I track specific equipment per waiver?", answer: "Yes. Add custom fields for equipment ID, serial number, model, and condition at checkout." },
      { question: "Can this replace my rental agreement?", answer: "Yes! Include rental terms, pricing, and liability language in one comprehensive digital document." },
      { question: "How do I find a specific waiver later?", answer: "Search by renter name, email, date, or equipment reference in your dashboard." },
      { question: "What's the cost structure?", answer: "Pay-per-waiver starting at 6¢. No monthly fees. Buy credits in bulk for discounts." },
    ],
    ctaHeadline: "Every rental, fully documented",
    ctaSubtext: "Digital waivers and rental agreements for equipment businesses.",
    industry: "equipment-rental",
  },
  {
    slug: "event-rental-waivers",
    title: "Event Rental Waivers",
    metaTitle: "Event Rental Waivers | Digital Liability Protection for Event Companies",
    metaDescription: "Digital liability waivers for event rental companies. Weddings, corporate events, festivals — protect your business. No monthly subscription.",
    h1: "Digital Waivers for Event Rentals",
    subheading: "Every event is a liability event — protect your business",
    heroDescription: "Event rental companies providing stages, lighting, AV equipment, dance floors, and décor need signed agreements for every event. Rental Waivers automates it all.",
    painPoints: [
      { title: "Large event liability", description: "Events with hundreds of guests multiply your liability. Signed agreements from organizers are essential." },
      { title: "Weekend rushes", description: "Multiple events on the same weekend means dozens of waivers. Automation is the only way." },
      { title: "Sub-vendor coordination", description: "When your equipment is part of a larger event, you need your own signed agreements." },
    ],
    features: [
      { title: "Event-specific templates", description: "Weddings, corporate, festivals — create templates for each event type.", icon: "calendar" },
      { title: "Venue & date fields", description: "Capture event date, venue, and setup/teardown details in the waiver.", icon: "map-pin" },
      { title: "Organizer + venue signing", description: "Multiple parties can sign the same waiver — event organizer and venue manager.", icon: "pen-tool" },
    ],
    howItWorks: [
      { step: 1, title: "Build event templates", description: "Create templates for different event types with specific liability terms." },
      { step: 2, title: "Send with proposals", description: "Attach waiver links to event proposals and confirmations." },
      { step: 3, title: "Organizers sign", description: "Event planners and organizers sign acknowledging all terms." },
      { step: 4, title: "Protected at every event", description: "Signed agreements on file for every event you service." },
    ],
    faqItems: [
      { question: "Can multiple people sign the same waiver?", answer: "Yes — use group signing so both the event organizer and venue contact can sign." },
      { question: "Can I include setup and teardown terms?", answer: "Absolutely. Your waiver template can include any terms relevant to your service." },
      { question: "What about wedding season volume?", answer: "Bulk credits at volume discounts. No throttling — send as many as you need." },
      { question: "Do you offer custom branding?", answer: "Coming soon! Organization branding on waivers is on our roadmap." },
    ],
    ctaHeadline: "Every event, every agreement, digital",
    ctaSubtext: "Digital waivers for event rental companies. Set up in minutes.",
    industry: "event-rental",
  },
  {
    slug: "hot-tub-rental-waivers",
    title: "Hot Tub Rental Waivers",
    metaTitle: "Hot Tub Rental Waivers | Digital Liability Protection",
    metaDescription: "Protect your hot tub rental with digital liability waivers. Guests acknowledge health risks and rules before soaking. Starting at 6¢.",
    h1: "Digital Waivers for Hot Tub Rentals",
    subheading: "Health risks, liability, and rules — all acknowledged in writing",
    heroDescription: "Hot tub rentals at vacation properties, spas, and rental businesses carry unique health and safety risks. Rental Waivers ensures guests acknowledge temperature warnings, health conditions, and usage rules before they soak.",
    painPoints: [
      { title: "Health condition liability", description: "Heart conditions, pregnancy, medications — guests need to acknowledge health risks in writing." },
      { title: "Temperature & chemical risks", description: "Burns, allergic reactions, and overexposure are real risks. Document guest acknowledgment." },
      { title: "Vacation property hot tubs", description: "Remote properties can't rely on in-person waiver collection. Go digital." },
    ],
    features: [
      { title: "Health screening questions", description: "Ask about heart conditions, pregnancy, medications, and alcohol use.", icon: "heart-pulse" },
      { title: "Temperature acknowledgment", description: "Document that guests acknowledge safe temperature ranges and time limits.", icon: "thermometer" },
      { title: "Property rules inclusion", description: "Include glass-free zones, guest limits, quiet hours, and cleaning expectations.", icon: "list-checks" },
    ],
    howItWorks: [
      { step: 1, title: "Create your hot tub waiver", description: "Health screening, liability terms, temperature warnings, and property rules." },
      { step: 2, title: "Send before check-in", description: "Automatically send when guests book your property." },
      { step: 3, title: "Guests acknowledge risks", description: "Full legal signing with health condition acknowledgment." },
      { step: 4, title: "Protected documentation", description: "Tamper-proof records of every guest's signed acknowledgment." },
    ],
    faqItems: [
      { question: "Can I ask about health conditions?", answer: "Yes. Add custom fields asking about heart conditions, pregnancy, blood pressure, and medications." },
      { question: "Is this just for vacation rentals?", answer: "No! Hot tub rental businesses, spas, and wellness centers all use our platform." },
      { question: "What if a guest doesn't disclose a condition?", answer: "Your waiver documents that you asked and they had the opportunity to disclose. This strengthens your legal position." },
      { question: "Can I include chemical safety info?", answer: "Yes. Include chlorine/bromine warnings, shower requirements, and any chemical safety information." },
    ],
    ctaHeadline: "Hot tub liability, covered",
    ctaSubtext: "Digital health acknowledgments and liability waivers for hot tub rentals.",
    industry: "hot-tub-rental",
  },
  {
    slug: "surfboard-rental-waivers",
    title: "Surfboard Rental Waivers",
    metaTitle: "Surfboard Rental Waivers | Digital Liability Forms for Surf Shops",
    metaDescription: "Digital liability waivers for surfboard rental shops and surf schools. Riders sign before they paddle out. Mobile-friendly, no subscription.",
    h1: "Digital Waivers for Surfboard Rentals",
    subheading: "Protect your surf shop with digital liability waivers",
    heroDescription: "Surf shops, board rental businesses, and surf schools need signed liability waivers for every customer. Rental Waivers makes it fast, mobile-friendly, and legally binding.",
    painPoints: [
      { title: "Ocean safety liability", description: "Rip currents, rocks, and collisions — surfing has real risks. Document acknowledgment." },
      { title: "Walk-in traffic", description: "Surf shops get walk-ins all day. QR codes handle waiver collection without slowing anyone down." },
      { title: "Board damage", description: "Dinged boards without signed damage agreements cost you money. Get it in writing." },
    ],
    features: [
      { title: "Ocean condition awareness", description: "Custom fields for ocean experience, swimming ability, and condition acknowledgment.", icon: "waves" },
      { title: "Board checkout form", description: "Capture board type, size, and condition at rental.", icon: "clipboard" },
      { title: "Walk-in QR signing", description: "Customers scan, sign, and paddle out in under a minute.", icon: "qr-code" },
    ],
    howItWorks: [
      { step: 1, title: "Create your surf waiver", description: "Ocean safety, liability, board damage policies, and experience level assessment." },
      { step: 2, title: "Display QR at shop", description: "Walk-in customers scan and sign on their phone instantly." },
      { step: 3, title: "Fast mobile signing", description: "Optimized for speed — surfers sign in under 60 seconds." },
      { step: 4, title: "Records always available", description: "Search and access any signed waiver from your dashboard." },
    ],
    faqItems: [
      { question: "Can I include board damage policies?", answer: "Yes. Include damage responsibility terms, repair costs, and condition documentation in your waiver." },
      { question: "What about surf lessons?", answer: "Create separate templates for lessons vs. rentals with appropriate liability language for each." },
      { question: "How does the QR code work?", answer: "Generate a QR code for your template. Print it and display at your counter. Customers scan with their phone camera." },
      { question: "What if someone doesn't have their phone?", answer: "Use a shared tablet at your counter. Multiple customers can sign on the same device." },
    ],
    ctaHeadline: "Shred without the risk",
    ctaSubtext: "Digital waivers for surf shops and board rentals. Set up in minutes.",
    industry: "surfboard-rental",
  },
];

export function getLandingPageBySlug(slug: string): SeoLandingPage | undefined {
  return seoLandingPages.find((p) => p.slug === slug);
}
