export interface StateWaiverLawPage {
  slug: string;
  state: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  overview: string;
  enforceability: "strong" | "moderate" | "challenging";
  enforcementSummary: string;
  keyStatutes: { name: string; description: string }[];
  minorRules: string;
  grossNegligence: string;
  rentalSpecific: string;
  bestPractices: string[];
  faqItems: { question: string; answer: string }[];
  relatedStates: string[];
}

export const stateWaiverLawPages: StateWaiverLawPage[] = [
  {
    slug: "california",
    state: "California",
    metaTitle: "California Waiver Laws — Are Liability Waivers Enforceable in CA?",
    metaDescription: "Learn about California liability waiver laws for rental businesses. Enforceability standards, minor waiver rules, and what your CA waiver must include.",
    h1: "California Liability Waiver Laws for Rental Businesses",
    overview: "California generally enforces liability waivers when they are clear, unambiguous, and do not attempt to waive liability for gross negligence. The state has a well-developed body of case law supporting waivers in recreational contexts, making it one of the more favorable states for waiver enforcement.",
    enforceability: "strong",
    enforcementSummary: "California courts enforce waivers that are clear, conspicuous, and specifically identify the risks. The release language must be unambiguous and cannot be hidden in fine print.",
    keyStatutes: [
      { name: "California Civil Code §1668", description: "Prohibits contracts that exempt parties from responsibility for fraud, willful injury, or violation of law. Waivers of ordinary negligence are generally permitted." },
      { name: "Tunkl v. Regents (1963)", description: "Landmark case establishing that waivers are unenforceable when they involve businesses of public interest with significant bargaining power imbalance." },
      { name: "Knight v. Jewett (1992)", description: "Established the primary assumption of risk doctrine for sports and recreational activities in California." },
    ],
    minorRules: "California is one of the few states where a parent's pre-injury waiver on behalf of a minor may be enforceable, though case law continues to evolve. Include a separate guardian signature section and specific minor-related risk disclosures.",
    grossNegligence: "California does not allow waiving liability for gross negligence. Your waiver can only protect against claims of ordinary negligence — not reckless conduct or willful disregard for safety.",
    rentalSpecific: "California has specific regulations for watercraft rentals, including PWC/jet ski age requirements (16+), boater safety education mandates, and vessel registration requirements. Include compliance language in your waiver.",
    bestPractices: [
      "Use clear, conspicuous language — California courts look for waivers that a reasonable person would notice and understand",
      "Specifically identify the risks of the activity — generic language is insufficient",
      "Include a separate signature line for the release clause (not just a general signature)",
      "Reference California Civil Code §1668 to acknowledge the limits of your waiver",
      "For watercraft rentals, include California Harbors and Navigation Code compliance",
      "Keep the waiver as a standalone document — don't bury it in a rental agreement",
    ],
    faqItems: [
      { question: "Are liability waivers enforceable in California?", answer: "Generally yes. California enforces well-drafted waivers for ordinary negligence in recreational contexts. The waiver must be clear, conspicuous, and specifically identify the risks. Gross negligence cannot be waived." },
      { question: "Can parents sign waivers for minors in California?", answer: "California has some case law supporting parental waivers for minors, though this area of law continues to evolve. Include a separate guardian section and consult a California attorney for current guidance." },
      { question: "What makes a California waiver unenforceable?", answer: "Ambiguous language, buried release clauses, attempts to waive gross negligence, and waivers that involve essential public services. The waiver must be prominent, clear, and voluntary." },
      { question: "Do California rental businesses need waivers?", answer: "While not legally required, waivers are strongly recommended for any business involving recreational activities. They significantly reduce litigation risk and are routinely enforced by California courts." },
    ],
    relatedStates: ["texas", "florida", "colorado"],
  },
  {
    slug: "florida",
    state: "Florida",
    metaTitle: "Florida Waiver Laws — Liability Waiver Enforceability in FL",
    metaDescription: "Florida liability waiver laws for rental businesses. Learn about enforceability, boat/jet ski requirements, and how to draft a valid FL waiver.",
    h1: "Florida Liability Waiver Laws for Rental Businesses",
    overview: "Florida has a strong tradition of enforcing liability waivers, particularly for recreational and sporting activities. The state is home to one of the largest water sports rental markets in the country, making waiver law especially relevant for jet ski, boat, and kayak rental operators.",
    enforceability: "strong",
    enforcementSummary: "Florida courts enforce clear, unambiguous waivers. The release must specifically mention negligence and clearly identify the activity and risks involved.",
    keyStatutes: [
      { name: "Sanislo v. Give Kids the World (2007)", description: "Florida Supreme Court case confirming that pre-injury releases are enforceable when they clearly and unequivocally release negligence claims." },
      { name: "Florida Statute §327.39", description: "Specific regulations for personal watercraft (jet ski) rentals including operator age requirements, mandatory safety instruction, and livery operator responsibilities." },
      { name: "Florida Statute §328.72", description: "Vessel registration and titling requirements applicable to boat rental operations." },
    ],
    minorRules: "Florida law is less clear on parental waivers for minors. While parents can sign on behalf of minors, the enforceability of pre-injury releases for children is not definitively established. Include guardian signatures but don't rely on them as your sole protection.",
    grossNegligence: "Florida does not allow waiving claims for gross negligence or intentional misconduct. Waivers cover ordinary negligence only.",
    rentalSpecific: "Florida has extensive PWC/jet ski rental regulations (F.S. §327.39) requiring mandatory safety instruction, minimum operator age of 18 for rental (14 with completion of boater safety course), and specific livery operator responsibilities. Boat rental operators must comply with vessel safety equipment requirements.",
    bestPractices: [
      "Specifically use the word 'negligence' in your release clause — Florida courts look for this",
      "For jet ski rentals, comply with F.S. §327.39 and include mandatory safety instruction documentation",
      "Include specific water activity risks (drowning, collision, weather) — not generic language",
      "Ensure the waiver is a standalone document or clearly separated section",
      "For boat rentals, include USCG safety equipment compliance language",
      "Add a 'read and understood' checkbox before the signature line",
    ],
    faqItems: [
      { question: "Are waivers enforceable in Florida?", answer: "Yes. Florida has strong waiver enforcement, particularly for recreational activities. The waiver must clearly and specifically release negligence claims and identify the activity and its risks." },
      { question: "What are Florida's jet ski rental waiver requirements?", answer: "Florida Statute §327.39 requires PWC rental operators to provide mandatory safety instruction, verify operator age (18+ for rental, or 14+ with boater safety course), and comply with specific livery operator responsibilities." },
      { question: "Can parents waive a child's rights in Florida?", answer: "The enforceability of parental waivers for minors is not definitively established in Florida. Include guardian signatures but combine with proper insurance coverage for additional protection." },
      { question: "Do I need separate waivers for each water activity?", answer: "We recommend it. Jet ski, boat, and kayak rentals have different risk profiles. Separate templates with activity-specific risk disclosures strengthen your legal position." },
    ],
    relatedStates: ["california", "texas", "colorado"],
  },
  {
    slug: "texas",
    state: "Texas",
    metaTitle: "Texas Waiver Laws — Liability Waiver Enforceability in TX",
    metaDescription: "Texas liability waiver laws for rental businesses. Pro-business enforcement, equine protections, and what your TX waiver must include.",
    h1: "Texas Liability Waiver Laws for Rental Businesses",
    overview: "Texas is widely considered one of the most business-friendly states for waiver enforcement. Courts routinely uphold pre-injury releases for recreational activities, and the state has specific statutory protections for equine and farm/ranch activities that benefit many rental operators.",
    enforceability: "strong",
    enforcementSummary: "Texas courts enforce waivers that meet the 'fair notice' requirement — the release must be conspicuous and clear enough that a reasonable person would be aware they are waiving legal rights.",
    keyStatutes: [
      { name: "Dresser Industries v. Page (1993)", description: "Texas Supreme Court case establishing the enforceability of pre-injury releases when they satisfy the fair notice requirement — conspicuous presentation and clear language." },
      { name: "Texas Civil Practice & Remedies Code §87", description: "Equine Activity Liability Act providing liability protections for equine activity sponsors — relevant for horse and trail riding rental operations." },
      { name: "Texas Civil Practice & Remedies Code §75", description: "Recreational use statute providing limited liability for landowners who allow recreational use of their property." },
    ],
    minorRules: "Texas allows parents to sign pre-injury waivers for minors under specific circumstances. The Texas Supreme Court has upheld parental waivers in the recreational activity context, making Texas one of the more favorable states for this issue.",
    grossNegligence: "Texas does not allow waiving gross negligence or willful/wanton misconduct. Your waiver protects against ordinary negligence claims only.",
    rentalSpecific: "Texas has specific boater education requirements — operators born after September 1, 1993 must complete a boater education course. ATV and off-road vehicle operations may be subject to Texas Parks & Wildlife regulations. Include compliance language for your specific rental type.",
    bestPractices: [
      "Make the release clause conspicuous — bold, larger font, or separate signature line",
      "Use clear, specific language — Texas courts apply the 'fair notice' standard",
      "Include the specific risks of your rental activity",
      "For equine/trail operations, reference the Texas Equine Activity Liability Act",
      "Include a statement that the signer has read and understood the release",
      "For water sports, include Texas Parks & Wildlife boater education requirements",
    ],
    faqItems: [
      { question: "How enforceable are waivers in Texas?", answer: "Very enforceable. Texas is one of the most pro-business states for waiver enforcement. Courts uphold releases that give 'fair notice' — conspicuous, clear language that a reasonable person would notice." },
      { question: "Can parents sign waivers for children in Texas?", answer: "Yes. Texas courts have upheld parental pre-injury waivers for minors in recreational activity contexts. Include a separate guardian signature section with minor-specific risk disclosures." },
      { question: "Does Texas have special protections for horse rentals?", answer: "Yes. The Texas Equine Activity Liability Act (Civil Practice & Remedies Code §87) provides specific liability protections for equine activity sponsors. Reference this statute in your waiver." },
      { question: "What makes a Texas waiver invalid?", answer: "Waivers that attempt to release gross negligence, use hidden or inconspicuous language, or fail to specifically identify the risks being waived. The 'fair notice' standard is the key test." },
    ],
    relatedStates: ["california", "florida", "arizona"],
  },
  {
    slug: "colorado",
    state: "Colorado",
    metaTitle: "Colorado Waiver Laws — Liability Waiver Enforceability in CO",
    metaDescription: "Colorado liability waiver laws for rental businesses. Very waiver-friendly state with ski area protections. Learn what your CO waiver must include.",
    h1: "Colorado Liability Waiver Laws for Rental Businesses",
    overview: "Colorado is one of the most waiver-friendly states in the country. The Colorado Ski Safety Act and a long history of recreational activity case law make it a particularly favorable jurisdiction for outdoor rental businesses. Courts generally enforce well-drafted waivers without extensive scrutiny.",
    enforceability: "strong",
    enforcementSummary: "Colorado courts enforce waivers that clearly express the parties' intent to release claims. The four-factor test from Jones v. Dressel (1981) guides enforceability analysis.",
    keyStatutes: [
      { name: "Jones v. Dressel (1981)", description: "Colorado Supreme Court case establishing the four-factor test for waiver enforceability: existence of duty, nature of injury, informed consent, and public policy compliance." },
      { name: "Colorado Ski Safety Act (C.R.S. §33-44)", description: "Comprehensive statute addressing ski area liability, assumption of risk, and operator duties — directly relevant to ski rental operations." },
      { name: "C.R.S. §13-22-107", description: "Colorado's statute on assumption of risk in recreational activities, supporting waiver enforcement for outdoor activities." },
    ],
    minorRules: "Colorado has been relatively favorable toward parental waivers for minors in recreational contexts, though the law continues to develop. Include a separate guardian section and age-appropriate risk disclosures.",
    grossNegligence: "Colorado does not allow waiving gross negligence or willful and wanton conduct. Waivers are limited to ordinary negligence claims.",
    rentalSpecific: "Colorado's outdoor recreation industry (ski, rafting, ATV, horseback) benefits from strong assumption of risk doctrines. The Ski Safety Act specifically addresses ski area liability. Boating regulations are governed by Colorado Parks & Wildlife.",
    bestPractices: [
      "Use clear, specific language — Colorado courts look for clear intent to release",
      "Include all four Jones v. Dressel factors in your waiver analysis",
      "For ski operations, comply with and reference the Colorado Ski Safety Act",
      "Include altitude-related risk disclosures for high-elevation activities",
      "Add cold water/weather risks for water sport rentals in mountain areas",
      "For ATV/off-road operations, include terrain-specific hazard disclosures",
    ],
    faqItems: [
      { question: "How waiver-friendly is Colorado?", answer: "Very. Colorado is one of the most favorable states for waiver enforcement. Courts routinely uphold well-drafted releases in recreational contexts using the four-factor Jones v. Dressel test." },
      { question: "Does the Ski Safety Act help ski rental businesses?", answer: "Yes. The Colorado Ski Safety Act (C.R.S. §33-44) establishes assumption of risk for ski area participants and defines both skier and operator responsibilities. Reference it in your ski rental waiver." },
      { question: "Are there altitude-related disclosure requirements?", answer: "While not legally mandated, including altitude and weather-related risk disclosures strengthens your waiver — especially for activities like mountain biking, rafting, and ATV riding at elevation." },
      { question: "Can I waive liability for cold water risks?", answer: "Yes, for ordinary negligence. Colorado's mountain lakes and rivers have significant cold water risks. Specifically disclose hypothermia, cold shock, and swift current hazards in your waiver." },
    ],
    relatedStates: ["california", "texas", "arizona"],
  },
  {
    slug: "new-york",
    state: "New York",
    metaTitle: "New York Waiver Laws — Are Liability Waivers Valid in NY?",
    metaDescription: "New York liability waiver laws for rental businesses. Learn about GOL §5-326, recreational facility exceptions, and how to draft a valid NY waiver.",
    h1: "New York Liability Waiver Laws for Rental Businesses",
    overview: "New York presents unique challenges for waiver enforcement due to General Obligations Law §5-326, which voids certain waivers for recreational facilities that receive fees. However, this statute has specific exceptions and limitations that rental businesses can navigate with proper legal guidance.",
    enforceability: "challenging",
    enforcementSummary: "New York's GOL §5-326 creates significant restrictions, but it does not apply to all rental businesses. The scope of the statute and its exceptions are critical to understand.",
    keyStatutes: [
      { name: "General Obligations Law §5-326", description: "Voids agreements that exempt owners/operators of 'pools, gymnasiums, places of amusement or recreation, or similar establishments' from negligence liability when a fee is charged." },
      { name: "Gross v. Sweet (1979)", description: "New York Court of Appeals case establishing that waivers must be clear, specific, and not violate public policy to be enforceable outside GOL §5-326 contexts." },
      { name: "CPLR §1411", description: "New York's comparative negligence statute, which can reduce but not eliminate liability based on the plaintiff's own negligence." },
    ],
    minorRules: "New York does not generally enforce parental pre-injury waivers for minors. Parents cannot waive a child's right to sue for personal injuries. Guardian signatures provide documentation but limited legal protection.",
    grossNegligence: "New York does not allow waiving gross negligence or willful misconduct, consistent with most states.",
    rentalSpecific: "The application of GOL §5-326 to specific rental businesses depends on whether they qualify as 'places of amusement or recreation.' Outdoor rental operations (kayak, bike) at non-fixed locations may fall outside the statute. Consult a New York attorney for your specific operation.",
    bestPractices: [
      "Consult a New York attorney about GOL §5-326 applicability to your specific business",
      "Even if your waiver may face enforceability challenges, it still has value for deterrence and informed consent documentation",
      "Use waivers as part of a broader risk management strategy — not as your sole protection",
      "Include assumption of risk language (distinct from liability release) which may be enforceable even under GOL §5-326",
      "Document safety briefings, equipment inspections, and all risk communication",
      "Carry robust liability insurance as your primary protection in New York",
    ],
    faqItems: [
      { question: "Are waivers valid in New York?", answer: "It depends on your business type. GOL §5-326 voids certain waivers for paid recreational facilities. However, this statute has specific limitations and may not apply to all rental businesses. Consult a New York attorney for your specific situation." },
      { question: "Does GOL §5-326 apply to outdoor rental businesses?", answer: "The application depends on whether your operation qualifies as a 'place of amusement or recreation.' Mobile or non-fixed-location rentals (bike tours, kayak rentals from a trailer) may fall outside the statute." },
      { question: "Should I still use waivers in New York?", answer: "Yes. Even with GOL §5-326 challenges, waivers serve valuable purposes: informed consent documentation, assumption of risk evidence, behavioral deterrence, and insurance compliance." },
      { question: "Can parents sign waivers for kids in New York?", answer: "New York generally does not enforce parental pre-injury waivers for minors. Include guardian signatures for documentation but rely on proper insurance and safety protocols as your primary protection." },
    ],
    relatedStates: ["virginia", "louisiana", "florida"],
  },
  {
    slug: "arizona",
    state: "Arizona",
    metaTitle: "Arizona Waiver Laws — Liability Waiver Enforceability in AZ",
    metaDescription: "Arizona liability waiver laws for rental businesses. Generally enforceable with clear language. Learn what your AZ waiver must include.",
    h1: "Arizona Liability Waiver Laws for Rental Businesses",
    overview: "Arizona generally enforces liability waivers when they are clear, unambiguous, and do not violate public policy. The state's outdoor recreation industry — ATV tours, desert jeep rentals, water sports on Lake Havasu — benefits from reasonable waiver enforcement standards.",
    enforceability: "strong",
    enforcementSummary: "Arizona courts enforce waivers that clearly express the intent to release liability. The language must be conspicuous and unambiguous.",
    keyStatutes: [
      { name: "Phelps v. Firebird Raceway (2005)", description: "Arizona Supreme Court case confirming that pre-injury releases are enforceable when they clearly and specifically express the parties' intent." },
      { name: "A.R.S. §12-553", description: "Arizona's equine liability statute providing protections for equine activity sponsors and professionals." },
    ],
    minorRules: "Arizona's position on parental waivers for minors is evolving. Courts have not definitively ruled on the enforceability of parental pre-injury releases. Include guardian signatures and robust insurance.",
    grossNegligence: "Arizona does not allow waiving claims for gross negligence, willful misconduct, or intentional harm.",
    rentalSpecific: "Arizona's outdoor rental industry (ATV, jeep, jet ski at Lake Havasu and other waterways) benefits from the state's recreation-friendly legal environment. Heat-related risks are a significant concern that should be specifically addressed in waivers.",
    bestPractices: [
      "Include heat and sun exposure risks — Arizona's extreme temperatures create unique hazards",
      "For ATV and off-road operations, include desert terrain hazards (loose sand, cacti, wildlife)",
      "Use clear, unambiguous release language",
      "Reference A.R.S. §12-553 for equine activities",
      "Include hydration requirements and heat safety acknowledgments",
      "For water sports, include monsoon season weather hazards",
    ],
    faqItems: [
      { question: "Are waivers enforceable in Arizona?", answer: "Generally yes. Arizona courts enforce clear, unambiguous pre-injury releases. The key is specific language that identifies the risks and clearly expresses the intent to release liability." },
      { question: "Do I need heat-related disclosures?", answer: "Strongly recommended. Arizona's extreme heat creates significant risks for outdoor activities. Include heat exhaustion, sunburn, and dehydration disclosures in your waiver." },
      { question: "What about ATV desert tour waivers?", answer: "ATV tours in Arizona should include specific desert terrain hazards, wildlife encounters, dust exposure, and temperature extremes. These specific disclosures strengthen enforceability." },
      { question: "Can parents sign waivers for minors in Arizona?", answer: "Arizona law on parental waivers for minors is not definitively settled. Include guardian signatures for documentation but don't rely solely on waivers for minor participant liability protection." },
    ],
    relatedStates: ["colorado", "texas", "california"],
  },
  {
    slug: "virginia",
    state: "Virginia",
    metaTitle: "Virginia Waiver Laws — Are Liability Waivers Enforceable in VA?",
    metaDescription: "Virginia liability waiver laws for rental businesses. More scrutiny than many states. Learn about enforceability standards and drafting requirements.",
    h1: "Virginia Liability Waiver Laws for Rental Businesses",
    overview: "Virginia applies more scrutiny to liability waivers than many states. Courts will enforce waivers, but they must be very precisely drafted with specific language that clearly communicates the release of negligence claims.",
    enforceability: "moderate",
    enforcementSummary: "Virginia enforces waivers but applies strict construction — ambiguities are resolved against the drafter. The language must explicitly reference negligence.",
    keyStatutes: [
      { name: "Hiett v. Lake Barcroft (1992)", description: "Virginia Supreme Court case establishing strict construction standards for liability releases — waivers must explicitly use the word 'negligence.'" },
    ],
    minorRules: "Virginia generally does not enforce parental waivers for minors. Parents cannot contractually waive a child's right to sue. Rely on insurance and safety protocols for minor participants.",
    grossNegligence: "Virginia does not allow waiving gross negligence. Waivers are limited to ordinary negligence claims.",
    rentalSpecific: "Virginia's outdoor recreation industry includes water sports on the Chesapeake Bay and river kayaking. Include specific water hazard disclosures and comply with Virginia Department of Wildlife Resources boating regulations.",
    bestPractices: [
      "Explicitly use the word 'negligence' in your release clause — Virginia courts require this",
      "Draft with extreme precision — Virginia applies strict construction against the drafter",
      "Make the release clause conspicuous and separately signed",
      "Include specific activity risks — generic language will not survive scrutiny",
      "Have a Virginia-licensed attorney review your waiver",
      "Use waivers as part of a comprehensive risk management strategy",
    ],
    faqItems: [
      { question: "Are waivers hard to enforce in Virginia?", answer: "Not impossible, but Virginia applies stricter construction standards than many states. The waiver must explicitly reference 'negligence' and be drafted with precision. Have a Virginia attorney review your waiver." },
      { question: "Does Virginia require the word 'negligence' in waivers?", answer: "Yes. Following Hiett v. Lake Barcroft, Virginia courts require explicit reference to negligence in the release clause. Generic release language without this word may be unenforceable." },
      { question: "Can parents sign waivers for kids in Virginia?", answer: "Virginia generally does not enforce parental pre-injury waivers for minors. Include guardian signatures for documentation but rely on insurance as your primary protection for minor participants." },
      { question: "What makes a Virginia waiver effective?", answer: "Precise language, explicit negligence reference, conspicuous presentation, specific risk identification, and voluntary signature. Have it reviewed by a Virginia attorney familiar with your industry." },
    ],
    relatedStates: ["new-york", "louisiana", "florida"],
  },
  {
    slug: "illinois",
    state: "Illinois",
    metaTitle: "Illinois Waiver Laws — Liability Waiver Enforceability in IL",
    metaDescription: "Illinois liability waiver laws for rental businesses. Generally enforceable with proper drafting. Learn requirements and best practices.",
    h1: "Illinois Liability Waiver Laws for Rental Businesses",
    overview: "Illinois generally enforces liability waivers for recreational activities when they are clear and unambiguous. The state's approach balances freedom of contract with consumer protection, making proper drafting essential.",
    enforceability: "moderate",
    enforcementSummary: "Illinois courts enforce waivers that clearly and specifically release negligence claims. Waivers must not be unconscionable or the result of unequal bargaining power.",
    keyStatutes: [
      { name: "Calarco v. YMCA of Greater Metropolitan Chicago (1993)", description: "Illinois Supreme Court case addressing waiver enforceability in recreational activity contexts." },
      { name: "740 ILCS 22", description: "Illinois Physical Fitness Services Act — relevant for fitness and recreation businesses in Illinois." },
    ],
    minorRules: "Illinois does not enforce parental pre-injury waivers for minors. A parent cannot waive a child's right to sue. Include guardian signatures for documentation purposes only.",
    grossNegligence: "Illinois does not allow waiving gross negligence, willful and wanton conduct, or intentional harm.",
    rentalSpecific: "Illinois' diverse recreational landscape (Lake Michigan water sports, downstate outdoor recreation) means rental businesses should include location-specific hazard disclosures. Chicago-area bike rentals should address urban traffic risks specifically.",
    bestPractices: [
      "Use clear, specific language — ambiguities are resolved against the drafter",
      "Include specific risks associated with the activity",
      "Make the waiver a standalone document or clearly separated section",
      "Include a 'read and understood' acknowledgment",
      "For water sports on Lake Michigan, include specific Great Lakes hazards",
      "Have an Illinois attorney review your waiver for compliance",
    ],
    faqItems: [
      { question: "Are waivers enforceable in Illinois?", answer: "Generally yes, for adult participants. Illinois enforces clear, unambiguous waivers for recreational activities. They must specifically address negligence and not be unconscionable." },
      { question: "Can parents sign waivers for minors in Illinois?", answer: "No. Illinois does not enforce parental pre-injury waivers for minors. Include guardian signatures for documentation but rely on insurance for minor participant protection." },
      { question: "What specific risks should I include?", answer: "Include all risks specific to your activity. For water sports: drowning, cold water, currents. For bike rentals: traffic, falls, equipment failure. Generic language weakens enforceability." },
      { question: "Does Illinois have special recreation business protections?", answer: "Illinois has various recreational use statutes that may apply depending on your business type. Consult an Illinois attorney about protections specific to your rental operation." },
    ],
    relatedStates: ["new-york", "virginia", "florida"],
  },
  {
    slug: "louisiana",
    state: "Louisiana",
    metaTitle: "Louisiana Waiver Laws — Civil Law Waiver Enforceability in LA",
    metaDescription: "Louisiana liability waiver laws — the only civil law state. How Napoleonic Code affects waiver enforceability for rental businesses in LA.",
    h1: "Louisiana Liability Waiver Laws for Rental Businesses",
    overview: "Louisiana is unique in the United States as the only state operating under a civil law system derived from the Napoleonic Code rather than English common law. This fundamentally changes how liability waivers are interpreted and enforced.",
    enforceability: "challenging",
    enforcementSummary: "Louisiana's civil law system treats waivers differently. Courts tend to interpret exculpatory clauses narrowly and may void waivers that are deemed contrary to public policy.",
    keyStatutes: [
      { name: "Louisiana Civil Code Art. 2004", description: "Provides that clauses limiting or excluding liability for intentional or gross fault are void. Ordinary negligence waivers may be enforceable but are narrowly construed." },
      { name: "Louisiana Civil Code Art. 2713", description: "Addresses contractual limitation of liability in lease and rental contexts." },
    ],
    minorRules: "Louisiana does not enforce parental pre-injury waivers for minors. The civil law framework provides strong protections for minor participants that cannot be contractually waived.",
    grossNegligence: "Louisiana Civil Code Art. 2004 explicitly voids clauses that limit liability for intentional or gross fault. Only ordinary negligence may potentially be waived.",
    rentalSpecific: "Louisiana's extensive waterway system (bayous, Gulf Coast, Lake Pontchartrain) creates significant water sport rental opportunities. Include specific hazards for your waterway type — tidal changes, wildlife, and weather patterns unique to Louisiana.",
    bestPractices: [
      "Consult a Louisiana attorney — the civil law system requires specialized knowledge",
      "Don't rely on common law waiver precedents from other states",
      "Use waivers primarily for informed consent documentation and assumption of risk",
      "Carry robust insurance as your primary liability protection",
      "Include specific hazard disclosures (wildlife, weather, water conditions)",
      "Document all safety briefings and equipment instructions",
    ],
    faqItems: [
      { question: "Are waivers valid in Louisiana?", answer: "Louisiana's civil law system treats waivers differently than other states. Exculpatory clauses are narrowly construed and may be limited by Louisiana Civil Code Art. 2004. Consult a Louisiana attorney for guidance specific to your business." },
      { question: "Why is Louisiana different from other states?", answer: "Louisiana is the only US state with a civil law system based on the Napoleonic Code. This means court precedents from other states don't apply, and waiver interpretation follows different principles." },
      { question: "Should I still use waivers in Louisiana?", answer: "Yes. Waivers still serve valuable purposes in Louisiana: informed consent documentation, assumption of risk evidence, and safety awareness. They are part of a comprehensive risk management strategy alongside proper insurance." },
      { question: "What's the best protection for Louisiana rental businesses?", answer: "Robust liability insurance combined with thorough safety protocols, documented training, equipment maintenance records, and well-drafted assumption of risk acknowledgments." },
    ],
    relatedStates: ["new-york", "virginia", "florida"],
  },
  {
    slug: "montana",
    state: "Montana",
    metaTitle: "Montana Waiver Laws — Liability Waiver Enforceability in MT",
    metaDescription: "Montana liability waiver laws for rental businesses. Courts have narrowed enforceability in some contexts. Learn what your MT waiver needs.",
    h1: "Montana Liability Waiver Laws for Rental Businesses",
    overview: "Montana's approach to waiver enforcement has been more restrictive than many western states. Courts have narrowed waiver enforceability in some recreational contexts, making careful drafting and comprehensive risk management essential.",
    enforceability: "moderate",
    enforcementSummary: "Montana courts have been willing to enforce waivers but apply meaningful scrutiny. The waiver must be clear, voluntary, and not against public policy.",
    keyStatutes: [
      { name: "Bjelland v. Poole (2014)", description: "Montana case addressing the enforceability of pre-injury releases in recreational activity contexts." },
      { name: "MCA §27-1-701", description: "Montana's assumption of risk statute, which may provide protections for some recreational activity providers." },
    ],
    minorRules: "Montana's position on parental waivers for minors is restrictive. Courts have been skeptical of parental pre-injury releases. Rely on insurance and safety protocols for minor participants.",
    grossNegligence: "Montana does not allow waiving gross negligence or willful misconduct.",
    rentalSpecific: "Montana's outdoor recreation industry (river rafting, horseback riding, ATV tours, ski rentals) is significant. Include specific hazards related to Montana's terrain, wildlife (bears, moose), and rapidly changing mountain weather.",
    bestPractices: [
      "Have a Montana-licensed attorney review your waiver — Montana courts apply meaningful scrutiny",
      "Include specific, detailed risk disclosures for your activity type",
      "Use waivers as part of a comprehensive risk management strategy",
      "Document all safety briefings and equipment orientation sessions",
      "Include wildlife and weather-specific hazard disclosures",
      "Carry robust insurance as your primary protection",
    ],
    faqItems: [
      { question: "Are waivers enforceable in Montana?", answer: "Montana courts will enforce waivers but apply more scrutiny than some neighboring states. Careful drafting with specific risk disclosures and a Montana attorney review is essential." },
      { question: "What outdoor activity risks should I disclose?", answer: "Include wildlife encounters (bears, moose, snakes), rapidly changing weather, altitude effects, cold water hazards, and terrain-specific dangers. Montana's environment creates unique risks that must be specifically addressed." },
      { question: "Can parents sign waivers for minors in Montana?", answer: "Montana courts have been skeptical of parental pre-injury releases. Include guardian signatures but rely primarily on insurance and safety protocols for minor participant protection." },
      { question: "What's the best approach for Montana rental businesses?", answer: "Combine a well-drafted waiver with comprehensive insurance, documented safety protocols, thorough staff training, and equipment maintenance records. Don't rely on waivers alone." },
    ],
    relatedStates: ["colorado", "virginia", "new-york"],
  },
];

export function getStateLawPage(slug: string): StateWaiverLawPage | undefined {
  return stateWaiverLawPages.find((p) => p.slug === slug);
}
