import type { WaiverTemplatePage } from "./waiver-template-pages";

const templates: { slug: string; name: string; activity: string; risks: string[]; uniqueClause: { title: string; text: string }; fields: string[]; bestPractices: string[] }[] = [
  {
    slug: "snowmobile-rental-waiver-template",
    name: "Snowmobile Rental Waiver",
    activity: "snowmobile",
    risks: ["High-speed collision with terrain, trees, or other riders", "Rollover and ejection from machine", "Avalanche burial in backcountry terrain", "Frostbite and hypothermia from extended exposure", "Mechanical failure on remote trails", "Carbon monoxide exposure when machine is enclosed"],
    uniqueClause: { title: "Avalanche & Backcountry Acknowledgment", text: "Participant acknowledges that snowmobiling on or near avalanche terrain involves the risk of avalanche burial and death. Participant confirms they have received avalanche safety information, will carry required safety equipment (beacon, probe, shovel) when riding off marked trails, and accept full responsibility for their decision to enter avalanche terrain." },
    fields: ["Full legal name", "Date of birth", "Driver's license number and state", "Snowmobile experience level (years)", "Helmet size", "Avalanche training certification (if backcountry)", "Emergency contact", "Trail or area selected"],
    bestPractices: ["Require helmet and goggle wear as a checkbox, not paragraph text", "Include a zero-alcohol policy with explicit acknowledgment", "Add fuel-return and machine-damage deposit policy in plain language", "Disclose specific local trail hazards (groomed vs ungroomed, road crossings)", "For backcountry/off-trail rentals, require avalanche education proof", "Include a separate guardian section for minors with state-law disclosure"],
  },
  {
    slug: "paintball-waiver-template",
    name: "Paintball Waiver",
    activity: "paintball",
    risks: ["Eye injury (including permanent blindness) if mask is removed in active zone", "Welts, bruising, and minor lacerations from impact", "Falls and ankle injury on uneven terrain", "Marker (gun) malfunction", "Heat exhaustion and dehydration", "Allergic reaction to paintball fill"],
    uniqueClause: { title: "Eye Protection / Mask-On Policy", text: "Participant acknowledges that PERMANENT EYE INJURY OR BLINDNESS will result from removing approved eye protection in any active playing area, staging area, or chronograph zone. Participant agrees to keep ASTM-rated paintball mask securely in place at all times when in any area where paintballs may be discharged, and accepts full responsibility for any injury resulting from removal of eye protection." },
    fields: ["Full legal name", "Date of birth", "Mask size", "Paintball experience level", "Marker (own or rented)", "Field/session selected", "Emergency contact", "Photo/video consent (separate)"],
    bestPractices: ["Make the mask-on clause physically prominent — bold, larger font, separate signature line if possible", "Require a separate guardian signature for any participant under 18", "Include chronograph compliance language (max 280 fps)", "Add a zero-alcohol/zero-drug policy with acknowledgment", "Specify behavior rules (no point-blank shots, no overshooting) and consequences", "List specific staff authority to eject players for safety violations"],
  },
  {
    slug: "escape-room-waiver-template",
    name: "Escape Room Waiver",
    activity: "escape room",
    risks: ["Claustrophobia or panic attack inside enclosed rooms", "Minor abrasions from props or set pieces", "Allergic reaction to theatrical fog, scents, or props", "Trip-and-fall on themed flooring or low light", "Photosensitive seizure from strobe or flashing effects", "Emotional distress from horror or thriller themes"],
    uniqueClause: { title: "Claustrophobia & Sensory Disclosure", text: "Participant acknowledges that escape rooms involve enclosed spaces, low lighting, themed sound effects, and may include theatrical fog, strobing lights, or simulated scares. Participant confirms they do not have any medical condition that would be aggravated by these conditions, including but not limited to claustrophobia, photosensitive epilepsy, severe anxiety disorder, or PTSD that could be triggered by the room theme." },
    fields: ["Full legal name", "Date of birth", "Room or game selected", "Booking/group ID", "Photo and social media consent", "Acknowledgment of no recording / no phones", "Emergency contact", "Any medical conditions or accessibility needs"],
    bestPractices: ["Disclose specific themes (horror, thriller, family) and any strobe/fog effects up front", "Include a no-recording, no-phone clause to protect game integrity (and IP)", "Add a property-damage clause for set pieces and props", "Always include a clear emergency exit acknowledgment — every player must know how to leave", "For minors, require guardian presence in the room or explicit guardian sign-off", "Include intoxication-prohibition language with right to refuse service"],
  },
  {
    slug: "trampoline-park-waiver-template",
    name: "Trampoline Park Waiver",
    activity: "trampoline park",
    risks: ["Fractures, including catastrophic spinal injury", "Ankle and knee sprains and tears", "Head and neck injury from awkward landing", "Double-bounce collision injury (the leading cause of serious injury)", "Concussion and traumatic brain injury", "Burns and abrasions from trampoline springs and pads"],
    uniqueClause: { title: "One-Jumper-Per-Trampoline / Double-Bounce Acknowledgment", text: "Participant acknowledges that the leading cause of catastrophic injury at trampoline parks is the 'double bounce' — when two or more jumpers share a single trampoline. Participant agrees to use only one trampoline at a time, never to jump on the same trampoline as another person, and to follow all posted rules and staff instructions. Participant understands that violation of this rule may result in immediate ejection without refund." },
    fields: ["Full legal name", "Date of birth", "Guardian name and signature (mandatory if under 18)", "Jump sock size and acknowledgment", "Court/zone assigned", "Emergency contact", "Acknowledgment of concussion symptom information", "Photo/marketing consent"],
    bestPractices: ["The double-bounce clause is the single most important — make it physically prominent and require an initial", "Require jump-sock purchase/usage with separate acknowledgment", "Disclose specific high-risk attractions (foam pit, dodgeball, dunk lane) individually", "Provide concussion-symptom information and require an acknowledgment", "Enforce age-zone separation in the waiver text (e.g., toddler court restrictions)", "Guardian waivers are unenforceable in some states — operate accordingly even with signed waivers"],
  },
  {
    slug: "axe-throwing-waiver-template",
    name: "Axe Throwing Waiver",
    activity: "axe throwing",
    risks: ["Lacerations from axe blades during handling or pickup", "Ricochet impact from axe bouncing off target", "Shoulder, elbow, and back strain from throwing motion", "Bystander injury from stray throws", "Foot injury from dropped or rebounding axe", "Splinter and minor wounds from target wood"],
    uniqueClause: { title: "Sober Throwing & Coach Authority", text: "Participant acknowledges that axe throwing requires full physical and mental control. Participant agrees that they will not throw, handle, or approach the throwing lane while under the influence of alcohol, cannabis, or any impairing substance, and accepts that staff have absolute authority to refuse service or eject any participant whose behavior or condition presents a safety risk, with no obligation to refund." },
    fields: ["Full legal name", "Date of birth (must be of legal drinking age if alcohol is served on-site)", "Footwear acknowledgment (closed-toe required)", "Lane number / session", "Group or party ID", "Coaching session acknowledgment", "Emergency contact", "Photo/marketing consent"],
    bestPractices: ["Require closed-toe footwear as a separate checkbox — flip-flops are a top injury cause", "If alcohol is served on-site, set a strict throw-cutoff (typically 2 drinks) and put it in writing", "Require coach instruction completion before throws — record it in the waiver", "Define lane-discipline rules: who throws, who watches, who retrieves, and when", "Disclose specific axe types in use (hatchet vs big axe) and any rotation challenges", "Set a minimum age (typically 12+) and require guardian presence/signature for minors"],
  },
  {
    slug: "surfboard-rental-waiver-template",
    name: "Surfboard Rental Waiver",
    activity: "surfboard rental and surfing",
    risks: ["Drowning, near-drowning, and water inhalation", "Board-strike laceration to head, face, or body (own board or others')", "Marine wildlife encounter (sharks, jellyfish, stingrays)", "Reef and rock contact lacerations", "Sun, heat, and dehydration injury", "Surfboard fin injury"],
    uniqueClause: { title: "Swimming Ability & Local Conditions Acknowledgment", text: "Participant confirms they are a competent ocean swimmer capable of swimming at least 50 yards in open water without assistance. Participant acknowledges they have been informed of current local surf conditions, hazards (including reef, rip currents, marine life, and crowd density), and agrees to surf only within their ability level. Participant agrees to wear the provided board leash at all times while in the water." },
    fields: ["Full legal name", "Date of birth", "Swimming ability (must be at least 'competent in open water')", "Surfing experience level (years and skill)", "Board type and length assigned", "Local break / beach selected", "Emergency contact", "Acknowledgment of current conditions briefing"],
    bestPractices: ["Require swimming-ability acknowledgment — never rent to non-swimmers", "Require leash usage as a separate checkbox (loose boards injure others)", "Disclose specific local hazards (named reef, rip current zones, shark activity)", "Include a board-damage policy and deposit terms in plain language", "For lessons, add an instructor-authority and group-rules clause", "Add a sun/heat warning and recommend reef-safe sunscreen"],
  },
  {
    slug: "segway-tour-waiver-template",
    name: "Segway / Personal Transporter Tour Waiver",
    activity: "Segway and personal transporter",
    risks: ["Fall from device, including head injury", "Collision with pedestrians or fixed objects", "Traffic injury when crossing or sharing roads", "Mechanical or electrical malfunction", "Battery fire or thermal event (rare)", "Tip-over on uneven surfaces"],
    uniqueClause: { title: "Weight, Balance, and Sobriety Requirements", text: "Participant confirms they meet manufacturer weight requirements (typically 100–260 lbs), are physically capable of standing and balancing for the duration of the tour, are not pregnant, and are not under the influence of alcohol or impairing substances. Participant acknowledges they have completed the mandatory pre-tour training and agrees to follow guide instructions at all times." },
    fields: ["Full legal name", "Date of birth (16+ minimum on most platforms)", "Weight (for safe-operation verification)", "Helmet size and acknowledgment", "Tour route/group", "Pregnancy and medical condition disclosure", "Driver's license (if route includes road sharing)", "Emergency contact"],
    bestPractices: ["Enforce manufacturer weight limits — record participant attestation in waiver", "Mandatory helmet wear for the duration of the tour, with a separate checkbox", "Require completion of the on-site training session as a documented step", "Specifically disclose if the route shares roads with vehicles", "Include a no-phone, no-headphone rule while operating", "Set a clear age minimum and require guardian signature for borderline ages"],
  },
  {
    slug: "drone-rental-waiver-template",
    name: "Drone Rental Waiver",
    activity: "drone rental and operation",
    risks: ["Property damage from collision or crash", "Injury to bystanders from rotor blades or falling drone", "Loss of drone (fly-away, crash beyond recovery)", "Federal Aviation Administration (FAA) violations and fines assigned to the operator", "Privacy violation claims from third parties", "Battery fire during charging or flight"],
    uniqueClause: { title: "FAA Operator Responsibility", text: "Participant acknowledges they are the legal Pilot in Command (PIC) under FAA regulations during the rental period. Participant agrees to comply with all applicable FAA rules including 14 CFR Part 107 (commercial) or recreational flyer requirements (TRUST), to register the drone if required, to respect all temporary flight restrictions and no-fly zones, and accepts full personal responsibility for any FAA violation, civil penalty, or third-party claim resulting from operation." },
    fields: ["Full legal name", "Date of birth (16+ for Part 107)", "FAA Part 107 certificate number (if commercial use)", "TRUST completion confirmation (if recreational)", "Drone model and serial assigned", "Intended flight area", "Insurance acknowledgment (operator vs business)", "Emergency contact"],
    bestPractices: ["Require FAA TRUST or Part 107 confirmation before handover — record it in the waiver", "Include a clear damage and loss policy with deposit/credit-card-hold terms", "Disclose battery handling and charging rules — battery fires are a real liability", "Add a privacy-and-trespass clause: operator is responsible for where they fly", "Specifically prohibit flight in known TFRs, near airports, over crowds, and at night without waiver", "Include an indemnification clause covering FAA fines and third-party property damage"],
  },
  {
    slug: "climbing-gym-waiver-template",
    name: "Climbing Gym Waiver",
    activity: "indoor climbing and bouldering",
    risks: ["Falls from height, including ground falls in bouldering", "Belay error resulting in uncontrolled fall", "Finger, tendon, and pulley injury from sustained loading", "Head impact from falling climbers, holds, or equipment", "Rope burn and harness-related injury", "Collision with other climbers or floor padding edges"],
    uniqueClause: { title: "Belay & Self-Sufficiency Acknowledgment", text: "Participant acknowledges that lead climbing, top-rope belaying, and unsupervised bouldering are inherently dangerous and that climber error, belayer error, or equipment failure can result in serious injury or death. Participant confirms they will not climb on rope without first passing the gym's belay competency test, will not lead climb without lead certification, and accept full responsibility for verifying their partner's belay skill before climbing." },
    fields: ["Full legal name", "Date of birth", "Guardian signature (mandatory under 18)", "Climbing experience (years, gym, outdoor)", "Belay certification status (none / top-rope / lead)", "Acknowledgment of gym orientation video", "Emergency contact", "Day pass / membership type"],
    bestPractices: ["Require a belay test for any climber going on rope — never accept a self-attestation alone", "Separate sections for boulder-only vs rope climbing access", "Require completion of an orientation video or in-person briefing — document it", "Include a child-supervision policy: ratio of guardians to minors, age cutoffs", "Disclose route-setting risk (holds can spin or break) explicitly", "Include a mat-edge and fall-zone clause for bouldering"],
  },
  {
    slug: "go-kart-rental-waiver-template",
    name: "Go-Kart Track Waiver",
    activity: "go-kart and karting",
    risks: ["Collision with other karts, walls, or barriers", "Whiplash and spinal injury from impact", "Rollover and ejection (rare on most modern karts)", "Burn injury from hot engine or exhaust components", "Hair, clothing, or scarf entanglement in moving parts", "Heat exhaustion in enclosed indoor tracks"],
    uniqueClause: { title: "Bumping & Track Discipline", text: "Participant acknowledges that intentional bumping, blocking, or rough driving creates serious injury risk and is strictly prohibited. Participant agrees to obey all flag signals from track marshals, accepts that any violation may result in immediate session termination without refund, and understands that aggressive driving substantially increases the risk of personal and bystander injury." },
    fields: ["Full legal name", "Date of birth (with track minimum age verification)", "Height (for kart-fit and minimum height)", "Helmet, hairnet, and balaclava acknowledgment", "Hair length / restraint method", "Loose clothing/jewelry removal acknowledgment", "Session and kart number", "Emergency contact"],
    bestPractices: ["Enforce minimum height as a hard requirement — measured at the track, not self-reported", "Require hair restraint (hairnet, ponytail through helmet) — entanglement is a real injury source", "Mandatory pre-race safety briefing with documented acknowledgment", "Disclose flag system and consequences of ignoring marshals", "Include a no-impairment policy (alcohol on-site if applicable, complete prohibition before driving)", "Separate kid-kart sessions and waivers from adult-kart sessions"],
  },
  {
    slug: "zipline-tour-waiver-template",
    name: "Zipline Tour Waiver",
    activity: "zipline and aerial adventure",
    risks: ["Fall from height during transition between platforms", "Harness failure or improper fit", "Brake-system malfunction at line termination", "Tree, platform, or structure impact", "Insect, wildlife, and weather exposure", "Cardiac event from height-induced stress"],
    uniqueClause: { title: "Weight, Harness, and Guide Compliance", text: "Participant acknowledges that zipline and aerial adventure activities require strict adherence to weight limits, proper harness fit, and guide instructions at all times. Participant confirms their weight is within the operator's published range (typically 70–250 lbs), agrees to wear the provided harness exactly as fitted by staff, and accepts that failure to follow guide instructions during a tour may result in serious injury or death." },
    fields: ["Full legal name", "Date of birth", "Guardian signature (if under 18)", "Weight (verified at check-in)", "Height (for harness fit)", "Footwear acknowledgment (closed-toe, secured)", "Pregnancy and cardiac/back condition disclosure", "Emergency contact"],
    bestPractices: ["Verify weight at check-in — do not rely on self-report alone for a load-rated activity", "Require closed, secured footwear as a separate checkbox", "Disclose specific medical contraindications (pregnancy, recent surgery, heart condition)", "Include a weather-cancellation and lightning-policy clause", "Mandatory ground-school / first-platform briefing with documented acknowledgment", "Set firm minimum-age and weight-minimum cutoffs (typically 7+ and 70 lbs)"],
  },
  {
    slug: "fitness-class-waiver-template",
    name: "Fitness Class & Personal Training Waiver",
    activity: "group fitness, yoga, and personal training",
    risks: ["Muscle strain, sprain, and tear", "Joint injury, especially knee, shoulder, and back", "Cardiac event during high-intensity exercise", "Equipment misuse injury (free weights, machines, kettlebells)", "Heat illness in hot yoga or HIIT classes", "Pregnancy-related complications in unmodified classes"],
    uniqueClause: { title: "PAR-Q Health Screening & Modification Compliance", text: "Participant confirms they have completed the Physical Activity Readiness Questionnaire (PAR-Q), have disclosed all relevant medical conditions, are physically capable of safe participation, and have either obtained physician clearance where indicated or accept full personal responsibility for proceeding without it. Participant agrees to follow all instructor cues regarding form, intensity, and modifications, and to immediately stop and notify the instructor of any pain, dizziness, or distress." },
    fields: ["Full legal name", "Date of birth", "PAR-Q checklist (cardiac, blood pressure, dizziness, joint, medication, other)", "Pregnancy disclosure", "Class or program enrolled", "Membership type and recurring-billing acknowledgment", "Emergency contact", "Photo/marketing consent (separate)"],
    bestPractices: ["Use a real PAR-Q (not a checkbox) — flag any 'yes' answer for follow-up", "Pregnancy disclosure is critical — many classes require modification or exclusion", "For recurring memberships, include a clear cancellation-policy clause and authorization for recurring charges", "Disclose specific class formats with elevated risk (hot yoga, HIIT, Olympic lifting)", "Require an annual waiver renewal — health status changes", "Include an injury-reporting clause requiring immediate notification of any incident"],
  },
];

export const extraTemplatePages: WaiverTemplatePage[] = templates.map((t) => ({
  slug: t.slug,
  name: t.name,
  metaTitle: `Free ${t.name} Template — Download or Sign Digitally`,
  metaDescription: `Free, attorney-reviewed ${t.name.toLowerCase()} template. Includes assumption of risk, release of liability, and ${t.activity}-specific safety clauses. Customize and go digital.`,
  h1: `${t.name} Template`,
  intro: `This ${t.name.toLowerCase()} template is built for ${t.activity} operators who need real legal protection — not a generic release that won't hold up. It covers the inherent risks of ${t.activity}, the assumption-of-risk and release-of-liability language courts expect to see, and ${t.activity}-specific safety clauses that demonstrate informed consent. Use it as a starting point, customize it for your venue, and have a licensed attorney in your state finalize it.`,
  risks: t.risks,
  clauses: [
    { title: "Assumption of Risk", text: `Participant acknowledges that ${t.activity} involves inherent and unavoidable risks of personal injury, property damage, and in some cases death. Participant has been informed of these risks, understands them, and voluntarily chooses to participate with full knowledge.` },
    { title: "Release of Liability", text: `In consideration of being permitted to participate, Participant releases, waives, and discharges [Business Name], its owners, officers, employees, agents, and affiliates from any and all liability, claims, demands, actions, and causes of action arising out of or related to any loss, damage, or injury sustained while participating in ${t.activity} activities, except in cases of gross negligence or willful misconduct.` },
    { title: "Indemnification", text: `Participant agrees to defend, indemnify, and hold harmless [Business Name] from any third-party claims, judgments, costs, and reasonable attorneys' fees arising out of Participant's use of equipment, participation in ${t.activity} activities, or violation of these terms.` },
    t.uniqueClause,
    { title: "Equipment Inspection & Responsibility", text: "Participant acknowledges receipt of equipment in good working condition, agrees to inspect it before use, to report any defects immediately, and to be financially responsible for damage or loss beyond normal wear and tear." },
    { title: "Medical Authorization", text: "In the event of an emergency, Participant authorizes [Business Name] to secure emergency medical treatment and transportation. Participant understands that all costs incurred are the sole responsibility of the Participant." },
    { title: "Severability & Governing Law", text: "If any provision of this agreement is found unenforceable, the remaining provisions remain in full effect. This agreement is governed by the laws of the state where the activity takes place, and any dispute will be brought in the courts of that state." },
  ],
  customFields: t.fields,
  bestPractices: t.bestPractices,
  faqItems: [
    { question: `Is this ${t.name.toLowerCase()} template free?`, answer: `Yes — download and customize it for free. You can use it as a paper waiver, or run it digitally through RentalWaivers starting at 6¢ per signed waiver.` },
    { question: "Will this hold up in court?", answer: `Waiver enforceability depends on (1) clear and conspicuous language, (2) specific risk disclosure, (3) signature evidence, and (4) state law. This template covers items 1–3. State enforceability varies — Virginia and Louisiana broadly disfavor pre-injury releases; most other states enforce well-drafted waivers between adults. Always have a licensed in-state attorney finalize it.` },
    { question: "What about minors?", answer: `Minor waiver enforceability varies dramatically by state. Connecticut, New Jersey, Utah, and Washington (among others) restrict or void parental pre-injury releases for minors. Always collect a guardian signature anyway — it documents informed consent even where it doesn't fully release liability.` },
    { question: "Can I edit the clauses?", answer: "Absolutely — this is a starting template. Add venue-specific hazards, your insurance carrier's required language, and any state-mandated disclosures. Just don't remove the assumption-of-risk and release-of-liability core." },
    { question: "Do I need to update it every year?", answer: "Yes. Best practice is an annual legal review — case law shifts, state statutes change, and your operations evolve. RentalWaivers makes versioning and re-signature easy." },
  ],
  relatedIndustry: t.slug.replace("-waiver-template", "-waivers"),
  relatedTemplates: ["kayak-rental-waiver-template", "atv-rental-waiver-template", "bounce-house-rental-waiver-template"],
}));

export const extraTemplateSlugs = templates.map((t) => t.slug);
