import type { WaiverTemplatePage } from "./waiver-template-pages";

// Property & general rental waiver template pages.
// Merged into allWaiverTemplatePages in waiver-template-pages.ts.
export const rentalTemplatePages: WaiverTemplatePage[] = [
  {
    slug: "vacation-rental-waiver-template",
    name: "Vacation Rental Waiver",
    metaTitle: "Free Vacation Rental Waiver Template — Protect Your Property",
    metaDescription: "Free vacation rental liability waiver template for hosts. Covers guest injury, pool and hot tub use, property damage, and amenity risks. Sign digitally in minutes.",
    h1: "Vacation Rental Waiver Template",
    intro: "This vacation rental waiver template is built for hosts and property managers who rent homes, condos, and cabins to short-term guests. It covers guest injuries on the property, amenity use (pools, hot tubs, grills, docks), property damage, and occupancy rules — the exposures a standard lease or platform agreement doesn't fully protect you from.",
    risks: ["Slip and fall injuries on decks, stairs, and wet surfaces", "Drowning or injury in pools, hot tubs, or nearby water", "Burns from grills, fire pits, and fireplaces", "Property damage caused by guests or their visitors", "Injury to unsupervised children on the property", "Theft, vandalism, or unauthorized parties"],
    clauses: [
      { title: "Assumption of Risk", text: "Guest acknowledges that use of the rental property and its amenities involves inherent risks including slips, falls, burns, and water-related injury. Guest voluntarily assumes all risks associated with occupancy and use of the property during the rental period." },
      { title: "Release of Liability", text: "Guest releases and discharges [Property Owner/Manager Name], its owners, employees, and agents from any and all claims, demands, or causes of action arising out of injury, loss, or damage sustained during the rental period, except in cases of gross negligence or willful misconduct." },
      { title: "Amenity Use Acknowledgment", text: "Guest agrees to follow all posted rules for pools, hot tubs, grills, fire pits, docks, and recreational equipment. Guest acknowledges that children must be supervised at all times and that no lifeguard is provided." },
      { title: "Property Damage Responsibility", text: "Guest agrees to leave the property in the condition received and accepts financial responsibility for damage, excessive cleaning, or loss caused by Guest or Guest's visitors beyond normal wear and tear." },
      { title: "Occupancy and Conduct", text: "Guest agrees to comply with the maximum occupancy limit, quiet hours, parking rules, and local ordinances. Unauthorized parties, events, or subletting are prohibited and constitute grounds for immediate termination." },
      { title: "Indemnification", text: "Guest agrees to indemnify, defend, and hold harmless [Property Owner/Manager Name] from any claims brought by third parties, including Guest's visitors, arising from Guest's occupancy or use of the property." },
    ],
    customFields: ["Full legal name of primary guest", "Number of adults and children in party", "Rental dates (check-in / check-out)", "Property address or listing name", "Names of minors staying on the property", "Emergency contact name and phone number", "Vehicle information for parking", "Pet information if applicable"],
    bestPractices: [
      "Send the waiver automatically when a booking is confirmed — not at check-in when guests are distracted",
      "Reference your specific amenities by name (pool, hot tub, dock) rather than generic 'premises' language",
      "Include a separate checkbox acknowledging pool and hot tub rules — courts treat it as stronger evidence of informed consent",
      "Add your house rules as an exhibit so guests can't claim they never saw them",
      "Collect a waiver from the booking guest covering all members of their party, with minors listed by name",
      "Pair the waiver with a security deposit policy and reference both in your rental agreement",
    ],
    faqItems: [
      { question: "Is this vacation rental waiver template free?", answer: "Yes. Download it for free and customize it for your property. You can use it on paper or collect digital signatures with RentalWaivers starting at 6¢ per waiver." },
      { question: "Does Airbnb or VRBO's coverage replace a waiver?", answer: "No. Platform protection programs are limited, can deny claims, and don't stop a guest from suing you. A signed waiver is your own direct legal protection." },
      { question: "Should every guest sign, or just the person who booked?", answer: "At minimum, the booking guest signs and accepts responsibility for their party. For higher-risk amenities like pools, having each adult sign provides stronger protection." },
      { question: "Can I use this for long-term tenants?", answer: "This template is designed for short-term stays. Long-term residential tenancies are governed by landlord-tenant law — use a lease agreement reviewed by a local attorney instead." },
      { question: "Is a waiver enforceable for vacation rentals?", answer: "Generally yes for ordinary negligence in most states, but enforceability varies. Have an attorney licensed in your property's state review your final version." },
    ],
    relatedIndustry: "vacation-rental-waiver-software",
    relatedTemplates: ["house-rental-waiver-template", "airbnb-vrbo-waiver-template", "pool-rental-waiver-template"],
  },
  {
    slug: "house-rental-waiver-template",
    name: "House Rental Waiver",
    metaTitle: "Free House Rental Waiver Template — Liability Release for Home Rentals",
    metaDescription: "Free house rental waiver template for homeowners renting their property for stays or events. Covers guest injury, property damage, and amenity use. Go digital in minutes.",
    h1: "House Rental Waiver Template",
    intro: "This house rental waiver template protects homeowners who rent out a house — whether for weekend stays, photo shoots, or private events. It releases you from guest injury claims, makes renters responsible for damage, and sets clear rules for occupancy and amenity use.",
    risks: ["Guest or visitor injuries on stairs, decks, or in yards", "Damage to furniture, appliances, and finishes", "Injuries involving pools, hot tubs, trampolines, or play equipment", "Fire or burn incidents from kitchens, grills, or fireplaces", "Unauthorized parties exceeding occupancy limits", "Neighbor complaints and ordinance violations"],
    clauses: [
      { title: "Assumption of Risk", text: "Renter acknowledges that occupying a residential property involves inherent risks including slips, falls, burns, and equipment-related injury. Renter voluntarily assumes all risks for themselves and their guests during the rental period." },
      { title: "Release of Liability", text: "Renter releases and discharges [Homeowner Name] from any and all claims for injury, illness, loss, or damage arising from occupancy or use of the property, except in cases of gross negligence or willful misconduct." },
      { title: "Property Care and Damage", text: "Renter agrees to treat the property with care, report any damage or malfunction immediately, and accept financial responsibility for damage beyond normal wear and tear caused by Renter or Renter's guests." },
      { title: "Occupancy Limits and Rules", text: "Renter agrees to comply with the stated maximum occupancy, noise restrictions, parking rules, and all posted house rules. Parties and events require prior written approval." },
      { title: "Amenity and Equipment Use", text: "Renter agrees to use all appliances, recreational equipment, and amenities according to instructions and to supervise children at all times on the property." },
      { title: "Indemnification", text: "Renter agrees to indemnify and hold harmless [Homeowner Name] from claims brought by Renter's guests, visitors, or contractors arising from the rental." },
    ],
    customFields: ["Full legal name of renter", "Purpose of rental (stay, event, production)", "Rental dates and times", "Total number of guests", "Names of minors on the property", "Emergency contact", "Security deposit amount", "Special requests or approved uses"],
    bestPractices: [
      "Walk the property with the renter at check-in and document condition with photos",
      "Attach house rules as a signed exhibit so they are part of the agreement",
      "State the security deposit amount and deduction policy directly in the waiver",
      "For event rentals, require the renter to name all vendors and confirm insurance",
      "Include a clause prohibiting use of areas you want off-limits (garage, attic, owner closets)",
      "Keep signed waivers for at least the statute of limitations for injury claims in your state — usually 2–4 years",
    ],
    faqItems: [
      { question: "Is this house rental waiver template free?", answer: "Yes. Download it free and customize it for your property. Go digital with RentalWaivers starting at 6¢ per signature." },
      { question: "Does homeowner's insurance make a waiver unnecessary?", answer: "No. Insurance defends and pays claims, but a signed waiver can prevent the claim from succeeding in the first place — and some insurers require one for short-term rentals." },
      { question: "Can I use this for a one-day event at my house?", answer: "Yes. Fill in the rental purpose and times. For larger events, also require the renter's event insurance and vendor lists." },
      { question: "What if a guest is injured and didn't sign?", answer: "Only the signer is bound. Have the primary renter sign and accept responsibility for their party, and ask each adult guest to sign where practical." },
    ],
    relatedIndustry: "vacation-rental-waiver-software",
    relatedTemplates: ["vacation-rental-waiver-template", "party-equipment-rental-waiver-template", "airbnb-vrbo-waiver-template"],
  },
  {
    slug: "airbnb-vrbo-waiver-template",
    name: "Airbnb / VRBO Waiver",
    metaTitle: "Free Airbnb & VRBO Waiver Template for Hosts — Guest Liability Release",
    metaDescription: "Free waiver template for Airbnb and VRBO hosts. Protect yourself beyond platform coverage — guest injuries, pool use, property damage. Collect e-signatures automatically.",
    h1: "Airbnb & VRBO Host Waiver Template",
    intro: "Platform protection programs like AirCover are limited, slow, and can deny claims. This Airbnb and VRBO waiver template gives hosts their own signed legal protection — covering guest injuries, amenity use, and property damage — collected automatically after every booking.",
    risks: ["Guest injuries on the property leading to lawsuits", "Pool, hot tub, and water amenity accidents", "Damage claims denied by platform protection programs", "Injuries to guests' visitors who never agreed to house rules", "Parties and occupancy violations", "Disputes over security deposit deductions"],
    clauses: [
      { title: "Assumption of Risk", text: "Guest acknowledges that staying at a residential short-term rental involves inherent risks and voluntarily assumes all risks of injury, illness, loss, or damage arising from the stay, for themselves and all members of their party." },
      { title: "Release of Host Liability", text: "Guest releases and discharges the Host, property owner, and any co-hosts or managers from all claims arising from the stay, except in cases of gross negligence or willful misconduct." },
      { title: "House Rules Acknowledgment", text: "Guest confirms they have read and agree to the listing's house rules, occupancy limits, quiet hours, and amenity rules, and accepts that violations may result in termination of the stay without refund." },
      { title: "Amenity Use and Supervision", text: "Guest agrees to use pools, hot tubs, grills, and recreational equipment at their own risk, follow posted safety rules, and supervise children and non-swimmers at all times." },
      { title: "Damage Responsibility", text: "Guest accepts financial responsibility for damage, missing items, or excessive cleaning caused by Guest or Guest's party, and authorizes deduction from the security deposit where applicable." },
      { title: "Indemnification", text: "Guest agrees to indemnify and hold harmless the Host from claims brought by Guest's visitors or third parties arising from Guest's stay." },
    ],
    customFields: ["Full legal name of booking guest", "Platform and reservation code", "Check-in and check-out dates", "Number of adults, children, and pets", "Names of minors in the party", "Emergency contact", "Acknowledgment of specific amenities (pool, hot tub, dock)", "Security deposit acknowledgment"],
    bestPractices: [
      "Send the waiver automatically right after booking confirmation — before guests arrive",
      "Mention the waiver requirement in your listing so it never surprises a guest",
      "Reference your listing's house rules by name and date so the waiver ties to the exact version",
      "Require the waiver before sending check-in instructions or door codes",
      "Re-collect a waiver for every stay — returning guests included",
      "Store signed waivers with timestamps and IP addresses for a complete audit trail",
    ],
    faqItems: [
      { question: "Is it allowed to ask Airbnb guests to sign a waiver?", answer: "Yes, hosts commonly require a separate rental agreement or waiver. Disclose the requirement in your listing description so guests see it before booking." },
      { question: "Doesn't AirCover protect me?", answer: "AirCover is a platform program with exclusions and a claims process the platform controls. A signed waiver is your own contract and can stop a claim before it starts. They work best together." },
      { question: "Will asking for a waiver hurt my bookings?", answer: "Hosts who present it professionally — automated, mobile-friendly, 60 seconds to sign — rarely see pushback. It signals a well-run property." },
      { question: "How do I collect signatures without awkwardness?", answer: "RentalWaivers emails or texts the signing link automatically when a booking is confirmed. Guests sign on their phone in under a minute." },
      { question: "Is this template free?", answer: "Yes, download and customize it free. Digital signing starts at 6¢ per waiver with no monthly fee." },
    ],
    relatedIndustry: "vacation-rental-waiver-software",
    relatedTemplates: ["vacation-rental-waiver-template", "house-rental-waiver-template", "hot-tub-waiver-template"],
  },
  {
    slug: "cabin-rental-waiver-template",
    name: "Cabin Rental Waiver",
    metaTitle: "Free Cabin Rental Waiver Template — Mountain & Lake Cabin Liability",
    metaDescription: "Free cabin rental waiver template covering fireplaces, docks, wildlife, ATVs, and remote-location risks. Customize and collect digital signatures before check-in.",
    h1: "Cabin Rental Waiver Template",
    intro: "Cabins come with unique exposures — wood stoves, fireplaces, private docks, steep terrain, wildlife, and remote locations far from emergency services. This cabin rental waiver template addresses those risks directly so owners of mountain, lake, and forest cabins are protected.",
    risks: ["Burns and carbon monoxide exposure from fireplaces and wood stoves", "Drowning or injury at private docks and waterfronts", "Falls on steep, uneven, or icy terrain", "Wildlife encounters", "Delayed emergency response in remote areas", "Guest use of owner-provided boats, ATVs, or snowmobiles"],
    clauses: [
      { title: "Assumption of Risk", text: "Guest acknowledges that the cabin is located in a rural or remote setting with inherent risks including uneven terrain, wildlife, limited cell service, and delayed emergency response times. Guest voluntarily assumes all such risks." },
      { title: "Release of Liability", text: "Guest releases and discharges [Owner Name] from all claims for injury, loss, or damage arising from the stay, including risks associated with the natural environment, except in cases of gross negligence or willful misconduct." },
      { title: "Fireplace, Stove, and Fire Pit Use", text: "Guest agrees to operate fireplaces, wood stoves, and fire pits according to posted instructions, never leave fires unattended, and fully extinguish all fires. Guest is responsible for damage caused by improper use." },
      { title: "Waterfront and Dock Use", text: "Guest acknowledges that docks and waterfront areas are unsupervised, used at Guest's own risk, and that children must be accompanied by an adult at all times near water. Life jackets should be worn for all water activities." },
      { title: "Recreational Equipment", text: "Guest agrees not to operate any owner-provided boats, ATVs, snowmobiles, or other motorized equipment without prior written approval and completion of any required additional waiver." },
      { title: "Wildlife and Food Storage", text: "Guest agrees to follow posted wildlife safety rules, secure food and trash, and not feed or approach wild animals." },
    ],
    customFields: ["Full legal name of primary guest", "Stay dates", "Number of guests and ages of children", "Emergency contact and phone", "Vehicle information (for remote access roads)", "Intended use of boats, ATVs, or equipment", "Acknowledgment of wood stove / fireplace instructions", "Pet information"],
    bestPractices: [
      "Name the specific hazards of your location — bears, ice, steep driveways, deep water",
      "Include emergency contacts and the cabin's physical address inside the waiver for 911 calls",
      "Require a separate signed waiver for motorized equipment use",
      "State burn-ban and fire-restriction policies with a seasonal clause",
      "Add a winter-access clause if roads are unmaintained (4WD required, no refunds for weather)",
      "Photograph the cabin's condition before each stay to support damage claims",
    ],
    faqItems: [
      { question: "Is this cabin waiver template free?", answer: "Yes. Download it free, customize for your cabin, and go digital for 6¢ per signature with RentalWaivers." },
      { question: "Do I need a separate waiver for the boat or ATV?", answer: "Recommended. A general cabin waiver plus an activity-specific waiver for motorized equipment gives you the strongest protection." },
      { question: "What about guests using the fireplace incorrectly?", answer: "The fireplace clause assigns responsibility for improper use. Pair it with posted instructions at the cabin for the best defense." },
      { question: "Does this work for cabins listed on Airbnb or VRBO?", answer: "Yes — send the signing link automatically after booking. Disclose the waiver requirement in your listing." },
    ],
    relatedIndustry: "vacation-rental-waiver-software",
    relatedTemplates: ["lake-house-rental-waiver-template", "vacation-rental-waiver-template", "atv-rental-waiver-template"],
  },
  {
    slug: "beach-house-rental-waiver-template",
    name: "Beach House Rental Waiver",
    metaTitle: "Free Beach House Rental Waiver Template — Waterfront Liability Protection",
    metaDescription: "Free beach house waiver template covering ocean hazards, decks, dunes, and water equipment. Protect your beachfront property — collect e-signatures automatically.",
    h1: "Beach House Rental Waiver Template",
    intro: "Beachfront properties face outsized liability: rip currents, surf injuries, dune erosion rules, elevated decks, and guests' water equipment. This beach house rental waiver template covers ocean-adjacent risks that generic rental agreements miss.",
    risks: ["Drowning and rip current incidents at the adjacent beach", "Falls from elevated decks, stairs, and boardwalks", "Injuries from surfboards, boogie boards, and beach equipment", "Sun exposure, heat exhaustion, and dehydration", "Damage from sand, saltwater, and wet gear brought indoors", "Violations of dune protection and beach access rules"],
    clauses: [
      { title: "Assumption of Risk", text: "Guest acknowledges that oceanfront and beach environments involve inherent risks including rip currents, large surf, marine life, sun exposure, and rapidly changing weather. Guest voluntarily assumes all such risks for themselves and their party." },
      { title: "Release of Liability", text: "Guest releases and discharges [Owner Name] from all claims for injury, loss, or damage arising from the stay or use of the beach and water adjacent to the property, except in cases of gross negligence or willful misconduct." },
      { title: "Ocean and Swimming Acknowledgment", text: "Guest acknowledges that no lifeguard is provided, that ocean conditions are unpredictable, and that children and inexperienced swimmers must be supervised by an adult at all times in or near the water." },
      { title: "Deck and Structure Safety", text: "Guest agrees to observe occupancy limits on decks and balconies, keep gates latched, and not climb on railings, dunes, or protective structures." },
      { title: "Beach Equipment Use", text: "Guest uses any owner-provided beach equipment — chairs, umbrellas, boards, kayaks — at their own risk and agrees to inspect equipment before use and secure it against wind." },
      { title: "Property Care", text: "Guest agrees to rinse off sand and salt before entering the house, follow posted dune and beach access rules, and accept responsibility for damage beyond normal wear and tear." },
    ],
    customFields: ["Full legal name of primary guest", "Stay dates", "Number of guests and ages of children", "Swimming ability of party members", "Emergency contact", "Use of owner-provided water equipment", "Acknowledgment of rip current safety information", "Pet information"],
    bestPractices: [
      "Include a rip current safety acknowledgment as its own checkbox",
      "Post the local beach flag warning system in the house and reference it in the waiver",
      "Set explicit deck and balcony occupancy limits — structural failures drive major claims",
      "Prohibit glass on the beach and decks in writing",
      "Require separate waivers for kayaks or motorized watercraft you provide",
      "Add a hurricane/evacuation clause stating refund and rebooking policy",
    ],
    faqItems: [
      { question: "Is this beach house waiver template free?", answer: "Yes. Download it free and customize it. Digital signing starts at 6¢ per waiver with no monthly fee." },
      { question: "Am I liable if a guest drowns at a public beach?", answer: "Liability depends on your state and whether you represented the water as supervised. A clear waiver stating no lifeguard is provided and guests swim at their own risk is an important defense." },
      { question: "Should the waiver cover beach equipment I lend out?", answer: "Yes — the equipment clause covers owner-provided items. For higher-risk craft like kayaks or jet skis, use a dedicated equipment waiver too." },
      { question: "Do guests push back on signing?", answer: "When it's automated and mobile-friendly, almost never. Guests sign on their phone in about a minute before check-in." },
    ],
    relatedIndustry: "vacation-rental-waiver-software",
    relatedTemplates: ["vacation-rental-waiver-template", "lake-house-rental-waiver-template", "paddleboard-rental-waiver-template"],
  },
  {
    slug: "lake-house-rental-waiver-template",
    name: "Lake House Rental Waiver",
    metaTitle: "Free Lake House Rental Waiver Template — Dock, Boat & Swim Liability",
    metaDescription: "Free lake house waiver template covering docks, swimming, boats, and watercraft. Protect your lakefront rental — send and collect signatures automatically.",
    h1: "Lake House Rental Waiver Template",
    intro: "Lakefront rentals concentrate risk in one place: docks, swimming areas, boats, and watercraft. This lake house rental waiver template covers dock safety, swim-at-your-own-risk acknowledgment, and watercraft rules so a great lake weekend doesn't become a lawsuit.",
    risks: ["Drowning at private docks and swim areas", "Slip and falls on wet docks and boat lifts", "Injuries from diving into shallow or unknown water", "Boat, kayak, and jet ski accidents", "Fishing hook and equipment injuries", "Alcohol-related incidents on the water"],
    clauses: [
      { title: "Assumption of Risk", text: "Guest acknowledges that lakefront properties involve inherent risks including deep water, sudden drop-offs, submerged objects, boat traffic, and changing weather. Guest voluntarily assumes all such risks for themselves and their party." },
      { title: "Release of Liability", text: "Guest releases and discharges [Owner Name] from all claims for injury, loss, or damage arising from the stay or use of the dock, waterfront, and water, except in cases of gross negligence or willful misconduct." },
      { title: "Dock and Swim Area Rules", text: "Guest acknowledges that swimming is unsupervised and at Guest's own risk. No diving from docks, boats, or structures. Children must wear life jackets near the water and be supervised by an adult at all times." },
      { title: "Watercraft Use", text: "Guest agrees not to operate owner-provided boats, jet skis, kayaks, or paddleboards without prior approval and any required additional waivers. Operators must follow state boating laws, and no alcohol is permitted while operating watercraft." },
      { title: "Life Jacket Acknowledgment", text: "Guest acknowledges that life jackets are available at the property and agrees that all children and non-swimmers will wear them during water activities." },
      { title: "Indemnification", text: "Guest agrees to indemnify and hold harmless [Owner Name] from claims brought by Guest's visitors or third parties arising from use of the property, dock, or watercraft." },
    ],
    customFields: ["Full legal name of primary guest", "Stay dates", "Number of guests and ages of children", "Watercraft to be used (boat, jet ski, kayak)", "Boating license or certification number if required", "Swimming ability of party members", "Emergency contact", "Acknowledgment of life jacket policy"],
    bestPractices: [
      "Make the no-diving rule its own initialed line — shallow-water diving injuries are among the most severe claims",
      "Require a separate boat or jet ski waiver with operator details for motorized watercraft",
      "Reference your state's boating license and age requirements",
      "Keep life jackets visibly available and note their location in the waiver",
      "Prohibit alcohol for anyone operating watercraft, in writing",
      "Photograph dock condition each season and repair promptly — premises liability starts with maintenance",
    ],
    faqItems: [
      { question: "Is this lake house waiver template free?", answer: "Yes. Download it free, customize for your lake, and collect digital signatures for 6¢ per waiver." },
      { question: "Can guests use my boat if they sign this?", answer: "This template covers general watercraft acknowledgment. For motorized boats and jet skis, add a dedicated watercraft waiver with operator licensing details." },
      { question: "Does the waiver cover guests' friends who visit for the day?", answer: "The booking guest accepts responsibility for their party. For day visitors using the dock or boats, have them sign individually — RentalWaivers makes this a 60-second process on their phone." },
      { question: "What if someone ignores the no-diving rule?", answer: "The waiver doesn't excuse gross negligence on your part, but a signed acknowledgment of a specific rule is strong evidence the guest assumed that risk." },
    ],
    relatedIndustry: "vacation-rental-waiver-software",
    relatedTemplates: ["beach-house-rental-waiver-template", "cabin-rental-waiver-template", "boat-rental-waiver-template"],
  },
  {
    slug: "condo-rental-waiver-template",
    name: "Condo Rental Waiver",
    metaTitle: "Free Condo Rental Waiver Template — Short-Term Condo Liability Release",
    metaDescription: "Free condo rental waiver template for short-term stays. Covers balconies, shared amenities, HOA rules, and guest injury. Collect signatures digitally before check-in.",
    h1: "Condo Rental Waiver Template",
    intro: "Short-term condo rentals layer owner liability on top of HOA rules and shared amenities — balconies, gyms, pools, and parking structures. This condo rental waiver template protects owners and keeps guests accountable to building rules.",
    risks: ["Balcony falls and railing accidents", "Injuries in shared pools, gyms, saunas, and spas", "HOA rule violations and fines triggered by guests", "Damage to the unit or common areas", "Parking accidents and towing disputes", "Noise complaints and neighbor disputes"],
    clauses: [
      { title: "Assumption of Risk", text: "Guest acknowledges that occupancy of the condominium and use of its amenities involves inherent risks and voluntarily assumes all risks of injury, loss, or damage during the stay." },
      { title: "Release of Liability", text: "Guest releases and discharges [Owner Name] from all claims arising from the stay, including use of the unit, balcony, and building amenities, except in cases of gross negligence or willful misconduct." },
      { title: "Balcony Safety", text: "Guest agrees not to climb on, lean over, or hang items from balcony railings, to keep balcony furniture away from railings, and to supervise children on balconies at all times." },
      { title: "Building and HOA Rules", text: "Guest agrees to comply with all building and homeowners association rules, including quiet hours, amenity hours, parking assignments, and check-in procedures. Guest is responsible for any fines caused by Guest's violations." },
      { title: "Shared Amenity Use", text: "Guest uses shared amenities — pools, gyms, spas, grills, and lounges — at their own risk, agrees to follow posted rules, and acknowledges no lifeguard or supervision is provided unless stated." },
      { title: "Damage and Indemnification", text: "Guest accepts responsibility for damage to the unit or common areas caused by Guest or Guest's party and agrees to indemnify [Owner Name] against third-party claims arising from the stay." },
    ],
    customFields: ["Full legal name of primary guest", "Stay dates", "Number of guests", "Vehicle and parking information", "Names of minors", "Emergency contact", "Amenities guest intends to use", "HOA rules acknowledgment checkbox"],
    bestPractices: [
      "Attach the HOA's short-term rental rules as an exhibit and reference them in the waiver",
      "Make balcony safety a standalone checkbox — especially for units above the second floor",
      "Include who pays HOA fines (the guest) in explicit language",
      "Add parking instructions and a tow-away acknowledgment",
      "Verify your HOA and local jurisdiction allow short-term rentals before listing",
      "Automate waiver delivery on booking confirmation so no guest arrives unsigned",
    ],
    faqItems: [
      { question: "Is this condo waiver template free?", answer: "Yes. Download it free and customize it. Digital signing starts at 6¢ per waiver." },
      { question: "Does the HOA's insurance cover my guests?", answer: "HOA master policies cover the building and common areas, not your liability as a host for guest injuries in your unit. You need your own protection — insurance plus a signed waiver." },
      { question: "Can I pass HOA fines to my guest?", answer: "Yes, if the waiver says so explicitly. The building rules clause in this template assigns fine responsibility to the guest." },
      { question: "What about guests using the gym or pool?", answer: "The shared amenity clause covers use at their own risk. Confirm the HOA allows guests to use amenities and note any wristband or key-fob rules." },
    ],
    relatedIndustry: "vacation-rental-waiver-software",
    relatedTemplates: ["vacation-rental-waiver-template", "airbnb-vrbo-waiver-template", "house-rental-waiver-template"],
  },
  {
    slug: "pool-rental-waiver-template",
    name: "Pool Rental Waiver",
    metaTitle: "Free Swimming Pool Rental Waiver Template — Hourly Pool Host Liability",
    metaDescription: "Free pool rental waiver template for hosts renting pools by the hour. Covers drowning risk, supervision, diving rules, and guest injury. Sign digitally before every swim.",
    h1: "Swimming Pool Rental Waiver Template",
    intro: "Renting your pool by the hour or for parties puts swimmers on your property — and drowning is one of the highest-severity liability exposures a homeowner can face. This pool rental waiver template covers supervision requirements, diving prohibitions, and swim-at-your-own-risk acknowledgment for every guest.",
    risks: ["Drowning and near-drowning incidents", "Diving injuries in shallow water", "Slip and falls on wet decks", "Unsupervised children in the pool area", "Alcohol-related incidents", "Injuries from pool equipment, slides, and toys"],
    clauses: [
      { title: "Assumption of Risk", text: "Renter acknowledges that swimming and pool use involve inherent risks including drowning, slip and fall, and water-related injury. Renter voluntarily assumes all risks for themselves and all members of their party." },
      { title: "Release of Liability", text: "Renter releases and discharges [Host Name] from all claims for injury, illness, loss, or damage arising from use of the pool and surrounding areas, except in cases of gross negligence or willful misconduct." },
      { title: "No Diving", text: "Renter agrees that diving, jumping from structures, and headfirst entry are strictly prohibited. Renter acknowledges that the pool may have shallow areas and that depth markings must be observed." },
      { title: "Supervision of Children", text: "Renter agrees that all children and non-swimmers will be supervised by a responsible adult at all times, with at least one designated adult water watcher who is not consuming alcohol. Children under [age] must remain within arm's reach of an adult." },
      { title: "Pool Rules Compliance", text: "Renter agrees to follow all posted pool rules, including capacity limits, no glass containers, no running, and designated hours of use." },
      { title: "Indemnification", text: "Renter agrees to indemnify and hold harmless [Host Name] from claims brought by Renter's guests or third parties arising from the rental period." },
    ],
    customFields: ["Full legal name of renter", "Rental date and time block", "Number of swimmers and non-swimmers", "Ages of children attending", "Designated water watcher name", "Swimming ability of party", "Emergency contact", "Acknowledgment of no-diving rule"],
    bestPractices: [
      "Require a named 'water watcher' on every waiver — designated sober adult supervision is the strongest drowning defense",
      "Make the no-diving clause a separately initialed line",
      "List your pool's maximum depth and shallow areas directly in the waiver",
      "Prohibit glass and alcohol, or explicitly permit and regulate them — don't stay silent",
      "Require every adult guest to be covered — either individual signatures or the renter accepting responsibility for named guests",
      "Keep rescue equipment visible and note its location in your pool rules",
    ],
    faqItems: [
      { question: "Is this pool rental waiver template free?", answer: "Yes. Download it free and customize it. Collect digital signatures before every rental for 6¢ per waiver." },
      { question: "Does homeowner's insurance cover pool rentals?", answer: "Many homeowner policies exclude commercial activity like paid pool rentals. Check your policy, get proper coverage, and use a signed waiver as your first line of defense." },
      { question: "Should every swimmer sign?", answer: "Ideally each adult signs. At minimum, the renter signs and lists all guests, accepting responsibility for minors in the party." },
      { question: "Can I rent my pool for parties with alcohol?", answer: "You can, but alcohol around water raises risk sharply. Address it explicitly in the waiver and require the designated water watcher to remain sober." },
    ],
    relatedIndustry: "vacation-rental-waiver-software",
    relatedTemplates: ["hot-tub-waiver-template", "vacation-rental-waiver-template", "party-equipment-rental-waiver-template"],
  },
  {
    slug: "hot-tub-waiver-template",
    name: "Hot Tub / Spa Waiver",
    metaTitle: "Free Hot Tub & Spa Waiver Template — Guest Liability Release",
    metaDescription: "Free hot tub waiver template for vacation rentals and spas. Covers heat exposure, health warnings, alcohol risk, and supervision. Collect e-signatures before use.",
    h1: "Hot Tub & Spa Waiver Template",
    intro: "Hot tubs combine heat, water, and often alcohol — a mix that drives real injury claims for vacation rental hosts and spa operators. This hot tub waiver template covers health warnings, time limits, supervision, and alcohol acknowledgment.",
    risks: ["Overheating, dehydration, and fainting", "Drowning, especially combined with alcohol", "Slip and falls entering and exiting", "Aggravation of heart conditions, pregnancy, or illness", "Injuries to unsupervised children", "Skin irritation from water chemistry"],
    clauses: [
      { title: "Assumption of Risk", text: "Guest acknowledges that hot tub and spa use involves inherent risks including overheating, dehydration, fainting, and drowning. Guest voluntarily assumes all risks of use." },
      { title: "Release of Liability", text: "Guest releases and discharges [Owner/Operator Name] from all claims for injury, illness, loss, or damage arising from hot tub or spa use, except in cases of gross negligence or willful misconduct." },
      { title: "Health Warning", text: "Guest confirms they have no medical condition that makes hot tub use unsafe. Pregnant women, persons with heart conditions, high or low blood pressure, diabetes, or those taking medication that causes drowsiness should consult a physician before use and use at their own risk." },
      { title: "Alcohol and Time Limits", text: "Guest acknowledges that alcohol consumption increases the risks of hot tub use, agrees to limit sessions to 15–20 minutes, stay hydrated, and never use the hot tub alone or while intoxicated." },
      { title: "Supervision of Children", text: "Guest agrees that children must be supervised by an adult at all times, that children under [age] are not permitted in the hot tub, and that the cover will be replaced and secured after each use." },
      { title: "Rules Compliance", text: "Guest agrees to shower before use, keep glass away from the hot tub area, observe posted capacity limits, and follow all posted rules." },
    ],
    customFields: ["Full legal name", "Stay or rental dates", "Number of users", "Ages of children in party", "Health condition acknowledgment checkbox", "Alcohol risk acknowledgment checkbox", "Emergency contact", "Property or unit reference"],
    bestPractices: [
      "Keep the health warning prominent — it should not be buried in paragraph text",
      "State a specific maximum session time (15–20 minutes) in writing",
      "Require the cover to be replaced and locked after use, in writing",
      "Post water temperature and keep it at or below 104°F (40°C)",
      "Include an alcohol acknowledgment even at properties where you can't control consumption",
      "Maintain water chemistry logs — they support your defense if a guest claims irritation or illness",
    ],
    faqItems: [
      { question: "Is this hot tub waiver template free?", answer: "Yes. Download it free and customize it for your property. Digital signing starts at 6¢ per waiver." },
      { question: "Can I prohibit alcohol in the hot tub?", answer: "You can prohibit it outright or include an acknowledgment of increased risk. An explicit written rule is far better than silence either way." },
      { question: "Should kids be allowed in the hot tub?", answer: "Most guidance recommends against hot tub use for young children. Set a minimum age in the waiver and require adult supervision for older children." },
      { question: "Does this cover guests at my Airbnb?", answer: "Yes — bundle it with your main guest waiver or send it as a standalone acknowledgment before check-in." },
    ],
    relatedIndustry: "vacation-rental-waiver-software",
    relatedTemplates: ["pool-rental-waiver-template", "airbnb-vrbo-waiver-template", "vacation-rental-waiver-template"],
  },
  {
    slug: "party-equipment-rental-waiver-template",
    name: "Party & Event Rental Waiver",
    metaTitle: "Free Party & Event Rental Waiver Template — Tables, Tents & More",
    metaDescription: "Free party rental waiver template for tent, table, chair, and event equipment companies. Covers setup hazards, equipment damage, and injury. Go digital in minutes.",
    h1: "Party & Event Equipment Rental Waiver Template",
    intro: "Party rental companies face claims from tent collapses, tipping furniture, and damaged equipment returns. This party and event rental waiver template covers setup and use hazards, weather policies, and damage responsibility for tents, tables, chairs, dance floors, and event equipment.",
    risks: ["Tent or canopy collapse from wind or improper anchoring", "Injuries from tipping tables, chairs, or staging", "Electrical hazards from lighting, heaters, and generators", "Damage to rented equipment during the event", "Weather-related event injuries", "Injuries during customer self-setup"],
    clauses: [
      { title: "Assumption of Risk", text: "Renter acknowledges that use of rented event equipment involves inherent risks including structural failure, tipping, electrical hazards, and weather exposure. Renter voluntarily assumes all risks of use during the rental period." },
      { title: "Release of Liability", text: "Renter releases and discharges [Company Name], its owners, employees, and agents from all claims for injury, loss, or damage arising from the rental equipment, except in cases of gross negligence or willful misconduct." },
      { title: "Proper Use and Supervision", text: "Renter agrees to use all equipment only for its intended purpose, follow all setup and safety instructions, supervise use during the event, and not modify, move, or disassemble installed equipment." },
      { title: "Weather Policy", text: "Renter acknowledges that tents and canopies are not safe in high winds, lightning, or severe weather, agrees to evacuate equipment in such conditions, and follows the company's stated weather decision policy." },
      { title: "Damage and Loss Responsibility", text: "Renter accepts financial responsibility for damage, loss, or theft of rental equipment beyond normal wear and tear, and agrees to the stated replacement cost schedule." },
      { title: "Indemnification", text: "Renter agrees to indemnify and hold harmless [Company Name] from claims brought by event guests or third parties arising from use of the rental equipment." },
    ],
    customFields: ["Full legal name of renter", "Event date and location", "Equipment list rented", "Setup by company or customer", "Event type and expected guest count", "Surface type for tent anchoring (grass, concrete)", "Emergency contact", "Damage waiver elected or declined"],
    bestPractices: [
      "Require company installation for large tents — customer-installed tent collapses are the worst claims",
      "State wind speed evacuation thresholds (typically 30–40 mph) in the waiver",
      "Attach the equipment list and replacement cost schedule as an exhibit",
      "For customer setup, include written instructions and require an acknowledgment checkbox",
      "Offer an optional damage waiver fee and document election or decline",
      "Collect the waiver at booking, not at delivery when the customer is rushing",
    ],
    faqItems: [
      { question: "Is this party rental waiver template free?", answer: "Yes. Download it free and customize it for your inventory. Digital signing starts at 6¢ per waiver." },
      { question: "Who is liable if a tent blows over at an event?", answer: "Liability depends on installation, warnings, and weather decisions. A waiver with explicit wind thresholds and evacuation duties is a key defense." },
      { question: "Should I offer a damage waiver fee?", answer: "Many rental companies offer an optional damage waiver (often 8–10% of the rental) covering accidental damage. Document the customer's choice in writing." },
      { question: "Does this cover bounce houses?", answer: "Bounce houses and inflatables carry higher risk — use the dedicated bounce house waiver template which includes supervision and anchoring specifics." },
    ],
    relatedIndustry: "equipment-rental-waiver-software",
    relatedTemplates: ["bounce-house-rental-waiver-template", "equipment-rental-waiver-template", "house-rental-waiver-template"],
  },
  {
    slug: "car-rental-waiver-template",
    name: "Car Rental Waiver",
    metaTitle: "Free Car Rental Waiver Template — Vehicle Liability & Damage Release",
    metaDescription: "Free car rental waiver template for rental agencies and peer-to-peer hosts. Covers accident liability, damage responsibility, and authorized drivers. Sign digitally.",
    h1: "Car Rental Waiver Template",
    intro: "Whether you run a rental fleet or rent your own vehicle peer-to-peer, this car rental waiver template covers accident liability, damage responsibility, authorized driver restrictions, and fuel and toll policies — the terms that decide who pays when something goes wrong.",
    risks: ["Traffic accidents causing injury or death", "Vehicle damage during the rental period", "Unauthorized drivers operating the vehicle", "Theft of the vehicle or contents", "Traffic violations, tolls, and parking tickets", "Mechanical failure claims from renters"],
    clauses: [
      { title: "Assumption of Risk", text: "Renter acknowledges that operating a motor vehicle involves inherent risks including collision, mechanical failure, and road hazards. Renter voluntarily assumes all risks of operating the rental vehicle." },
      { title: "Release of Liability", text: "Renter releases and discharges [Company/Owner Name] from all claims for injury, loss, or damage arising from Renter's operation of the vehicle, except in cases of gross negligence or willful misconduct." },
      { title: "Authorized Drivers Only", text: "Renter agrees that only drivers listed on this agreement, holding valid licenses and meeting minimum age requirements, may operate the vehicle. Operation by any unauthorized driver voids all protections and makes Renter fully liable." },
      { title: "Damage Responsibility", text: "Renter accepts financial responsibility for all damage to the vehicle during the rental period, including collision, weather, vandalism, and interior damage, regardless of fault, subject to any protection plan elected." },
      { title: "Prohibited Use", text: "Renter agrees not to operate the vehicle under the influence, off-road, for racing, for rideshare or delivery services without written approval, or outside the permitted geographic area." },
      { title: "Violations, Tolls, and Fees", text: "Renter is responsible for all traffic violations, tolls, parking fees, and impound costs incurred during the rental period, plus any administrative fees stated in this agreement." },
    ],
    customFields: ["Full legal name of renter", "Driver's license number, state, and expiration", "Additional authorized drivers", "Vehicle make, model, year, and plate", "Rental period and mileage allowance", "Insurance information or protection plan election", "Fuel level at pickup and return policy", "Emergency contact"],
    bestPractices: [
      "Verify and photograph every renter's license — no license photo, no keys",
      "Photograph the vehicle from all angles at pickup and return with timestamps",
      "List permitted geography explicitly (e.g., 'state of Florida only')",
      "Require renters to show proof of personal auto insurance or buy your protection plan",
      "Document fuel level, mileage, and existing damage on a signed condition report",
      "Keep signed agreements for at least your state's injury statute of limitations",
    ],
    faqItems: [
      { question: "Is this car rental waiver template free?", answer: "Yes. Download it free and customize it. Digital signing starts at 6¢ per waiver." },
      { question: "Does a waiver replace rental car insurance?", answer: "No. You still need commercial fleet insurance or peer-to-peer platform coverage. The waiver defines renter responsibility and deters claims; insurance pays when they happen." },
      { question: "What if someone else drives and crashes?", answer: "The authorized-drivers clause makes the renter fully liable for unauthorized use. Always list every driver on the agreement." },
      { question: "Can I use this for Turo or peer-to-peer rentals?", answer: "Platform terms govern what additional agreements you can require — check your platform's policy. Many hosts use supplemental agreements for terms the platform allows." },
    ],
    relatedIndustry: "equipment-rental-waiver-software",
    relatedTemplates: ["rv-rental-waiver-template", "scooter-rental-waiver-template", "equipment-rental-waiver-template"],
  },
  {
    slug: "golf-cart-rental-waiver-template",
    name: "Golf Cart Rental Waiver",
    metaTitle: "Free Golf Cart Rental Waiver Template — Street & Course Liability",
    metaDescription: "Free golf cart rental waiver template covering rollovers, road use, age limits, and damage. For resorts, communities, and rental companies. Sign digitally in minutes.",
    h1: "Golf Cart Rental Waiver Template",
    intro: "Golf carts feel harmless — until a rollover or street collision produces a serious injury claim. This golf cart rental waiver template covers safe operation, age and licensing rules, road-use restrictions, and damage responsibility for resorts, campgrounds, and rental companies.",
    risks: ["Rollovers from sharp turns or slopes", "Collisions with vehicles, pedestrians, or objects", "Passengers falling from the cart", "Underage or unlicensed operation", "Damage to carts from reckless use", "Street-legal compliance violations"],
    clauses: [
      { title: "Assumption of Risk", text: "Renter acknowledges that golf cart operation involves inherent risks including rollover, collision, and falls. Renter voluntarily assumes all risks of operating or riding in the rental cart." },
      { title: "Release of Liability", text: "Renter releases and discharges [Company Name], its owners, employees, and agents from all claims for injury, loss, or damage arising from use of the rental cart, except in cases of gross negligence or willful misconduct." },
      { title: "Operator Requirements", text: "Renter agrees that only persons meeting the minimum age of [age] and holding a valid driver's license may operate the cart, and that all operators will follow posted rules, speed limits, and traffic laws." },
      { title: "Safe Operation", text: "Renter agrees to keep all passengers seated with limbs inside the cart, observe the stated passenger capacity, avoid steep slopes and sharp high-speed turns, and never operate the cart under the influence of alcohol or drugs." },
      { title: "Road Use Restrictions", text: "Renter agrees to operate the cart only in permitted areas and on roads where golf carts are legally allowed, and to comply with all local low-speed vehicle regulations." },
      { title: "Damage Responsibility", text: "Renter accepts financial responsibility for damage to or loss of the cart during the rental period beyond normal wear and tear, and agrees to the stated repair and replacement cost policy." },
    ],
    customFields: ["Full legal name of renter", "Driver's license number and state", "Age of primary operator", "Additional operators", "Cart number or ID", "Rental period", "Intended use area (resort, campground, street)", "Emergency contact"],
    bestPractices: [
      "Set a minimum operator age (16–25 depending on your market) and verify licenses",
      "State passenger capacity explicitly — overloading causes falls and rollovers",
      "Prohibit alcohol for operators in its own clause",
      "Mark permitted roads and no-go areas on a map attached to the waiver",
      "Photograph cart condition at pickup and return",
      "For street-legal carts, confirm local LSV registration and insurance requirements",
    ],
    faqItems: [
      { question: "Is this golf cart waiver template free?", answer: "Yes. Download it free and customize it. Digital signing starts at 6¢ per waiver." },
      { question: "Do golf cart renters need a driver's license?", answer: "For street use, most jurisdictions require a valid license. Even on private property, requiring one is a smart safety screen — put it in the waiver." },
      { question: "Are golf cart waivers enforceable?", answer: "Generally yes for ordinary negligence in most states. Enforceability varies, so have an attorney in your state review the final version." },
      { question: "What about passengers who didn't sign?", answer: "The renter accepts responsibility for their party. For resort or group rentals, you can have each adult sign — it takes about a minute per phone." },
    ],
    relatedIndustry: "equipment-rental-waiver-software",
    relatedTemplates: ["scooter-rental-waiver-template", "atv-rental-waiver-template", "bike-rental-waiver-template"],
  },
];
