export interface WaiverTemplatePage {
  slug: string;
  name: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  intro: string;
  risks: string[];
  clauses: { title: string; text: string }[];
  customFields: string[];
  bestPractices: string[];
  faqItems: { question: string; answer: string }[];
  relatedIndustry: string;
  relatedTemplates: string[];
}

export const waiverTemplatePages: WaiverTemplatePage[] = [
  {
    slug: "kayak-rental-waiver-template",
    name: "Kayak Rental Waiver",
    metaTitle: "Free Kayak Rental Waiver Template — Download or Sign Digitally",
    metaDescription: "Download a free, legally-reviewed kayak rental waiver template. Includes assumption of risk, release of liability, and drowning acknowledgment. Go digital in 5 minutes.",
    h1: "Kayak Rental Waiver Template",
    intro: "This kayak rental waiver template covers the essential legal protections kayak rental operators need — from drowning risk acknowledgment to equipment damage liability. Use it as-is or customize it for your specific operation, location, and state requirements.",
    risks: ["Drowning or near-drowning", "Capsizing in cold water", "Collision with objects, other watercraft, or wildlife", "Sunburn, heat exhaustion, or hypothermia", "Strains, sprains, and physical injuries from paddling", "Equipment malfunction or failure"],
    clauses: [
      { title: "Assumption of Risk", text: "Participant acknowledges that kayaking involves inherent risks including but not limited to drowning, capsizing, exposure to weather conditions, and collision with natural or man-made objects. Participant voluntarily assumes all risks associated with kayak rental and use." },
      { title: "Release of Liability", text: "Participant releases and discharges [Business Name], its owners, employees, and agents from any and all claims, demands, or causes of action arising out of or related to any loss, damage, or injury sustained while participating in kayak rental activities, except in cases of gross negligence or willful misconduct." },
      { title: "Indemnification", text: "Participant agrees to indemnify, defend, and hold harmless [Business Name] from any claims brought by third parties arising from Participant's use of rental equipment or participation in kayaking activities." },
      { title: "Equipment Responsibility", text: "Participant acknowledges receipt of equipment in good working condition and agrees to return all equipment in the same condition. Participant agrees to be financially responsible for any damage to or loss of rental equipment beyond normal wear and tear." },
      { title: "Swimming Ability Declaration", text: "Participant confirms they are a competent swimmer and are physically capable of participating in kayaking activities. Participant agrees to wear a personal flotation device (PFD) at all times while on the water." },
      { title: "Medical Authorization", text: "In the event of an emergency, Participant authorizes [Business Name] to secure emergency medical treatment, transportation, and procedures as deemed necessary. Participant understands that any costs incurred are the sole responsibility of the Participant." },
    ],
    customFields: ["Full legal name", "Date of birth", "Emergency contact name and phone number", "Swimming ability (beginner/intermediate/advanced)", "Prior kayaking experience", "Number of participants in group", "Rental duration and equipment assigned", "Any medical conditions relevant to water activity"],
    bestPractices: [
      "Include specific water hazards at your location (rapids, currents, cold water temperatures)",
      "Require PFD acknowledgment as a separate checkbox — not buried in paragraph text",
      "Add a safety briefing confirmation checkbox so participants confirm they received instructions",
      "Include weather cancellation policy language to set clear expectations",
      "For guided tours, add a 'follow guide instructions' clause",
      "Include alcohol/drug use prohibition language",
    ],
    faqItems: [
      { question: "Is this kayak waiver template free?", answer: "Yes. Download it for free and customize it for your business. You can use it as a paper waiver or go digital with RentalWaivers starting at 6¢ per signature." },
      { question: "Does this template cover tandem kayaks?", answer: "Yes — the assumption of risk and liability release language applies to both single and tandem kayak rentals. For tandem kayaks, each participant should sign individually." },
      { question: "What about minors on kayak trips?", answer: "Add a guardian signature field. In most states, a parent can sign on behalf of a minor, though enforceability varies. Always include a separate section for the guardian's signature." },
      { question: "Do I need a lawyer to use this template?", answer: "We recommend having a licensed attorney in your state review your waiver. Waiver enforceability varies by jurisdiction and this template follows general best practices, not state-specific legal requirements." },
      { question: "Can I add my own clauses?", answer: "Absolutely. This is a starting template — customize it with your specific rental policies, location-specific hazards, and any additional terms your operation requires." },
    ],
    relatedIndustry: "kayak-rental-waivers",
    relatedTemplates: ["paddleboard-rental-waiver-template", "boat-rental-waiver-template"],
  },
  {
    slug: "bike-rental-waiver-template",
    name: "Bike Rental Waiver",
    metaTitle: "Free Bike Rental Waiver Template — Download or Use Digitally",
    metaDescription: "Free bike rental waiver template with helmet acknowledgment, traffic risk disclosure, and equipment liability clauses. Customize and go digital in minutes.",
    h1: "Bike Rental Waiver Template",
    intro: "This bike rental waiver template is designed for urban bike rental shops, tourism bike rentals, e-bike operators, and cycling tour companies. It covers traffic risks, helmet policies, equipment damage, and the specific liability considerations unique to cycling.",
    risks: ["Collision with vehicles, pedestrians, or objects", "Falls and impact injuries", "Equipment malfunction (brakes, tires, chains)", "Traffic and road hazard exposure", "Overexertion and heat-related illness", "Theft or loss of rental equipment"],
    clauses: [
      { title: "Assumption of Risk", text: "Participant acknowledges that cycling on public roads and trails involves inherent risks including collision, falls, equipment failure, and exposure to traffic. Participant voluntarily assumes all risks associated with bicycle rental and use." },
      { title: "Release of Liability", text: "Participant releases [Business Name], its owners, employees, and agents from any claims arising from loss, damage, or injury sustained while using rental bicycles, except in cases of gross negligence." },
      { title: "Helmet Acknowledgment", text: "Participant acknowledges that [Business Name] has offered/provided a helmet for use during the rental period. Participant understands the risks of cycling without a helmet and agrees that the decision to wear a helmet is solely their responsibility." },
      { title: "Traffic Law Compliance", text: "Participant agrees to obey all applicable traffic laws, signals, and signage while operating the rental bicycle. Participant acknowledges that cycling on public roads requires sharing the road with motor vehicles." },
      { title: "Equipment Responsibility", text: "Participant agrees to inspect the bicycle before use, report any defects immediately, and return all equipment in the condition received. Participant is financially responsible for damage, loss, or theft of rental equipment." },
      { title: "Indemnification", text: "Participant agrees to indemnify and hold harmless [Business Name] from any third-party claims arising from Participant's use of rental equipment." },
    ],
    customFields: ["Full legal name", "Height (for bike fitting)", "Helmet size or decline checkbox", "Planned route or destination", "Rental duration", "Bicycle number/ID", "Emergency contact", "Experience level (beginner/intermediate/advanced)"],
    bestPractices: [
      "Include a separate helmet checkbox — courts view this as stronger evidence of informed consent",
      "Add a bike inspection acknowledgment so renters confirm they checked brakes and tires",
      "For e-bikes, include specific electric motor safety warnings and speed limit disclosures",
      "Add local traffic law references specific to your city or state",
      "Include a return policy and late fee schedule",
      "For guided tours, add a 'stay with the group' clause",
    ],
    faqItems: [
      { question: "Does this template cover e-bikes?", answer: "The core liability language applies to both traditional and electric bikes. For e-bikes, we recommend adding specific clauses about electric motor safety, speed limitations, and battery handling." },
      { question: "Should I require helmets?", answer: "Laws vary by state and municipality. Regardless of local law, always offer helmets and include a helmet acknowledgment clause — it strengthens your legal position even where helmets aren't required by law." },
      { question: "What about bike theft during a rental?", answer: "Include an equipment responsibility clause that makes renters liable for theft or loss. Specify the replacement value and any security deposit policies." },
      { question: "Can I use this for a bike tour company?", answer: "Yes. Add clauses for following guide instructions, staying with the group, and any route-specific hazards. Each participant on a group tour should sign individually." },
    ],
    relatedIndustry: "bike-rental-waivers",
    relatedTemplates: ["scooter-rental-waiver-template", "equipment-rental-waiver-template"],
  },
  {
    slug: "atv-rental-waiver-template",
    name: "ATV Rental Waiver",
    metaTitle: "Free ATV Rental Waiver Template — Off-Road Liability Protection",
    metaDescription: "Free ATV/UTV rental waiver template with off-road risk disclosure, rollover acknowledgment, and equipment damage clauses. Download or go digital.",
    h1: "ATV Rental Waiver Template",
    intro: "ATVs and UTVs are among the highest-liability rental categories. This waiver template addresses the specific risks of off-road riding — rollover hazards, terrain dangers, speed-related injuries, and the physical demands of ATV operation.",
    risks: ["Rollover and ejection", "Collision with trees, rocks, or other vehicles", "Severe terrain hazards (ditches, hills, loose gravel)", "Speed-related injuries", "Burns from engine or exhaust contact", "Dust, debris, and environmental exposure"],
    clauses: [
      { title: "Assumption of Risk", text: "Participant acknowledges that ATV/UTV operation involves extreme inherent risks including but not limited to rollover, ejection, collision, and severe injury or death. Participant voluntarily assumes all such risks." },
      { title: "Release of Liability", text: "Participant releases [Business Name] from all claims arising from ATV/UTV rental and operation, except for gross negligence or willful misconduct by [Business Name]." },
      { title: "Safety Equipment Acknowledgment", text: "Participant acknowledges receipt of required safety equipment including helmet, goggles, and gloves. Participant agrees to wear all safety equipment at all times during operation." },
      { title: "Experience and Age Declaration", text: "Participant confirms they meet the minimum age requirement for ATV operation and possess sufficient skill and physical ability to safely operate the vehicle. Participant confirms they have received a safety briefing." },
      { title: "Trail Rules Compliance", text: "Participant agrees to operate the ATV/UTV only on designated trails, at safe speeds, and in accordance with all posted rules. Participant agrees not to attempt stunts, jumps, or reckless maneuvers." },
      { title: "Damage and Loss Liability", text: "Participant is financially responsible for any damage to the ATV/UTV beyond normal wear. Participant acknowledges the replacement/repair costs disclosed at checkout." },
    ],
    customFields: ["Full legal name and date of birth", "Driver's license number", "Prior ATV experience (none/some/experienced)", "Vehicle assigned (make/model/unit number)", "Safety briefing completion checkbox", "Emergency contact", "Medical conditions affecting operation", "Alcohol/drug use declaration"],
    bestPractices: [
      "Require a separate safety briefing confirmation — don't just include it in the waiver text",
      "Add minimum age requirements (typically 16+ for ATVs, varies by state)",
      "Include specific trail boundary descriptions for your property",
      "Add a damage fee schedule so renters know costs upfront",
      "Require photo ID and record driver's license numbers",
      "Consider requiring a separate passenger waiver for UTV passengers",
    ],
    faqItems: [
      { question: "Is an ATV waiver enough to protect my business?", answer: "A well-drafted waiver significantly reduces your litigation risk but cannot eliminate it entirely. Waivers protect against ordinary negligence — not gross negligence or willful misconduct. Combine waivers with proper insurance coverage." },
      { question: "What's the minimum age for ATV renters?", answer: "This varies by state — many states set 16 as the minimum for ATV operation. Include your state's age requirement in your waiver template and verify age with photo ID." },
      { question: "Should passengers sign separately?", answer: "Yes, especially for UTVs with passenger seats. Each rider should sign their own waiver acknowledging the risks specific to their role (driver vs. passenger)." },
      { question: "Do I need to verify riding experience?", answer: "Include an experience declaration and safety briefing requirement. For inexperienced riders, consider requiring a supervised orientation ride before solo rental." },
    ],
    relatedIndustry: "atv-rental-waivers",
    relatedTemplates: ["equipment-rental-waiver-template", "jet-ski-rental-waiver-template"],
  },
  {
    slug: "boat-rental-waiver-template",
    name: "Boat Rental Waiver",
    metaTitle: "Free Boat Rental Waiver Template — Marina Liability Protection",
    metaDescription: "Free boat rental waiver template for marina operators. Includes drowning risk, boating experience declaration, and Coast Guard compliance language.",
    h1: "Boat Rental Waiver Template",
    intro: "This boat rental waiver template addresses the unique liability concerns of marina operators, pontoon rental companies, and fishing charter businesses. It covers watercraft operation risks, passenger safety, and equipment responsibility for vessels.",
    risks: ["Drowning or near-drowning", "Collision with vessels, docks, or submerged objects", "Falls overboard", "Propeller injuries", "Weather-related hazards (wind, waves, lightning)", "Carbon monoxide exposure on enclosed vessels"],
    clauses: [
      { title: "Assumption of Risk", text: "Participant acknowledges that boating involves inherent risks including drowning, collision, capsizing, and exposure to weather. Participant voluntarily assumes all risks associated with boat rental and operation." },
      { title: "Release of Liability", text: "Participant releases [Business Name] from all claims arising from boat rental, except for gross negligence or willful misconduct." },
      { title: "Operator Qualification", text: "Participant confirms they possess a valid boater safety certificate or equivalent qualification as required by state law, and have sufficient experience to safely operate the rented vessel." },
      { title: "Navigation Rules Compliance", text: "Participant agrees to comply with all US Coast Guard navigation rules, state boating laws, and posted marina rules including speed limits, no-wake zones, and restricted areas." },
      { title: "Life Jacket Acknowledgment", text: "Participant acknowledges that USCG-approved life jackets have been provided for all passengers. Participant understands that children under [age per state law] are required by law to wear a life jacket at all times." },
      { title: "Vessel Return Condition", text: "Participant agrees to return the vessel in the condition received, at the designated time and location. Participant is responsible for damage, grounding, or loss of the vessel and its equipment." },
    ],
    customFields: ["Full legal name", "Boater safety certificate number", "Prior boating experience level", "Number of passengers", "Vessel assigned and hull number", "Fuel level at departure/return", "Emergency contact", "Trip plan (destination/area)"],
    bestPractices: [
      "Verify boater safety certifications before rental — many states require them",
      "Include specific navigation hazards at your marina/lake/bay",
      "Add a fuel policy clause (return at same level, charge for refueling)",
      "Include a weather cancellation and early return policy",
      "For fishing boats, add specific fishing equipment liability language",
      "Add alcohol consumption prohibition while operating the vessel",
    ],
    faqItems: [
      { question: "Do renters need a boating license?", answer: "Requirements vary by state — many states require a boater safety certificate for motorboat operation. Include the requirement in your waiver and verify certification before handing over keys." },
      { question: "Does this cover all passengers?", answer: "Each adult passenger should ideally sign their own waiver. At minimum, the primary renter signs acknowledging responsibility for all passengers. For families, include a guardian section for minors." },
      { question: "What about fishing charter operations?", answer: "Add clauses covering fishing equipment risks, captain's authority, and catch-and-release policies. For captained charters, liability dynamics are different — consult your maritime attorney." },
      { question: "Should I include fuel and damage deposits?", answer: "Yes — reference deposit amounts and damage assessment procedures in your waiver. This sets clear financial expectations and strengthens your claim for equipment damage." },
    ],
    relatedIndustry: "boat-rental-waivers",
    relatedTemplates: ["jet-ski-rental-waiver-template", "kayak-rental-waiver-template"],
  },
  {
    slug: "bounce-house-rental-waiver-template",
    name: "Bounce House Waiver",
    metaTitle: "Free Bounce House Rental Waiver Template — Party Liability Protection",
    metaDescription: "Free bounce house and inflatable rental waiver template. Covers jumping injuries, age restrictions, capacity limits, and supervision requirements.",
    h1: "Bounce House Rental Waiver Template",
    intro: "Bounce house and inflatable rental businesses face unique liability challenges — most participants are children, supervision is critical, and injuries from jumping and collision are common. This template addresses the specific risks of inflatable rental operations.",
    risks: ["Falls and impact injuries from bouncing", "Collision between participants", "Improper entry or exit injuries", "Wind-related incidents (tipping, deflation)", "Overcrowding and capacity-related injuries", "Allergic reactions to materials"],
    clauses: [
      { title: "Assumption of Risk", text: "Parent/Guardian acknowledges that inflatable use involves inherent risks including falls, collisions, and impact injuries. Parent/Guardian voluntarily assumes all risks on behalf of the minor participant(s)." },
      { title: "Release of Liability", text: "Parent/Guardian releases [Business Name] from claims arising from inflatable use, except for gross negligence." },
      { title: "Supervision Responsibility", text: "Parent/Guardian agrees to provide adult supervision at all times while children are using the inflatable equipment. [Business Name] is not responsible for supervision of participants." },
      { title: "Safety Rules Acknowledgment", text: "Parent/Guardian has read and agrees to enforce all safety rules including: no shoes, no rough play, maximum capacity limits, age/size groupings, and no food or drink on the inflatable." },
      { title: "Weather and Setup Conditions", text: "Parent/Guardian acknowledges that inflatables must be properly anchored and will not be used in winds exceeding 15 mph. Parent/Guardian agrees to follow all setup and takedown instructions provided." },
      { title: "Equipment Damage", text: "Renter is financially responsible for damage to rental equipment caused by misuse, failure to follow setup instructions, or failure to supervise participants." },
    ],
    customFields: ["Parent/Guardian full name", "Minor participant name(s) and ages", "Event date and location", "Equipment rented", "Event type (birthday, school, church, etc.)", "Number of expected participants", "Emergency contact", "Setup location type (grass, concrete, indoor)"],
    bestPractices: [
      "Always have the parent/guardian sign — minors cannot waive their own rights",
      "Include specific capacity limits per inflatable unit",
      "Add age/weight grouping rules to prevent size mismatches",
      "Include setup surface requirements (grass preferred, stakes needed)",
      "Add a wind speed cutoff policy and weather cancellation terms",
      "Include delivery/pickup time windows and overtime fees",
    ],
    faqItems: [
      { question: "Who should sign the waiver for a kids' party?", answer: "The parent or guardian of each child using the bounce house should sign. At minimum, the hosting parent should sign a waiver covering supervision responsibilities." },
      { question: "Does this protect me if a child gets hurt?", answer: "A well-drafted waiver significantly reduces your liability risk, but parental waivers for minors are not enforceable in all states. Combine waivers with proper insurance and safety protocols." },
      { question: "Should I include setup instructions in the waiver?", answer: "Yes — include key safety requirements (anchoring, surface type, distance from obstacles) in the waiver so the renter acknowledges responsibility for proper setup." },
      { question: "What about commercial events vs. residential?", answer: "Commercial events (school carnivals, church festivals) have different liability dynamics. Consider separate templates for residential and commercial rentals with appropriate insurance requirements." },
    ],
    relatedIndustry: "bounce-house-rental-waivers",
    relatedTemplates: ["party-equipment-rental-waiver-template", "event-rental-waiver-template"],
  },
  {
    slug: "equipment-rental-waiver-template",
    name: "Equipment Rental Waiver",
    metaTitle: "Free Equipment Rental Waiver Template — Tool & Machinery Liability",
    metaDescription: "Free equipment rental waiver template for tool, machinery, and construction equipment rental businesses. Covers operator qualification, damage, and injury risk.",
    h1: "Equipment Rental Waiver Template",
    intro: "Equipment rental businesses — from construction tools to power equipment — face significant liability exposure. This template covers operator qualification, equipment inspection, damage responsibility, and the specific safety risks associated with powered machinery.",
    risks: ["Injury from improper equipment operation", "Cuts, burns, and impact injuries", "Electrical hazards", "Equipment malfunction", "Property damage during use", "Hearing or eye injury from noise/debris"],
    clauses: [
      { title: "Assumption of Risk", text: "Renter acknowledges that operating rental equipment involves risks of injury, property damage, and equipment malfunction. Renter voluntarily assumes all risks associated with equipment rental and use." },
      { title: "Operator Qualification", text: "Renter confirms they are trained, qualified, and legally permitted to operate the rented equipment. Renter has read and understands all operating instructions and safety warnings." },
      { title: "Release of Liability", text: "Renter releases [Business Name] from claims arising from equipment rental and use, except for gross negligence or defective equipment known to [Business Name]." },
      { title: "Equipment Inspection", text: "Renter has inspected the equipment, confirms it is in satisfactory working condition, and agrees to report any defects immediately. Renter will not use equipment found to be defective." },
      { title: "Return Condition and Damage", text: "Renter agrees to return equipment in the condition received. Renter is financially responsible for damage, loss, or excessive wear beyond normal use." },
      { title: "Indemnification", text: "Renter agrees to indemnify [Business Name] from any third-party claims arising from Renter's use of equipment, including property damage and bodily injury claims." },
    ],
    customFields: ["Full legal name and company name", "Equipment rented (type, model, serial number)", "Rental period", "Intended use description", "Operator license/certification (if applicable)", "Proof of insurance", "Emergency contact", "Delivery address (if applicable)"],
    bestPractices: [
      "Require proof of relevant training or certification for powered equipment",
      "Include an equipment condition checklist that renters sign off on at pickup",
      "Add a 'permitted use only' clause — renters can't sublet or use for unintended purposes",
      "Include damage assessment procedures and fee schedules",
      "Require proof of liability insurance for high-value equipment",
      "Add a maintenance responsibility clause for long-term rentals",
    ],
    faqItems: [
      { question: "Should I require proof of training?", answer: "For powered equipment (chainsaws, excavators, aerial lifts), always require proof of training or certification. Include an operator qualification clause in your waiver." },
      { question: "What about damage disputes?", answer: "Document equipment condition at pickup and return with photos. Include a damage assessment procedure in your waiver and rental agreement." },
      { question: "Does this cover commercial job sites?", answer: "This template provides general liability protection. For commercial job site equipment, consider requiring the renter's business insurance certificate as additional protection." },
      { question: "Should equipment rental waivers be separate from rental agreements?", answer: "They can be combined, but the liability waiver language should be clearly separated and conspicuous — not buried within rental terms. Courts require waiver language to be prominent." },
    ],
    relatedIndustry: "equipment-rental-waivers",
    relatedTemplates: ["atv-rental-waiver-template", "bike-rental-waiver-template"],
  },
  {
    slug: "jet-ski-rental-waiver-template",
    name: "Jet Ski Rental Waiver",
    metaTitle: "Free Jet Ski Rental Waiver Template — PWC Liability Protection",
    metaDescription: "Free jet ski and personal watercraft rental waiver template. Covers high-speed water risks, operator age requirements, and state-specific PWC regulations.",
    h1: "Jet Ski Rental Waiver Template",
    intro: "Jet ski and personal watercraft (PWC) rentals are among the highest-liability water activities. This template addresses high-speed operation risks, operator qualification requirements, and the state-specific regulations that apply to PWC rental businesses.",
    risks: ["High-speed collision with other watercraft or objects", "Ejection and impact with water at speed", "Drowning or near-drowning", "Internal injuries from water forced entry", "Burns from jet propulsion", "Passenger injuries during sharp turns"],
    clauses: [
      { title: "Assumption of Risk", text: "Participant acknowledges that personal watercraft operation is a high-risk activity involving extreme speed, collision potential, and drowning risk. Participant voluntarily assumes all such risks." },
      { title: "Release of Liability", text: "Participant releases [Business Name] from all claims related to jet ski rental and operation, except for gross negligence." },
      { title: "Operator Age and Qualification", text: "Participant confirms they meet the minimum age requirement for PWC operation in this state and possess any required boater safety certification." },
      { title: "Speed and Operation Rules", text: "Participant agrees to operate the PWC at safe speeds, maintain required distances from other vessels and swimmers, and comply with all no-wake zone restrictions." },
      { title: "Life Jacket Requirement", text: "Participant acknowledges that USCG-approved life jackets must be worn at all times while operating or riding the PWC. This is both a company policy and a legal requirement in most states." },
      { title: "Damage and Loss", text: "Participant is financially responsible for damage to or loss of the PWC and all associated equipment during the rental period." },
    ],
    customFields: ["Full legal name and date of birth", "Boater safety certificate number", "Prior PWC experience", "PWC unit assigned", "Number of riders", "Rental duration", "Emergency contact", "State-issued ID number"],
    bestPractices: [
      "Verify minimum age compliance — most states require 16+ for solo PWC operation",
      "Include state-specific PWC regulations in your waiver",
      "Add a mandatory safety briefing completion checkbox",
      "Include specific restricted areas and boundary maps",
      "Require each rider (driver and passenger) to sign individually",
      "Add an alcohol/drug prohibition clause — required by federal law for vessel operation",
    ],
    faqItems: [
      { question: "What's the minimum age for jet ski renters?", answer: "Most states require operators to be at least 16, with some requiring 18 for rental without supervision. Check your state's PWC regulations and include the requirement in your waiver." },
      { question: "Should passengers sign too?", answer: "Yes. Each person who rides the jet ski — driver and passenger — should sign an individual waiver acknowledging the risks." },
      { question: "Do I need to verify boater safety certification?", answer: "Many states require PWC operators to have completed a boater safety course. Verify certification before rental and note the certificate number on the waiver." },
      { question: "What about damage from flipping?", answer: "Include a damage liability clause with estimated repair costs for common incidents (hull damage, propeller damage, towing fees). Set clear expectations before the rental begins." },
    ],
    relatedIndustry: "jet-ski-rental-waivers",
    relatedTemplates: ["boat-rental-waiver-template", "paddleboard-rental-waiver-template"],
  },
  {
    slug: "scooter-rental-waiver-template",
    name: "Scooter Rental Waiver",
    metaTitle: "Free Scooter Rental Waiver Template — Electric & Motor Scooter Liability",
    metaDescription: "Free scooter rental waiver template for electric and motor scooter operators. Covers traffic risk, helmet policy, and equipment damage liability.",
    h1: "Scooter Rental Waiver Template",
    intro: "Electric and motor scooter rentals are booming in tourist areas and urban centers. This template covers traffic risks, speed limitations, helmet requirements, and the unique liability considerations for scooter rental businesses.",
    risks: ["Collision with vehicles or pedestrians", "Falls on uneven pavement or obstacles", "Speed-related injuries", "Battery or electrical malfunction", "Visibility issues in traffic", "Theft or vandalism of rental equipment"],
    clauses: [
      { title: "Assumption of Risk", text: "Participant acknowledges that scooter operation on public roads involves inherent risks including collision, falls, and traffic hazards. Participant voluntarily assumes all risks." },
      { title: "Release of Liability", text: "Participant releases [Business Name] from claims arising from scooter rental and use, except for gross negligence." },
      { title: "Helmet and Safety Gear", text: "Participant acknowledges the offer of a helmet and understands the risks of operating a scooter without one. Participant agrees to wear appropriate footwear (closed-toe shoes)." },
      { title: "Traffic Law Compliance", text: "Participant agrees to obey all traffic laws, ride in designated areas, and not operate the scooter on sidewalks where prohibited." },
      { title: "Speed and Operation Limits", text: "Participant agrees to operate within posted speed limits and not attempt to modify or override speed limiters on electric scooters." },
      { title: "Equipment Responsibility", text: "Participant is responsible for the scooter during the rental period including damage, theft, and loss." },
    ],
    customFields: ["Full legal name", "Driver's license or ID number", "Height and weight (for scooter assignment)", "Helmet acceptance/decline checkbox", "Rental duration", "Scooter unit number", "Emergency contact", "Prior scooter experience"],
    bestPractices: [
      "Include local regulations specific to electric scooter operation in your area",
      "Add a photo of the renter with the scooter at checkout for identification",
      "Include geofence or restricted area boundaries if applicable",
      "Add a charging/battery return policy for electric scooters",
      "Include parking instructions and prohibited parking areas",
      "Consider requiring a credit card hold for damage deposits",
    ],
    faqItems: [
      { question: "Does this cover electric scooters and gas scooters?", answer: "The core liability language applies to both. For gas-powered scooters, add clauses about fuel handling and engine heat. For electric scooters, address battery safety and speed limiter compliance." },
      { question: "Are helmet requirements included?", answer: "Yes — the template includes a helmet acknowledgment clause. Requirements vary by jurisdiction, but always offer helmets and document the renter's choice." },
      { question: "What about tourist rental operations?", answer: "Add route recommendations, local traffic rules, and area-specific hazards. Consider including a basic navigation/route briefing as part of your checkout process." },
      { question: "Should I require a driver's license?", answer: "Many jurisdictions require a valid driver's license for motorized scooter operation. Include this requirement and verify before rental." },
    ],
    relatedIndustry: "scooter-rental-waivers",
    relatedTemplates: ["bike-rental-waiver-template", "equipment-rental-waiver-template"],
  },
  {
    slug: "rv-rental-waiver-template",
    name: "RV Rental Waiver",
    metaTitle: "Free RV Rental Waiver Template — Motorhome Liability Protection",
    metaDescription: "Free RV and motorhome rental waiver template. Covers driving qualification, interior equipment, generator safety, and campsite liability.",
    h1: "RV Rental Waiver Template",
    intro: "RV and motorhome rental businesses face liability for both vehicle operation and living space equipment. This template covers driving qualification, interior safety (gas appliances, generators), campsite setup, and the long-term rental considerations unique to RV operations.",
    risks: ["Vehicle collision or rollover (oversized vehicle)", "Carbon monoxide from generators or propane systems", "Propane leak or fire hazard", "Low clearance and bridge strikes", "Sewer system handling hazards", "Slide-out mechanism injuries"],
    clauses: [
      { title: "Assumption of Risk", text: "Renter acknowledges that operating a recreational vehicle involves unique risks including oversized vehicle handling, propane systems, generator operation, and campsite setup. Renter voluntarily assumes all such risks." },
      { title: "Driver Qualification", text: "Renter confirms they possess a valid driver's license appropriate for the vehicle class, are at least 25 years of age, and have sufficient driving experience to safely operate the RV." },
      { title: "Release of Liability", text: "Renter releases [Business Name] from claims arising from RV rental and use, except for gross negligence or known mechanical defects." },
      { title: "Vehicle Systems Training", text: "Renter has received training on all vehicle systems including propane, generator, water/sewer, slide-outs, and electrical. Renter will follow all operating instructions." },
      { title: "Mileage and Territory", text: "Renter agrees to operate the RV within designated territories and return it within the agreed mileage allowance. Excess mileage charges apply per the rental agreement." },
      { title: "Interior and Exterior Damage", text: "Renter is responsible for all damage to the RV interior and exterior beyond normal wear, including furnishings, appliances, and exterior body damage." },
    ],
    customFields: ["Full legal name(s) of all authorized drivers", "Driver's license number and state", "Insurance information", "Planned travel route/destinations", "Rental dates and mileage allowance", "Number of occupants", "Pet declaration", "Towing equipment (if applicable)"],
    bestPractices: [
      "Require a comprehensive vehicle walkthrough with documented checklist",
      "Include minimum driver age (typically 25) and license class requirements",
      "Add carbon monoxide and propane safety acknowledgments",
      "Include altitude and mountain driving warnings if applicable to your area",
      "Add a pet policy (allowed/not, cleaning fees)",
      "Include generator quiet hours and campsite etiquette rules",
    ],
    faqItems: [
      { question: "What driver's license do renters need for an RV?", answer: "Most states allow Class C RVs (under 26,000 lbs) with a standard driver's license. Larger Class A motorhomes may require a non-commercial Class B license in some states. Verify requirements for your specific vehicles." },
      { question: "Should I include interior damage in the waiver?", answer: "Absolutely. RVs have extensive interior equipment (appliances, furnishings, bathroom fixtures) that can be damaged. Include a condition report and walkthrough documentation." },
      { question: "What about propane and generator safety?", answer: "Include specific clauses about propane system operation, CO detector requirements, and generator ventilation. These are critical safety items that should be covered in both the waiver and a separate safety briefing." },
      { question: "Do I need separate insurance for renters?", answer: "Most RV rental businesses provide or require insurance coverage. Reference your insurance policy in the waiver and clarify the renter's deductible and coverage limitations." },
    ],
    relatedIndustry: "rv-rental-waivers",
    relatedTemplates: ["boat-rental-waiver-template", "equipment-rental-waiver-template"],
  },
  {
    slug: "paddleboard-rental-waiver-template",
    name: "Paddleboard Rental Waiver",
    metaTitle: "Free Paddleboard (SUP) Rental Waiver Template — Water Activity Liability",
    metaDescription: "Free stand-up paddleboard rental waiver template. Covers water safety, balance risks, wind/current hazards, and leash/PFD requirements.",
    h1: "Paddleboard (SUP) Rental Waiver Template",
    intro: "Stand-up paddleboarding has exploded in popularity, and with it, SUP rental businesses. This template covers the specific risks of paddleboarding — balance challenges, wind and current hazards, and the importance of leash and PFD usage.",
    risks: ["Falling from the board into water", "Drowning or near-drowning", "Wind or current carrying the board away", "Collision with swimmers, boats, or objects", "Board strike injuries (to rider or others)", "Sunburn and heat exhaustion"],
    clauses: [
      { title: "Assumption of Risk", text: "Participant acknowledges that stand-up paddleboarding involves risks including falling, drowning, wind/current exposure, and collision. Participant voluntarily assumes all risks." },
      { title: "Release of Liability", text: "Participant releases [Business Name] from claims arising from paddleboard rental and use, except for gross negligence." },
      { title: "Swimming Ability", text: "Participant confirms they are a competent swimmer capable of swimming at least 100 meters in open water without a flotation device." },
      { title: "Leash and PFD Requirements", text: "Participant agrees to wear the provided leash at all times and to carry a USCG-approved PFD as required by local regulations." },
      { title: "Weather and Conditions", text: "Participant acknowledges that water and weather conditions can change rapidly. Participant agrees to return to shore if conditions deteriorate." },
      { title: "Equipment Care", text: "Participant agrees to handle the paddleboard and paddle with care, avoid dragging over rocks or concrete, and return equipment in the condition received." },
    ],
    customFields: ["Full legal name", "Swimming ability level", "Prior SUP experience", "Board size assigned", "Rental duration", "Emergency contact", "Any medical conditions", "PFD and leash acknowledgment"],
    bestPractices: [
      "Include a swimming ability requirement — SUP renters must be able to swim",
      "Add wind speed limits and conditions under which rentals will be paused",
      "Include a leash usage requirement — critical safety equipment for SUP",
      "Add specific local water hazards (currents, boat channels, shallow areas)",
      "Include a sun exposure and hydration warning",
      "For SUP yoga or fitness classes, add specific class-related risk language",
    ],
    faqItems: [
      { question: "Is a paddleboard waiver different from a kayak waiver?", answer: "The core liability language is similar, but SUP waivers should address balance-specific risks, leash requirements, and the unique challenge of standing on water. The risk profile is different from seated paddling." },
      { question: "Should I require PFDs for paddleboarders?", answer: "USCG considers SUPs as vessels — PFDs must be on board. Many states require PFD wear. Include this requirement in your waiver and provide PFDs with every rental." },
      { question: "What about SUP tours and group classes?", answer: "Add guide/instructor compliance clauses and group-specific rules. For yoga SUP, include additional fitness-related risk language." },
      { question: "Do kids need special waiver language?", answer: "Yes — include a guardian signature section. Add age-appropriate board assignment requirements and consider mandatory PFD wear for all minors." },
    ],
    relatedIndustry: "paddleboard-rental-waivers",
    relatedTemplates: ["kayak-rental-waiver-template", "surfboard-rental-waiver-template"],
  },
];

import { extraTemplatePages } from "./waiver-template-pages-extra";

export const allWaiverTemplatePages: WaiverTemplatePage[] = [...waiverTemplatePages, ...extraTemplatePages];

export function getWaiverTemplatePage(slug: string): WaiverTemplatePage | undefined {
  return allWaiverTemplatePages.find((p) => p.slug === slug);
}
