project_id = "llsgwfzoutdpgrgtcbif"

[functions]
  [functions.ask-waiver-question]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.marketplace-webhook]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = false
  [functions.send-envelope-notification]
    verify_jwt = false
  [functions.send-team-invite-email]
    verify_jwt = false
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.send-welcome-email]
    verify_jwt = false
  [functions.waiverflow-api]
    verify_jwt = false
