project_id = "llsgwfzoutdpgrgtcbif"

[functions.send-team-invite-email]
verify_jwt = false

[functions.send-envelope-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.marketplace-webhook]
verify_jwt = false

[functions.waiverflow-api]
verify_jwt = false