import type { TranslationKeys } from "./en";

export const ar: TranslationKeys = {
  common: { save: "حفظ", cancel: "إلغاء", delete: "حذف", loading: "جاري التحميل...", search: "بحث", noResults: "لم يتم العثور على نتائج", signOut: "تسجيل الخروج", upgrade: "ترقية" },
  nav: { dashboard: "لوحة التحكم", templates: "القوالب", envelopes: "المغلفات", analytics: "التحليلات", team: "الفريق", apiKeys: "مفاتيح API", webhooks: "Webhooks", pricing: "الأسعار", settings: "الإعدادات" },
  dashboard: { title: "لوحة التحكم", subtitle: "نظرة عامة على عمليات إخلاء المسؤولية", setupRequired: "قم بإعداد مؤسستك للبدء", templates: "القوالب", sent: "مُرسل", completed: "مكتمل", pending: "قيد الانتظار" },
  envelopes: { title: "المغلفات", subtitle: "تتبع جميع توقيعات إخلاء المسؤولية", newEnvelope: "مغلف جديد", bulkSend: "إرسال جماعي", searchPlaceholder: "البحث بالبريد الإلكتروني أو الاسم أو رقم الحجز...", allStatuses: "جميع الحالات", noEnvelopes: "لم يتم العثور على مغلفات" },
  signing: { title: "إخلاء المسؤولية", subtitle: "يرجى قراءة إخلاء المسؤولية أدناه بعناية، ثم قم بالتمرير إلى الأسفل وأكمل توقيعك.", scrollToEnd: "قم بالتمرير إلى النهاية للمتابعة", fullName: "الاسم القانوني الكامل", initials: "الأحرف الأولى", signature: "التوقيع", drawSignature: "ارسم توقيعك أعلاه", clearSignature: "مسح التوقيع", agreeText: "أوافق على توقيع هذا المستند إلكترونيًا وأقر بأن هذا يشكل توقيعًا ملزمًا قانونيًا.", submit: "إنهاء وإرسال", submitting: "جاري التوقيع...", submitDisclaimer: 'بالنقر على "إنهاء وإرسال"، فإنك توافق على الشروط أعلاه وتوافق على التوقيع الإلكتروني.', success: "تم توقيع إخلاء المسؤولية", successMessage: "شكرًا لك، {name}. تم تسجيل إخلاء المسؤولية الموقع.", notFound: "الرابط غير موجود", notFoundMessage: "رابط التوقيع هذا غير صالح أو منتهي الصلاحية.", canceled: "تم إلغاء إخلاء المسؤولية", canceledMessage: "تم إلغاء إخلاء المسؤولية هذا ولا يمكن توقيعه بعد الآن." },
  settings: { title: "الإعدادات", subtitle: "إدارة مؤسستك", orgName: "اسم المؤسسة", retention: "مدة حفظ PDF (سنوات)", createOrg: "إنشاء مؤسسة", saveChanges: "حفظ التغييرات" },
  team: { title: "أعضاء الفريق", subtitle: "إدارة فريقك ودعوة أعضاء جدد", invite: "دعوة عضو", sendInvite: "إرسال الدعوة", pendingInvites: "الدعوات المعلقة", currentMembers: "الأعضاء الحاليون", you: "أنت" },
  analytics: { title: "التحليلات", subtitle: "أداء إخلاء المسؤولية ورؤى الاستخدام", exportCsv: "تصدير CSV", totalEnvelopes: "إجمالي المغلفات", completionRate: "معدل الإكمال", monthlyUsage: "الاستخدام الشهري", waiversOverTime: "إخلاءات المسؤولية عبر الزمن (30 يومًا)", statusBreakdown: "توزيع الحالات" },
  pricing: { title: "اختر خطتك", subtitle: "ادفع مقابل ما تستخدمه — كل خطة تشمل الزيادة بمعدل {rate}/إخلاء مسؤولية", manageSubscription: "إدارة الاشتراك", currentPlan: "الخطة الحالية", getStarted: "ابدأ", switchPlan: "تغيير الخطة", downgrade: "تخفيض" },
};
