import type { TranslationKeys } from "./en";

export const de: TranslationKeys = {
  common: { save: "Speichern", cancel: "Abbrechen", delete: "Löschen", loading: "Laden...", search: "Suchen", noResults: "Keine Ergebnisse gefunden", signOut: "Abmelden", upgrade: "Upgrade" },
  nav: { dashboard: "Dashboard", templates: "Vorlagen", envelopes: "Umschläge", analytics: "Analytik", team: "Team", apiKeys: "API-Schlüssel", webhooks: "Webhooks", pricing: "Preise", settings: "Einstellungen" },
  dashboard: { title: "Dashboard", subtitle: "Überblick über Ihre Haftungsverzichtserklärungen", setupRequired: "Richten Sie Ihre Organisation ein, um zu beginnen", templates: "Vorlagen", sent: "Gesendet", completed: "Abgeschlossen", pending: "Ausstehend" },
  envelopes: { title: "Umschläge", subtitle: "Alle Unterschriften verfolgen", newEnvelope: "Neuer Umschlag", bulkSend: "Massenversand", searchPlaceholder: "Nach E-Mail, Name, Buchungs-ID suchen...", allStatuses: "Alle Status", noEnvelopes: "Keine Umschläge gefunden" },
  signing: { title: "Haftungsverzichtserklärung", subtitle: "Bitte lesen Sie die Verzichtserklärung sorgfältig durch, scrollen Sie nach unten und vervollständigen Sie Ihre Unterschrift.", scrollToEnd: "Scrollen Sie bis zum Ende, um fortzufahren", fullName: "Vollständiger Name", initials: "Initialen", signature: "Unterschrift", drawSignature: "Zeichnen Sie Ihre Unterschrift oben", clearSignature: "Unterschrift löschen", agreeText: "Ich stimme zu, dieses Dokument elektronisch zu unterzeichnen und erkenne an, dass dies eine rechtsverbindliche Unterschrift darstellt.", submit: "Abschließen & Absenden", submitting: "Wird unterschrieben...", submitDisclaimer: 'Durch Klicken auf "Abschließen & Absenden" stimmen Sie den obigen Bedingungen zu.', success: "Verzichtserklärung Unterzeichnet", successMessage: "Danke, {name}. Ihre unterzeichnete Verzichtserklärung wurde erfasst.", notFound: "Link Nicht Gefunden", notFoundMessage: "Dieser Signierlink ist ungültig oder abgelaufen.", canceled: "Verzichtserklärung Storniert", canceledMessage: "Diese Verzichtserklärung wurde storniert und kann nicht mehr unterzeichnet werden." },
  settings: { title: "Einstellungen", subtitle: "Verwalten Sie Ihre Organisation", orgName: "Organisationsname", retention: "PDF-Aufbewahrung (Jahre)", createOrg: "Organisation Erstellen", saveChanges: "Änderungen Speichern" },
  team: { title: "Teammitglieder", subtitle: "Verwalten Sie Ihr Team und laden Sie neue Mitglieder ein", invite: "Mitglied Einladen", sendInvite: "Einladung Senden", pendingInvites: "Ausstehende Einladungen", currentMembers: "Aktuelle Mitglieder", you: "Sie" },
  analytics: { title: "Analytik", subtitle: "Leistung und Nutzungseinblicke", exportCsv: "CSV Exportieren", totalEnvelopes: "Gesamt Umschläge", completionRate: "Abschlussrate", monthlyUsage: "Monatliche Nutzung", waiversOverTime: "Verzichtserklärungen im Zeitverlauf (30 Tage)", statusBreakdown: "Statusaufschlüsselung" },
  pricing: { title: "Wählen Sie Ihren Plan", subtitle: "Zahlen Sie nur, was Sie nutzen — jeder Plan enthält Überschuss bei {rate}/Verzichtserklärung", manageSubscription: "Abonnement Verwalten", currentPlan: "Aktueller Plan", getStarted: "Loslegen", switchPlan: "Plan Wechseln", downgrade: "Herabstufen" },
};
