import type { TranslationKeys } from "./en";

export const hi: TranslationKeys = {
  common: { save: "सहेजें", cancel: "रद्द करें", delete: "हटाएं", loading: "लोड हो रहा है...", search: "खोजें", noResults: "कोई परिणाम नहीं मिला", signOut: "लॉग आउट", upgrade: "अपग्रेड" },
  nav: { dashboard: "डैशबोर्ड", templates: "टेम्पलेट", envelopes: "लिफाफे", analytics: "विश्लेषण", team: "टीम", apiKeys: "API कुंजियाँ", webhooks: "Webhooks", pricing: "मूल्य निर्धारण", settings: "सेटिंग्स" },
  dashboard: { title: "डैशबोर्ड", subtitle: "आपके छूट संचालन का अवलोकन", setupRequired: "शुरू करने के लिए अपनी संस्था सेट करें", templates: "टेम्पलेट", sent: "भेजा गया", completed: "पूर्ण", pending: "लंबित" },
  envelopes: { title: "लिफाफे", subtitle: "सभी छूट हस्ताक्षरों को ट्रैक करें", newEnvelope: "नया लिफाफा", bulkSend: "बल्क भेजें", searchPlaceholder: "ईमेल, नाम, बुकिंग ID से खोजें...", allStatuses: "सभी स्थितियाँ", noEnvelopes: "कोई लिफाफा नहीं मिला" },
  signing: { title: "दायित्व छूट", subtitle: "कृपया नीचे दी गई छूट को ध्यान से पढ़ें, नीचे तक स्क्रॉल करें और अपना हस्ताक्षर पूरा करें।", scrollToEnd: "जारी रखने के लिए अंत तक स्क्रॉल करें", fullName: "पूरा कानूनी नाम", initials: "आद्याक्षर", signature: "हस्ताक्षर", drawSignature: "ऊपर अपना हस्ताक्षर बनाएं", clearSignature: "हस्ताक्षर मिटाएं", agreeText: "मैं इस दस्तावेज़ पर इलेक्ट्रॉनिक रूप से हस्ताक्षर करने के लिए सहमत हूं और स्वीकार करता हूं कि यह कानूनी रूप से बाध्यकारी हस्ताक्षर है।", submit: "समाप्त करें और सबमिट करें", submitting: "हस्ताक्षर हो रहा है...", submitDisclaimer: '"समाप्त करें और सबमिट करें" पर क्लिक करके, आप उपरोक्त शर्तों से सहमत हैं।', success: "छूट पर हस्ताक्षर हो गया", successMessage: "धन्यवाद, {name}। आपकी हस्ताक्षरित छूट दर्ज कर ली गई है।", notFound: "लिंक नहीं मिला", notFoundMessage: "यह हस्ताक्षर लिंक अमान्य है या समाप्त हो गया है।", canceled: "छूट रद्द", canceledMessage: "यह छूट रद्द कर दी गई है और अब हस्ताक्षर नहीं किया जा सकता।" },
  settings: { title: "सेटिंग्स", subtitle: "अपनी संस्था प्रबंधित करें", orgName: "संस्था का नाम", retention: "PDF प्रतिधारण (वर्ष)", createOrg: "संस्था बनाएं", saveChanges: "परिवर्तन सहेजें" },
  team: { title: "टीम सदस्य", subtitle: "अपनी टीम प्रबंधित करें और नए सदस्यों को आमंत्रित करें", invite: "सदस्य आमंत्रित करें", sendInvite: "आमंत्रण भेजें", pendingInvites: "लंबित आमंत्रण", currentMembers: "वर्तमान सदस्य", you: "आप" },
  analytics: { title: "विश्लेषण", subtitle: "छूट प्रदर्शन और उपयोग अंतर्दृष्टि", exportCsv: "CSV निर्यात", totalEnvelopes: "कुल लिफाफे", completionRate: "पूर्णता दर", monthlyUsage: "मासिक उपयोग", waiversOverTime: "समय के साथ छूट (30 दिन)", statusBreakdown: "स्थिति विभाजन" },
  pricing: { title: "अपनी योजना चुनें", subtitle: "जो उपयोग करें उसके लिए भुगतान करें — हर योजना में {rate}/छूट पर अतिरिक्त शामिल है", manageSubscription: "सदस्यता प्रबंधित करें", currentPlan: "वर्तमान योजना", getStarted: "शुरू करें", switchPlan: "योजना बदलें", downgrade: "डाउनग्रेड" },
};
