import type { TranslationKeys } from "./en";

export const it: TranslationKeys = {
  common: { save: "Salva", cancel: "Annulla", delete: "Elimina", loading: "Caricamento...", search: "Cerca", noResults: "Nessun risultato trovato", signOut: "Esci", upgrade: "Aggiorna" },
  nav: { dashboard: "Dashboard", templates: "Modelli", envelopes: "Buste", analytics: "Analisi", team: "Team", apiKeys: "Chiavi API", webhooks: "Webhooks", pricing: "Prezzi", settings: "Impostazioni" },
  dashboard: { title: "Dashboard", subtitle: "Panoramica delle operazioni di esonero", setupRequired: "Configura la tua organizzazione per iniziare", templates: "Modelli", sent: "Inviati", completed: "Completati", pending: "In attesa" },
  envelopes: { title: "Buste", subtitle: "Traccia tutte le firme di esonero", newEnvelope: "Nuova Busta", bulkSend: "Invio Massivo", searchPlaceholder: "Cerca per email, nome, ID prenotazione...", allStatuses: "Tutti gli stati", noEnvelopes: "Nessuna busta trovata" },
  signing: { title: "Esonero di Responsabilità", subtitle: "Leggi attentamente l'esonero qui sotto, scorri fino in fondo e completa la tua firma.", scrollToEnd: "Scorri fino alla fine per continuare", fullName: "Nome Legale Completo", initials: "Iniziali", signature: "Firma", drawSignature: "Disegna la tua firma sopra", clearSignature: "Cancella firma", agreeText: "Accetto di firmare questo documento elettronicamente e riconosco che ciò costituisce una firma legalmente vincolante.", submit: "Concludi e Invia", submitting: "Firma in corso...", submitDisclaimer: 'Cliccando "Concludi e Invia", accetti i termini sopra e acconsenti alla firma elettronica.', success: "Esonero Firmato", successMessage: "Grazie, {name}. Il tuo esonero firmato è stato registrato.", notFound: "Link Non Trovato", notFoundMessage: "Questo link di firma non è valido o è scaduto.", canceled: "Esonero Annullato", canceledMessage: "Questo esonero è stato annullato e non può più essere firmato." },
  settings: { title: "Impostazioni", subtitle: "Gestisci la tua organizzazione", orgName: "Nome Organizzazione", retention: "Conservazione PDF (anni)", createOrg: "Crea Organizzazione", saveChanges: "Salva Modifiche" },
  team: { title: "Membri del Team", subtitle: "Gestisci il tuo team e invita nuovi membri", invite: "Invita Membro", sendInvite: "Invia Invito", pendingInvites: "Inviti in Attesa", currentMembers: "Membri Attuali", you: "Tu" },
  analytics: { title: "Analisi", subtitle: "Prestazioni e statistiche di utilizzo degli esoneri", exportCsv: "Esporta CSV", totalEnvelopes: "Totale Buste", completionRate: "Tasso di Completamento", monthlyUsage: "Utilizzo Mensile", waiversOverTime: "Esoneri nel Tempo (30 giorni)", statusBreakdown: "Ripartizione per Stato" },
  pricing: { title: "Scegli il Tuo Piano", subtitle: "Paga solo quello che usi — ogni piano include eccedenza a {rate}/esonero", manageSubscription: "Gestisci Abbonamento", currentPlan: "Piano Attuale", getStarted: "Inizia", switchPlan: "Cambia Piano", downgrade: "Declassa" },
};
