import type { TranslationKeys } from "./en";

export const pt: TranslationKeys = {
  common: { save: "Salvar", cancel: "Cancelar", delete: "Excluir", loading: "Carregando...", search: "Pesquisar", noResults: "Nenhum resultado encontrado", signOut: "Sair", upgrade: "Atualizar" },
  nav: { dashboard: "Painel", templates: "Modelos", envelopes: "Envelopes", analytics: "Análises", team: "Equipe", apiKeys: "Chaves API", webhooks: "Webhooks", pricing: "Preços", settings: "Configurações" },
  dashboard: { title: "Painel", subtitle: "Visão geral das suas operações de isenção", setupRequired: "Configure sua organização para começar", templates: "Modelos", sent: "Enviados", completed: "Concluídos", pending: "Pendentes" },
  envelopes: { title: "Envelopes", subtitle: "Rastreie todas as assinaturas de isenção", newEnvelope: "Novo Envelope", bulkSend: "Envio em Massa", searchPlaceholder: "Pesquisar por email, nome, ID de reserva...", allStatuses: "Todos os status", noEnvelopes: "Nenhum envelope encontrado" },
  signing: { title: "Termo de Responsabilidade", subtitle: "Por favor, leia o termo abaixo cuidadosamente, role até o final e complete sua assinatura.", scrollToEnd: "Role até o final para continuar", fullName: "Nome Legal Completo", initials: "Iniciais", signature: "Assinatura", drawSignature: "Desenhe sua assinatura acima", clearSignature: "Limpar assinatura", agreeText: "Concordo em assinar este documento eletronicamente e reconheço que isso constitui uma assinatura legalmente vinculante.", submit: "Finalizar e Enviar", submitting: "Assinando...", submitDisclaimer: 'Ao clicar em "Finalizar e Enviar", você concorda com os termos acima e consente com a assinatura eletrônica.', success: "Termo Assinado", successMessage: "Obrigado, {name}. Seu termo assinado foi registrado.", notFound: "Link Não Encontrado", notFoundMessage: "Este link de assinatura é inválido ou expirou.", canceled: "Termo Cancelado", canceledMessage: "Este termo foi cancelado e não pode mais ser assinado." },
  settings: { title: "Configurações", subtitle: "Gerencie sua organização", orgName: "Nome da Organização", retention: "Retenção de PDF (anos)", createOrg: "Criar Organização", saveChanges: "Salvar Alterações" },
  team: { title: "Membros da Equipe", subtitle: "Gerencie sua equipe e convide novos membros", invite: "Convidar Membro", sendInvite: "Enviar Convite", pendingInvites: "Convites Pendentes", currentMembers: "Membros Atuais", you: "Você" },
  analytics: { title: "Análises", subtitle: "Desempenho e insights de uso de isenções", exportCsv: "Exportar CSV", totalEnvelopes: "Total de Envelopes", completionRate: "Taxa de Conclusão", monthlyUsage: "Uso Mensal", waiversOverTime: "Isenções ao Longo do Tempo (30 dias)", statusBreakdown: "Divisão por Status" },
  pricing: { title: "Escolha Seu Plano", subtitle: "Pague pelo que usar — cada plano inclui excedente a {rate}/isenção", manageSubscription: "Gerenciar Assinatura", currentPlan: "Plano Atual", getStarted: "Começar", switchPlan: "Trocar Plano", downgrade: "Rebaixar" },
};
