// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-waivers.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function requireOrgId(supabase, userId) {
  if (!userId) throw new Error("Authenticated caller required");
  const { data, error } = await supabase.from("profiles").select("org_id").eq("user_id", userId).maybeSingle();
  if (error) throw new Error(error.message);
  if (!data?.org_id) throw new Error("No organization found for this account");
  return data.org_id;
}

// src/lib/mcp/tools/list-waivers.ts
var toWaiverJson = (row) => ({
  id: String(row.id),
  status: String(row.status),
  signer_name: row.signer_name ?? null,
  signer_email: String(row.signer_email),
  is_group_waiver: Boolean(row.is_group_waiver),
  created_at: String(row.created_at),
  signed_at: row.signed_at ?? null,
  expires_at: row.expires_at ?? null,
  booking_id: row.booking_id ?? null
});
var list_waivers_default = defineTool({
  name: "list_waivers",
  title: "List waivers",
  description: "List the signed-in account's waivers (envelopes), newest first, optionally filtered by status or signer email.",
  inputSchema: {
    status: z.enum(["draft", "sent", "viewed", "completed", "expired", "canceled"]).optional().describe("Only return waivers with this status."),
    signer_email: z.string().trim().optional().describe("Only return waivers for this signer email."),
    limit: z.number().int().min(1).max(100).optional().describe("Maximum waivers to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, signer_email, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const orgId = await requireOrgId(supabase, ctx.getUserId());
    let query = supabase.from("envelopes").select(
      "id,status,signer_name,signer_email,is_group_waiver,created_at,signed_at,expires_at,booking_id"
    ).eq("org_id", orgId).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    if (signer_email) query = query.ilike("signer_email", signer_email);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const waivers = (data ?? []).map((row) => toWaiverJson(row));
    return {
      content: [{ type: "text", text: JSON.stringify(waivers, null, 2) }],
      structuredContent: { waivers }
    };
  }
});

// src/lib/mcp/tools/get-waiver.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_waiver_default = defineTool2({
  name: "get_waiver",
  title: "Get waiver",
  description: "Get one waiver by its id, including status, signer details, signing link, and recent activity events.",
  inputSchema: { waiver_id: z2.string().uuid().describe("The waiver (envelope) id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ waiver_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const orgId = await requireOrgId(supabase, ctx.getUserId());
    const { data, error } = await supabase.from("envelopes").select(
      "id,status,signer_name,signer_email,is_group_waiver,signing_token,group_token,created_at,signed_at,expires_at,booking_id,listing_id,credits_charged,pdf_storage_key"
    ).eq("org_id", orgId).eq("id", waiver_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) throw new ToolError(`No waiver found with id ${waiver_id}`);
    const { data: events } = await supabase.from("envelope_events").select("event_type,created_at").eq("envelope_id", waiver_id).order("created_at", { ascending: false }).limit(10);
    const row = data;
    const signingPath = row.is_group_waiver ? row.group_token ? `/group/${String(row.group_token)}` : null : `/waiver/${String(row.signing_token)}`;
    const waiver = {
      id: String(row.id),
      status: String(row.status),
      signer_name: row.signer_name ?? null,
      signer_email: String(row.signer_email),
      is_group_waiver: Boolean(row.is_group_waiver),
      signing_url: signingPath ? `https://www.rentalwaivers.com${signingPath}` : null,
      created_at: String(row.created_at),
      signed_at: row.signed_at ?? null,
      expires_at: row.expires_at ?? null,
      booking_id: row.booking_id ?? null,
      listing_id: row.listing_id ?? null,
      credits_charged: Number(row.credits_charged ?? 0),
      has_signed_pdf: Boolean(row.pdf_storage_key),
      recent_events: (events ?? []).map((e) => ({
        event_type: String(e.event_type),
        created_at: String(e.created_at)
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(waiver, null, 2) }],
      structuredContent: { waiver }
    };
  }
});

// src/lib/mcp/tools/list-templates.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_templates_default = defineTool3({
  name: "list_templates",
  title: "List waiver templates",
  description: "List the account's waiver templates, with the id needed to send a waiver.",
  inputSchema: {
    active_only: z3.boolean().optional().describe("Only return active templates (default true).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const orgId = await requireOrgId(supabase, ctx.getUserId());
    let query = supabase.from("templates").select("id,name,description,is_active,require_photo,require_video,updated_at").eq("org_id", orgId).order("updated_at", { ascending: false });
    if (active_only !== false) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const templates = (data ?? []).map((row) => {
      const t = row;
      return {
        id: String(t.id),
        name: String(t.name),
        description: t.description ?? null,
        is_active: Boolean(t.is_active),
        require_photo: Boolean(t.require_photo),
        require_video: Boolean(t.require_video),
        updated_at: String(t.updated_at)
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(templates, null, 2) }],
      structuredContent: { templates }
    };
  }
});

// src/lib/mcp/tools/send-waiver.ts
import { defineTool as defineTool4, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var send_waiver_default = defineTool4({
  name: "send_waiver",
  title: "Send a waiver",
  description: "Create a waiver from a template and email it to the signer. Deducts credits from the account, the same as sending from the app.",
  inputSchema: {
    template_id: z4.string().uuid().describe("Template to send (see list_templates)."),
    signer_email: z4.string().trim().email().describe("Email address of the person who must sign."),
    signer_name: z4.string().trim().optional().describe("Name of the signer."),
    booking_id: z4.string().trim().optional().describe("Your own booking or reservation reference."),
    rental_date: z4.string().trim().optional().describe("Rental or effective date for the waiver, as YYYY-MM-DD."),
    expires_in_days: z4.number().int().min(1).max(365).optional().describe("Expire the waiver after this many days.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const orgId = await requireOrgId(supabase, ctx.getUserId());
    const { data: template, error: templateErr } = await supabase.from("templates").select("id,require_photo,require_video").eq("org_id", orgId).eq("id", args.template_id).maybeSingle();
    if (templateErr) return { content: [{ type: "text", text: templateErr.message }], isError: true };
    if (!template) throw new ToolError2(`No template found with id ${args.template_id}`);
    const { data: version } = await supabase.from("template_versions").select("id").eq("template_id", args.template_id).eq("is_current", true).maybeSingle();
    if (!version) throw new ToolError2("This template has no active version yet");
    const { data: org } = await supabase.from("organizations").select("logo_url,brand_color,brand_font").eq("id", orgId).maybeSingle();
    const t = template;
    const o = org ?? {};
    const isBranded = Boolean(o.logo_url || o.brand_color || o.brand_font);
    const cost = 1 + (t.require_photo ? 1 : 0) + (t.require_video ? 2 : 0) + (isBranded ? 1 : 0);
    const { data: envelope, error } = await supabase.from("envelopes").insert({
      org_id: orgId,
      template_version_id: version.id,
      signer_email: args.signer_email,
      signer_name: args.signer_name ?? null,
      booking_id: args.booking_id ?? null,
      status: "sent",
      is_group_waiver: false,
      credits_charged: cost,
      expires_at: args.expires_in_days ? new Date(Date.now() + args.expires_in_days * 864e5).toISOString() : null,
      payload: { booking_id: args.booking_id ?? null, rental_date: args.rental_date ?? null }
    }).select("id,signing_token").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const envelopeRow = envelope;
    const envelopeId = String(envelopeRow.id);
    const { data: creditResult, error: creditErr } = await supabase.rpc("deduct_credit", {
      p_org_id: orgId,
      p_reference_id: envelopeId,
      p_type: "waiver_deduction",
      p_amount: cost,
      p_notes: "sent via agent integration"
    });
    const creditRow = creditResult?.[0];
    if (creditErr || !creditRow?.success) {
      await supabase.from("envelopes").update({ status: "canceled" }).eq("id", envelopeId);
      throw new ToolError2(creditErr?.message || creditRow?.error_message || "Insufficient credits");
    }
    await supabase.from("envelope_events").insert({
      envelope_id: envelopeId,
      event_type: "envelope.sent",
      metadata: { source: "mcp", signer_email: args.signer_email }
    });
    let emailSent = true;
    const { error: emailErr } = await supabase.functions.invoke("send-signing-email", {
      body: { envelope_id: envelopeId }
    });
    if (emailErr) emailSent = false;
    const waiver = {
      id: envelopeId,
      signing_url: `https://www.rentalwaivers.com/waiver/${String(envelopeRow.signing_token)}`,
      credits_charged: cost,
      email_sent: emailSent
    };
    return {
      content: [
        {
          type: "text",
          text: emailSent ? `Waiver sent to ${args.signer_email}. Signing link: ${waiver.signing_url}` : `Waiver created for ${args.signer_email}, but the email failed to send. Share this link instead: ${waiver.signing_url}`
        }
      ],
      structuredContent: { waiver }
    };
  }
});

// src/lib/mcp/tools/account-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.1";
var account_summary_default = defineTool5({
  name: "account_summary",
  title: "Account summary",
  description: "Summarize the signed-in account: organization name, remaining credits, and waiver counts by status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const orgId = await requireOrgId(supabase, ctx.getUserId());
    const [{ data: org }, { data: wallet }, { data: rows }] = await Promise.all([
      supabase.from("organizations").select("name").eq("id", orgId).maybeSingle(),
      supabase.from("wallets").select("credits").eq("org_id", orgId).maybeSingle(),
      supabase.from("envelopes").select("status").eq("org_id", orgId).limit(5e3)
    ]);
    const counts = {};
    for (const row of rows ?? []) {
      const status = String(row.status);
      counts[status] = (counts[status] ?? 0) + 1;
    }
    const summary = {
      organization: org?.name ? String(org.name) : null,
      credits_remaining: Number(wallet?.credits ?? 0),
      total_waivers: (rows ?? []).length,
      waivers_by_status: counts
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { summary }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "llsgwfzoutdpgrgtcbif";
var mcp_default = defineMcp({
  name: "rental-waivers",
  title: "Rental waivers",
  version: "0.1.0",
  instructions: "Tools for Rental Waivers, a digital liability waiver platform. Use `account_summary` for credits and waiver counts, `list_templates` to find a template id, `send_waiver` to email a waiver to a guest, and `list_waivers` / `get_waiver` to check signing status.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [account_summary_default, list_templates_default, send_waiver_default, list_waivers_default, get_waiver_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
